In [ ]:
#ONLY RUN THIS CELL
#No need to run the embeddings
#Can just run models
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/IMM-TSF

!ls data/*/processed/*/text_embeddings_model=GPT2*.pt | wc -l
print("✅ Ready!")

In [ ]:
#RUN ONCE
%cd /content/drive/MyDrive/
!git clone https://github.com/blacksnail789521/IMM-TSF.git
%cd IMM-TSF

/content/drive/MyDrive
fatal: destination path 'IMM-TSF' already exists and is not an empty directory.
/content/drive/MyDrive/IMM-TSF

In [ ]:
#RUN ONCE
!pip install -r requirements.txt

Requirement already satisfied: torch==2.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 1)) (2.7.0)
Requirement already satisfied: pandas==2.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 2)) (2.2.3)
Requirement already satisfied: scikit-learn==1.6.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 3)) (1.6.1)
Requirement already satisfied: reformer_pytorch==1.4.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 4)) (1.4.4)
Requirement already satisfied: stribor==0.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (0.1.0)
Requirement already satisfied: matplotlib==3.10.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 6)) (3.10.3)
Requirement already satisfied: seaborn==0.13.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 7)) (0.13.2)
Requirement already satisfied: geotorch==0.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 8)) (0.3.0)
Requirement already satisfied: transformers==4.51.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 9)) (4.51.3)
Requirement already satisfied: prettytable==3.16.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 10)) (3.16.0)
Requirement already satisfied: accelerate==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 11)) (1.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.5.1.17 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (9.5.1.17)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (0.6.3)
Requirement already satisfied: nvidia-nccl-cu12==2.26.2 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (2.26.2)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (1.11.1.6)
Requirement already satisfied: triton==3.3.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (3.3.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.3->-r requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.3->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.3->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.3->-r requirements.txt (line 2)) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.6.1->-r requirements.txt (line 3)) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.6.1->-r requirements.txt (line 3)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.6.1->-r requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: axial-positional-embedding>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from reformer_pytorch==1.4.4->-r requirements.txt (line 4)) (0.3.12)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from reformer_pytorch==1.4.4->-r requirements.txt (line 4)) (0.8.2)
Requirement already satisfied: local-attention in /usr/local/lib/python3.12/dist-packages (from reformer_pytorch==1.4.4->-r requirements.txt (line 4)) (1.11.2)
Requirement already satisfied: product-key-memory in /usr/local/lib/python3.12/dist-packages (from reformer_pytorch==1.4.4->-r requirements.txt (line 4)) (0.3.0)
Requirement already satisfied: pytest in /usr/local/lib/python3.12/dist-packages (from stribor==0.1.0->-r requirements.txt (line 5)) (8.4.2)
Requirement already satisfied: torchdiffeq==0.2.1 in /usr/local/lib/python3.12/dist-packages (from stribor==0.1.0->-r requirements.txt (line 5)) (0.2.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.3->-r requirements.txt (line 6)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.3->-r requirements.txt (line 6)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.3->-r requirements.txt (line 6)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.3->-r requirements.txt (line 6)) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.3->-r requirements.txt (line 6)) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.3->-r requirements.txt (line 6)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.3->-r requirements.txt (line 6)) (3.3.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3->-r requirements.txt (line 9)) (0.36.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3->-r requirements.txt (line 9)) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3->-r requirements.txt (line 9)) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3->-r requirements.txt (line 9)) (2.32.4)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3->-r requirements.txt (line 9)) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3->-r requirements.txt (line 9)) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3->-r requirements.txt (line 9)) (4.67.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable==3.16.0->-r requirements.txt (line 10)) (0.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate==1.6.0->-r requirements.txt (line 11)) (5.9.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.51.3->-r requirements.txt (line 9)) (1.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.3->-r requirements.txt (line 2)) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch==2.7.0->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch==2.7.0->-r requirements.txt (line 1)) (3.0.3)
Requirement already satisfied: hyper-connections>=0.1.8 in /usr/local/lib/python3.12/dist-packages (from local-attention->reformer_pytorch==1.4.4->-r requirements.txt (line 4)) (0.4.9)
Requirement already satisfied: colt5-attention>=0.10.14 in /usr/local/lib/python3.12/dist-packages (from product-key-memory->reformer_pytorch==1.4.4->-r requirements.txt (line 4)) (0.11.1)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest->stribor==0.1.0->-r requirements.txt (line 5)) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest->stribor==0.1.0->-r requirements.txt (line 5)) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest->stribor==0.1.0->-r requirements.txt (line 5)) (2.20.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.3->-r requirements.txt (line 9)) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.3->-r requirements.txt (line 9)) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.3->-r requirements.txt (line 9)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.3->-r requirements.txt (line 9)) (2026.2.25)
Requirement already satisfied: torch-einops-utils>=0.0.20 in /usr/local/lib/python3.12/dist-packages (from hyper-connections>=0.1.8->local-attention->reformer_pytorch==1.4.4->-r requirements.txt (line 4)) (0.0.30)

In [ ]:
#RUN ONCE
# Install Kaggle API
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.15 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.2.25)

In [ ]:
#RUN ONCE
#Fixes torch error
!pip uninstall transformers timm torchvision torchaudio -y

!pip install transformers==4.45.2

!pip install --no-deps torchvision==0.22.0 torchaudio==2.7.0 \
  --index-url https://download.pytorch.org/whl/cu126

Found existing installation: transformers 4.51.3
Uninstalling transformers-4.51.3:
  Successfully uninstalled transformers-4.51.3
Found existing installation: timm 1.0.26
Uninstalling timm-1.0.26:
  Successfully uninstalled timm-1.0.26
Found existing installation: torchvision 0.25.0+cu128
Uninstalling torchvision-0.25.0+cu128:
  Successfully uninstalled torchvision-0.25.0+cu128
Found existing installation: torchaudio 2.10.0+cu128
Uninstalling torchaudio-2.10.0+cu128:
  Successfully uninstalled torchaudio-2.10.0+cu128
Collecting transformers==4.45.2
  Downloading transformers-4.45.2-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.2) (3.25.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.2) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.2) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.2) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.2) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.2) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.2) (2.32.4)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.2) (0.7.0)
Collecting tokenizers<0.21,>=0.20 (from transformers==4.45.2)
  Downloading tokenizers-0.20.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.2) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.45.2) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.45.2) (1.4.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.45.2) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.45.2) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.45.2) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.45.2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.45.2) (2026.2.25)
Downloading transformers-4.45.2-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 89.3 MB/s eta 0:00:00
Downloading tokenizers-0.20.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 100.0 MB/s eta 0:00:00
Installing collected packages: tokenizers, transformers
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.21.4
    Uninstalling tokenizers-0.21.4:
      Successfully uninstalled tokenizers-0.21.4
Successfully installed tokenizers-0.20.3 transformers-4.45.2
Looking in indexes: https://download.pytorch.org/whl/cu126
Collecting torchvision==0.22.0
  Downloading https://download-r2.pytorch.org/whl/cu126/torchvision-0.22.0%2Bcu126-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Collecting torchaudio==2.7.0
  Downloading https://download-r2.pytorch.org/whl/cu126/torchaudio-2.7.0%2Bcu126-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Downloading https://download-r2.pytorch.org/whl/cu126/torchvision-0.22.0%2Bcu126-cp312-cp312-manylinux_2_28_x86_64.whl (7.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 90.1 MB/s eta 0:00:00
Downloading https://download-r2.pytorch.org/whl/cu126/torchaudio-2.7.0%2Bcu126-cp312-cp312-manylinux_2_28_x86_64.whl (3.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 77.9 MB/s eta 0:00:00
Installing collected packages: torchaudio, torchvision
Successfully installed torchaudio-2.7.0+cu126 torchvision-0.22.0+cu126

In [ ]:
#Run only once and then only run the code chunk in the cell below
# Upload your kaggle.json (download it from kaggle.com/settings → API)
from google.colab import files
files.upload()  # upload kaggle.json
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

Saving kaggle.json to kaggle (1).json

In [ ]:
#Run everytime to load kaggle json API file
!mkdir -p ~/.kaggle
!cp /content/drive/MyDrive/IMM-TSF/kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
#RUN ONCE
# Download and unzip
!kaggle datasets download -d blacksnail789521/time-imm
!unzip -q time-imm.zip -d data/

Dataset URL: https://www.kaggle.com/datasets/blacksnail789521/time-imm
License(s): Attribution 4.0 International (CC BY 4.0)
time-imm.zip: Skipping, found more recently modified local copy (use --force to force download)
replace data/CESNET/processed/10.0.178.41/text.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: A

In [ ]:
#RUN ONCE
# Skip MIMIC (one-time fix)
!sed -i 's/"MIMIC", *//g' compute_text_embeddings.py
!sed -i "s/'MIMIC', *//g" compute_text_embeddings.py

sed: can't read compute_text_embeddings.py: No such file or directory
sed: can't read compute_text_embeddings.py: No such file or directory

In [ ]:
#RUN ONCE
#Creates embeddings for all the datasets except for MIMIC
!python compute_text_embeddings.py --llm_model GPT2

### LLM model: GPT2 ###
### Processing dataset: ClusterTrace ###
tokenizer_config.json: 100% 26.0/26.0 [00:00<00:00, 234kB/s]
config.json: 100% 665/665 [00:00<00:00, 5.92MB/s]
vocab.json: 1.04MB [00:00, 43.2MB/s]
merges.txt: 456kB [00:00, 116MB/s]
tokenizer.json: 1.36MB [00:00, 146MB/s]
Detected 1 GPUs. Using model parallelism.
model.safetensors: 100% 548M/548M [00:02<00:00, 257MB/s]
Loaded GPT2 with 6 layers for fusion.
[1/3] Processing record: 1c6afd5c227e89b8a29589f4
[SKIP] Embeddings already exist for '1c6afd5c227e89b8a29589f4', skipping.
[2/3] Processing record: 35fc40d2844c0b899c1ceb1e
[SKIP] Embeddings already exist for '35fc40d2844c0b899c1ceb1e', skipping.
[3/3] Processing record: 7077ec572d50395cafcbcb7d
[SKIP] Embeddings already exist for '7077ec572d50395cafcbcb7d', skipping.

In [ ]:
#Verify the embeddings were created
!ls data/*/processed/*/text_embeddings_model=GPT2*.pt | head -5

data/CESNET/processed/10.0.178.41/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
data/CESNET/processed/10.0.178.41/text_embeddings_model=GPT2_layers=full_maxlen=1024.pt
data/CESNET/processed/10.0.212.206/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
data/CESNET/processed/10.0.212.206/text_embeddings_model=GPT2_layers=full_maxlen=1024.pt
data/CESNET/processed/10.0.31.13/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt

In [ ]:
# Total embeddings count
!ls data/*/processed/*/text_embeddings_model=GPT2*.pt | wc -l

76

In [ ]:
#Test to see if GPU is running
import torch
print("GPU available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

GPU available: True
GPU: Tesla T4

In [ ]:
!pip install -r requirements.txt

Requirement already satisfied: torch==2.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 1)) (2.7.0)
Requirement already satisfied: pandas==2.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 2)) (2.2.3)
Requirement already satisfied: scikit-learn==1.6.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 3)) (1.6.1)
Requirement already satisfied: reformer_pytorch==1.4.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 4)) (1.4.4)
Requirement already satisfied: stribor==0.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (0.1.0)
Requirement already satisfied: matplotlib==3.10.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 6)) (3.10.3)
Requirement already satisfied: seaborn==0.13.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 7)) (0.13.2)
Requirement already satisfied: geotorch==0.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 8)) (0.3.0)
Collecting transformers==4.51.3 (from -r requirements.txt (line 9))
  Using cached transformers-4.51.3-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: prettytable==3.16.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 10)) (3.16.0)
Requirement already satisfied: accelerate==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 11)) (1.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.5.1.17 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (9.5.1.17)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (0.6.3)
Requirement already satisfied: nvidia-nccl-cu12==2.26.2 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (2.26.2)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (1.11.1.6)
Requirement already satisfied: triton==3.3.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.7.0->-r requirements.txt (line 1)) (3.3.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.3->-r requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.3->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.3->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.3->-r requirements.txt (line 2)) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.6.1->-r requirements.txt (line 3)) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.6.1->-r requirements.txt (line 3)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.6.1->-r requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: axial-positional-embedding>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from reformer_pytorch==1.4.4->-r requirements.txt (line 4)) (0.3.12)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from reformer_pytorch==1.4.4->-r requirements.txt (line 4)) (0.8.2)
Requirement already satisfied: local-attention in /usr/local/lib/python3.12/dist-packages (from reformer_pytorch==1.4.4->-r requirements.txt (line 4)) (1.11.2)
Requirement already satisfied: product-key-memory in /usr/local/lib/python3.12/dist-packages (from reformer_pytorch==1.4.4->-r requirements.txt (line 4)) (0.3.0)
Requirement already satisfied: pytest in /usr/local/lib/python3.12/dist-packages (from stribor==0.1.0->-r requirements.txt (line 5)) (8.4.2)
Requirement already satisfied: torchdiffeq==0.2.1 in /usr/local/lib/python3.12/dist-packages (from stribor==0.1.0->-r requirements.txt (line 5)) (0.2.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.3->-r requirements.txt (line 6)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.3->-r requirements.txt (line 6)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.3->-r requirements.txt (line 6)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.3->-r requirements.txt (line 6)) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.3->-r requirements.txt (line 6)) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.3->-r requirements.txt (line 6)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.3->-r requirements.txt (line 6)) (3.3.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3->-r requirements.txt (line 9)) (0.36.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3->-r requirements.txt (line 9)) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3->-r requirements.txt (line 9)) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3->-r requirements.txt (line 9)) (2.32.4)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.51.3->-r requirements.txt (line 9))
  Using cached tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3->-r requirements.txt (line 9)) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3->-r requirements.txt (line 9)) (4.67.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable==3.16.0->-r requirements.txt (line 10)) (0.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate==1.6.0->-r requirements.txt (line 11)) (5.9.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.51.3->-r requirements.txt (line 9)) (1.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.3->-r requirements.txt (line 2)) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch==2.7.0->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch==2.7.0->-r requirements.txt (line 1)) (3.0.3)
Requirement already satisfied: hyper-connections>=0.1.8 in /usr/local/lib/python3.12/dist-packages (from local-attention->reformer_pytorch==1.4.4->-r requirements.txt (line 4)) (0.4.9)
Requirement already satisfied: colt5-attention>=0.10.14 in /usr/local/lib/python3.12/dist-packages (from product-key-memory->reformer_pytorch==1.4.4->-r requirements.txt (line 4)) (0.11.1)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest->stribor==0.1.0->-r requirements.txt (line 5)) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest->stribor==0.1.0->-r requirements.txt (line 5)) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest->stribor==0.1.0->-r requirements.txt (line 5)) (2.20.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.3->-r requirements.txt (line 9)) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.3->-r requirements.txt (line 9)) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.3->-r requirements.txt (line 9)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.3->-r requirements.txt (line 9)) (2026.2.25)
Requirement already satisfied: torch-einops-utils>=0.0.20 in /usr/local/lib/python3.12/dist-packages (from hyper-connections>=0.1.8->local-attention->reformer_pytorch==1.4.4->-r requirements.txt (line 4)) (0.0.30)
Using cached transformers-4.51.3-py3-none-any.whl (10.4 MB)
Using cached tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Installing collected packages: tokenizers, transformers
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.20.3
    Uninstalling tokenizers-0.20.3:
      Successfully uninstalled tokenizers-0.20.3
  Attempting uninstall: transformers
    Found existing installation: transformers 4.45.2
    Uninstalling transformers-4.45.2:
      Successfully uninstalled transformers-4.45.2
Successfully installed tokenizers-0.21.4 transformers-4.51.3

In [ ]:
%cd /content/drive/MyDrive/IMM-TSF
#patching main.py for the CESNET empty val set

/content/drive/MyDrive/IMM-TSF

In [ ]:
from pathlib import Path
import shutil

eval_path = Path("/content/drive/MyDrive/IMM-TSF/lib/evaluation.py")
backup_path = Path("/content/drive/MyDrive/IMM-TSF/lib/evaluation_backup_before_cesnet_patch.py")

# Back up once
if eval_path.exists() and not backup_path.exists():
    shutil.copy(eval_path, backup_path)
    print(f"Backup created: {backup_path}")

text = eval_path.read_text(encoding="utf-8")

target = "n_avai_var = torch.count_nonzero(n_eval_samples)"
replacement = """# ---- auto-patch for empty validation/test splits ----
    if isinstance(n_eval_samples, int):
        if n_eval_samples == 0:
            return {
                "loss": float("nan"),
                "mse": float("nan"),
                "mae": float("nan"),
                "rmse": float("nan"),
                "mape": float("nan"),
            }
        n_eval_samples = torch.tensor(n_eval_samples)

    n_avai_var = torch.count_nonzero(n_eval_samples)

    if isinstance(n_avai_var, torch.Tensor) and n_avai_var.item() == 0:
        return {
            "loss": float("nan"),
            "mse": float("nan"),
            "mae": float("nan"),
            "rmse": float("nan"),
            "mape": float("nan"),
        }"""

if target not in text:
    print("Target line not found. Printing nearby lines for inspection:")
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if "count_nonzero" in line or "n_eval_samples" in line:
            start = max(0, i-5)
            end = min(len(lines), i+6)
            print(f"\n--- lines {start+1} to {end} ---")
            for j in range(start, end):
                print(f"{j+1:04d}: {lines[j]}")
else:
    text = text.replace(target, replacement)
    eval_path.write_text(text, encoding="utf-8")
    print(f"Patched: {eval_path}")

    # Show the patched block
    lines = eval_path.read_text(encoding="utf-8").splitlines()
    for i, line in enumerate(lines):
        if "auto-patch for empty validation/test splits" in line:
            start = max(0, i-2)
            end = min(len(lines), i+18)
            print(f"\n--- patched lines {start+1} to {end} ---")
            for j in range(start, end):
                print(f"{j+1:04d}: {lines[j]}")
            break

Patched: /content/drive/MyDrive/IMM-TSF/lib/evaluation.py

--- patched lines 257 to 276 ---
0257:         n_eval_samples_mape += mask_count_mape
0258:
0259:     # ---- auto-patch for empty validation/test splits ----
0260:     if isinstance(n_eval_samples, int):
0261:         if n_eval_samples == 0:
0262:             return {
0263:                 "loss": float("nan"),
0264:                 "mse": float("nan"),
0265:                 "mae": float("nan"),
0266:                 "rmse": float("nan"),
0267:                 "mape": float("nan"),
0268:             }
0269:         n_eval_samples = torch.tensor(n_eval_samples)
0270:
0271:     # ---- auto-patch for empty validation/test splits ----
0272:     if isinstance(n_eval_samples, int):
0273:         if n_eval_samples == 0:
0274:             return {
0275:                 "loss": float("nan"),
0276:                 "mse": float("nan"),

In [ ]:
# --- Clean PyTorch / TorchVision / Transformers environment for IMM-TSF on Colab ---

!pip uninstall -y torch torchvision torchaudio transformers timm

# Install a matched PyTorch stack
!pip install -q torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cu126

# Install the transformers version your notebook was using
!pip install -q transformers==4.45.2 timm reformer-pytorch

# Optional but useful
!pip install -q pandas numpy matplotlib tqdm scikit-learn pyyaml

# Restart runtime automatically so imports reset cleanly
import os, IPython
print("Installed. Restarting runtime now...")
os.kill(os.getpid(), 9)

Found existing installation: torch 2.7.0
Uninstalling torch-2.7.0:
  Successfully uninstalled torch-2.7.0
Found existing installation: torchvision 0.22.0+cu126
Uninstalling torchvision-0.22.0+cu126:
  Successfully uninstalled torchvision-0.22.0+cu126
Found existing installation: torchaudio 2.7.0+cu126
Uninstalling torchaudio-2.7.0+cu126:
  Successfully uninstalled torchaudio-2.7.0+cu126
Found existing installation: transformers 4.51.3
Uninstalling transformers-4.51.3:
  Successfully uninstalled transformers-4.51.3
WARNING: Skipping timm as it is not installed.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 866.8/866.8 MB 2.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
peft 0.18.1 requires transformers, which is not installed.
sentence-transformers 5.3.0 requires transformers<6.0.0,>=4.41.0, which is not installed.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 56.1 MB/s eta 0:00:00

In [ ]:
%cd /content/drive/MyDrive/IMM-TSF
!pwd
!ls

/content/drive/MyDrive/IMM-TSF
/content/drive/MyDrive/IMM-TSF
 compute_text_embeddings_backup_before_cesnet.py	 logs
 compute_text_embeddings_backup_before_clustertrace.py	 main_all.py
 compute_text_embeddings.py				 main_all.sh
 data							 main.py
 fusions						 models
 go.sh							 README.md
'kaggle (1).json'					 requirements.txt
 kaggle.json						 run_logs
 layers							 time-imm.zip
 lib							 utils
 LICENSE

In [ ]:
import torch
import torchvision
import transformers

print("torch:", torch.__version__)
print("torchvision:", torchvision.__version__)
print("transformers:", transformers.__version__)
print("cuda:", torch.cuda.is_available())
print("gpu:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "no gpu")

torch: 2.7.0+cu126
torchvision: 0.22.0+cu126
transformers: 4.45.2
cuda: True
gpu: Tesla T4

In [ ]:
from pathlib import Path
import shutil

eval_path = Path("/content/drive/MyDrive/IMM-TSF/lib/evaluation.py")
backup_path = Path("/content/drive/MyDrive/IMM-TSF/lib/evaluation_backup_before_cesnet_patch.py")

if eval_path.exists() and not backup_path.exists():
    shutil.copy(eval_path, backup_path)

text = eval_path.read_text(encoding="utf-8")

target = "n_avai_var = torch.count_nonzero(n_eval_samples)"
replacement = """# ---- auto-patch for empty validation/test splits ----
    if isinstance(n_eval_samples, int):
        if n_eval_samples == 0:
            return {
                "loss": float("nan"),
                "mse": float("nan"),
                "mae": float("nan"),
                "rmse": float("nan"),
                "mape": float("nan"),
            }
        n_eval_samples = torch.tensor(n_eval_samples)

    n_avai_var = torch.count_nonzero(n_eval_samples)

    if isinstance(n_avai_var, torch.Tensor) and n_avai_var.item() == 0:
        return {
            "loss": float("nan"),
            "mse": float("nan"),
            "mae": float("nan"),
            "rmse": float("nan"),
            "mape": float("nan"),
        }"""

if target in text:
    text = text.replace(target, replacement)
    eval_path.write_text(text, encoding="utf-8")
    print("Patched evaluation.py")
else:
    print("Target line not found.")

Patched evaluation.py

In [ ]:
#CESNET tPatchGNN uniimodal
!python main.py \
  --dataset CESNET \
  --model tPatchGNN \
  --split_method instance \
  --history 12 \
  --pred_window 6 \
  --stride 6 \
  --patch_size 6 \
  --patch_stride 6 \
  --npatch 2 \
  -b 16 \
  --epoch 20 \
  --seed 42

PID, device: 12706 cuda
Using dataset path: /content/drive/MyDrive/IMM-TSF/data/CESNET
Record 10.0.178.41: 11 chunks created, 5 dropped (31.25%)
Record 10.0.212.206: 11 chunks created, 3 dropped (21.43%)
Record 10.0.31.13: 11 chunks created, 5 dropped (31.25%)
Record 10.0.64.221: 11 chunks created, 5 dropped (31.25%)
Record 10.0.90.172: 11 chunks created, 5 dropped (31.25%)
Record firewall-3127: 11 chunks created, 5 dropped (31.25%)
Record firewall-8704: 11 chunks created, 5 dropped (31.25%)
Record router-1902: 11 chunks created, 5 dropped (31.25%)
Record router-7669: 11 chunks created, 0 dropped (0.00%)
Record server-1245: 11 chunks created, 7 dropped (38.89%)
Record switch-9995: 11 chunks created, 5 dropped (31.25%)
+-------------------------------------+-----------------------------------------+
|                Metric               |                  Value                  |
+-------------------------------------+-----------------------------------------+
|             num_entities            |                    11                   |
|             num_features            |                    10                   |
|        num_unique_timestamps        |                  18666                  |
|           num_observations          |                  187020                 |
|  Feat observability entropy (norm)  |                   1.0                   |
| Temporal observation entropy (norm) |                   1.0                   |
|               Mean IOI              |                0.049 days               |
|               timespan              | 2023-12-31 23:23:10~2024-03-24 07:33:41 |
|               num_text              |                    81                   |
|     Text temporal entropy (norm)    |                  0.9671                 |
+-------------------------------------+-----------------------------------------+
After chunking & splitting (instance): train=43, val=12, test=16
Using Patch Collate Fn: patch_size=6, npatch=2, patch_stride=6
Scanning train split (3 batches)...
Scanning val split (1 batches)...
Scanning test split (1 batches)...
/content/drive/MyDrive/IMM-TSF/main.py
2026-04-06 23:52:07
main.py --dataset CESNET --model tPatchGNN --split_method instance --history 12 --pred_window 6 --stride 6 --patch_size 6 --patch_stride 6 --npatch 2 -b 16 --epoch 20 --seed 42
Namespace(overwrite_args=False, state='def', seed=42, gpu='0', dataset='CESNET', data_root='./data', n=100000000, split_method='instance', enable_text=False, use_text_embeddings=False, time_unit='days', history=12, pred_window=6, stride=6, patch_size=6, npatch=2, patch_stride=6, model='tPatchGNN', outlayer='Linear', hid_dim=64, te_dim=10, node_dim=10, hop=1, tf_layer=1, nlayer=1, top_k=5, e_layers=2, d_layers=1, d_ff=2048, d_model=512, n_heads=2, num_kernels=6, embed='timeF', freq='h', moving_avg=25, factor=1, activation='gelu', distil=True, down_sampling_layers=3, down_sampling_window=2, down_sampling_method='avg', decomp_method='moving_avg', channel_independence=1, use_norm=1, n_vars=7, mode='mix_channel', AP_levels=3, use_decoder=True, d_mode='common_channel', d_d_model=64, ts_vocab_size=1000, domain_des='The Electricity Transformer Temperature (ETT) is a crucial indicator in the electric power long-term deployment.', input_token_len=576, output_token_len=96, llm_model_timellm='GPT2', llm_layers_timellm=6, nf_latents=20, nf_rec_dims=40, nf_gru_units=32, nf_hidden_layers=3, nf_hidden_dim=32, nf_flow_model='coupling', nf_flow_layers=2, nf_time_net='TimeLinear', nf_time_hidden_dim=8, nf_solver='dopri5', nf_solver_step=0.05, nf_atol=0.0001, nf_rtol=0.001, nf_odenet='concat', nf_activation='Tanh', nf_final_activation='Identity', nf_obsrv_std=0.01, nf_weight_decay=0.0001, nf_quantization=0.0, nf_max_t=5.0, nf_mixing=0.0001, nf_gob_prep_hidden=10, nf_gob_cov_hidden=50, nf_gob_p_hidden=25, nf_invertible=1, nf_components=8, nf_decoder_type='continuous', nf_rnn='gru', nf_marks=0, nf_density_model='independent', nf_extrap=0, cru_lsd=64, cru_hidden_units=64, cru_enc_num_layers=1, cru_dec_num_layers=1, cru_num_layers=1, cru_dropout_type='None', cru_dropout_rate=0.0, cru_use_gate_hidden_states=True, cru_use_ode_for_gru=False, cru_use_decay_gravity_gate=True, cru_use_gravity_gate=True, cru_use_decay_input_gate=True, cru_use_input_gate=True, cru_use_skip_connection=True, cru_solver='euler', ts=0.3, grad_clip=False, ode_latents=20, ode_units=32, ode_gen_layers=1, ode_rec_dims=32, ode_rec_layers=1, ode_gru_units=32, ode_poisson=False, ode_classif=False, ode_linear_classif=False, ode_z0_encoder='odernn', ode_obsrv_std=0.01, ode_n_traj_samples=1, TTF_module='TTF_T2V_XAttn', MMF_module='MMF_XAttn_Add', llm_model_fusion='GPT2', llm_layers_fusion=6, max_length=1024, d_txt=768, recency_sigma=1.0, n_heads_fusion=1, kappa=0.5, epoch=20, patience=3, early_stop_delta=0.0001, lr=0.001, w_decay=0.01, batch_size=16, dropout=0.1, use_amp=False, logmode='a', save='experiments/', load=None, device=device(type='cuda'), PID=12706, C=10, enc_in=10, c_out=10, input_len=2, pred_len=136)
Epoch 0, Loss: 1.04289: 100% 3/3 [00:01<00:00,  2.51it/s]
100% 1/1 [00:00<00:00, 36.57it/s]
100% 1/1 [00:00<00:00, 34.99it/s]
- Epoch 000, ExpID 35003
Train - Loss (one batch): 1.04289
Val - Loss, MSE, MAE: 0.96372, 0.96372, 0.76691
Test - Best epoch, Loss, MSE, MAE: 0, 1.02502, 1.02502, 0.79341
Time spent: 1.25s
Epoch 1, Loss: 0.98706: 100% 3/3 [00:00<00:00,  5.84it/s]
100% 1/1 [00:00<00:00, 43.80it/s]
100% 1/1 [00:00<00:00, 36.02it/s]
- Epoch 001, ExpID 35003
Train - Loss (one batch): 0.98706
Val - Loss, MSE, MAE: 0.96175, 0.96175, 0.77250
Test - Best epoch, Loss, MSE, MAE: 1, 1.02652, 1.02652, 0.80236
Time spent: 0.57s
Epoch 2, Loss: 1.00680: 100% 3/3 [00:00<00:00,  6.43it/s]
100% 1/1 [00:00<00:00, 41.45it/s]
- Epoch 002, ExpID 35003
Train - Loss (one batch): 1.00680
Val - Loss, MSE, MAE: 0.96178, 0.96178, 0.77276
Test - Best epoch, Loss, MSE, MAE: 1, 1.02652, 1.02652, 0.80236
Time spent: 0.49s
Epoch 3, Loss: 0.99447: 100% 3/3 [00:00<00:00,  6.45it/s]
100% 1/1 [00:00<00:00, 42.66it/s]
- Epoch 003, ExpID 35003
Train - Loss (one batch): 0.99447
Val - Loss, MSE, MAE: 0.96195, 0.96195, 0.76945
Test - Best epoch, Loss, MSE, MAE: 1, 1.02652, 1.02652, 0.80236
Time spent: 0.49s
Epoch 4, Loss: 0.94032: 100% 3/3 [00:00<00:00,  7.33it/s]
100% 1/1 [00:00<00:00, 43.76it/s]
- Epoch 004, ExpID 35003
Train - Loss (one batch): 0.94032
Val - Loss, MSE, MAE: 0.96196, 0.96196, 0.76937
Test - Best epoch, Loss, MSE, MAE: 1, 1.02652, 1.02652, 0.80236
Time spent: 0.43s
Exp has been early stopped!
loss: 1.0265249013900757
mse: 1.0265249013900757
mae: 0.8023554086685181
rmse: 1.0131756067276
mape: -0.20147517323493958
### Done ###

In [ ]:
!pip uninstall -y torch torchvision torchaudio transformers timm reformer-pytorch

Found existing installation: torch 2.7.0+cu126
Uninstalling torch-2.7.0+cu126:
  Successfully uninstalled torch-2.7.0+cu126
Found existing installation: torchvision 0.22.0+cu126
Uninstalling torchvision-0.22.0+cu126:
  Successfully uninstalled torchvision-0.22.0+cu126
Found existing installation: torchaudio 2.7.0+cu126
Uninstalling torchaudio-2.7.0+cu126:
  Successfully uninstalled torchaudio-2.7.0+cu126
Found existing installation: transformers 4.45.2
Uninstalling transformers-4.45.2:
  Successfully uninstalled transformers-4.45.2
Found existing installation: timm 1.0.26
Uninstalling timm-1.0.26:
  Successfully uninstalled timm-1.0.26
Found existing installation: reformer-pytorch 1.4.4
Uninstalling reformer-pytorch-1.4.4:
  Successfully uninstalled reformer-pytorch-1.4.4

In [ ]:
!pip install -q torch==2.7.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cu126
!pip install -q transformers==4.45.2 reformer-pytorch pandas numpy matplotlib tqdm scikit-learn pyyaml

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
peft 0.18.1 requires transformers, which is not installed.
sentence-transformers 5.3.0 requires transformers<6.0.0,>=4.41.0, which is not installed.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.

In [ ]:
import os
os.kill(os.getpid(), 9)

In [ ]:
%cd /content/drive/MyDrive/IMM-TSF
!pwd

/content/drive/MyDrive/IMM-TSF
/content/drive/MyDrive/IMM-TSF

In [ ]:
import torch
import transformers

print("torch:", torch.__version__)
print("transformers:", transformers.__version__)
print("cuda:", torch.cuda.is_available())
print("gpu:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "no gpu")

torch: 2.7.0+cu126
transformers: 4.45.2
cuda: True
gpu: Tesla T4

In [ ]:
#CESNET tPatchGNN multimodal
!python main.py \
  --dataset CESNET \
  --model tPatchGNN \
  --TTF_module TTF_RecAvg \
  --MMF_module MMF_GR_Add \
  --llm_model_fusion GPT2 \
  --use_text_embeddings \
  --enable_text \
  --split_method instance \
  --history 12 \
  --pred_window 6 \
  --stride 6 \
  --patch_size 6 \
  --patch_stride 6 \
  --npatch 2 \
  -b 16 \
  --epoch 20 \
  --seed 42

PID, device: 16326 cuda
Using dataset path: /content/drive/MyDrive/IMM-TSF/data/CESNET
Traceback (most recent call last):
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 1279, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 981, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets
    ds = ChunkedTimeSeriesDataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/IMM-TSF/lib/parse_datasets.py", line 149, in __init__
    raise FileNotFoundError(f"Missing text embeddings file: {path}")
FileNotFoundError: Missing text embeddings file: /content/drive/MyDrive/IMM-TSF/data/CESNET/processed/10.0.178.41/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt

In [ ]:
import os
from pathlib import Path

base = Path("/content/drive/MyDrive/IMM-TSF/data/CESNET/processed")
pts = list(base.rglob("text_embeddings_model=GPT2_layers=6_maxlen=1024.pt"))

print("Number of CESNET embedding files found:", len(pts))
print("Sample files:")
for p in pts[:10]:
    print(p)

Number of CESNET embedding files found: 0
Sample files:

In [ ]:
from pathlib import Path
import shutil

path = Path("/content/drive/MyDrive/IMM-TSF/compute_text_embeddings.py")
backup = Path("/content/drive/MyDrive/IMM-TSF/compute_text_embeddings_backup_before_cesnet.py")

if path.exists() and not backup.exists():
    shutil.copy(path, backup)
    print("Backup created:", backup)

text = path.read_text(encoding="utf-8")

# Force absolute processed path
text = text.replace(
    'base_dir = f"data/{data_name}/processed"',
    r'base_dir = rf"/content/drive/MyDrive/IMM-TSF/data/{data_name}/processed"'
)

# If your file currently has a data_name_list block, replace it
import re
text = re.sub(
    r"data_name_list\s*=\s*\[[^\]]*\]",
    'data_name_list = ["CESNET"]',
    text,
    flags=re.DOTALL
)

# Force GPT2 layer setting to match what main.py expects
text = re.sub(
    r"llm_layers_fusion\s*=\s*None",
    "llm_layers_fusion = 6",
    text
)

path.write_text(text, encoding="utf-8")
print("Patched compute_text_embeddings.py for CESNET only.")

Backup created: /content/drive/MyDrive/IMM-TSF/compute_text_embeddings_backup_before_cesnet.py
Patched compute_text_embeddings.py for CESNET only.

In [ ]:
!cd /content/drive/MyDrive/IMM-TSF && python compute_text_embeddings.py

### LLM model: GPT2 ###
### Processing dataset: CESNET ###
tokenizer_config.json: 100% 26.0/26.0 [00:00<00:00, 223kB/s]
config.json: 100% 665/665 [00:00<00:00, 7.48MB/s]
vocab.json: 1.04MB [00:00, 45.0MB/s]
merges.txt: 456kB [00:00, 119MB/s]
tokenizer.json: 1.36MB [00:00, 129MB/s]
Detected 1 GPUs. Using model parallelism.
model.safetensors: 100% 548M/548M [00:02<00:00, 219MB/s]
Loaded GPT2 with 6 layers for fusion.
[1/11] Processing record: 10.0.178.41
Embedding notes for record '10.0.178.41'...
Wrote embeddings to /content/drive/MyDrive/IMM-TSF/data/CESNET/processed/10.0.178.41/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
[2/11] Processing record: 10.0.212.206
Embedding notes for record '10.0.212.206'...
Wrote embeddings to /content/drive/MyDrive/IMM-TSF/data/CESNET/processed/10.0.212.206/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
[3/11] Processing record: 10.0.31.13
Embedding notes for record '10.0.31.13'...
Wrote embeddings to /content/drive/MyDrive/IMM-TSF/data/CESNET/processed/10.0.31.13/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
[4/11] Processing record: 10.0.64.221
Embedding notes for record '10.0.64.221'...
Wrote embeddings to /content/drive/MyDrive/IMM-TSF/data/CESNET/processed/10.0.64.221/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
[5/11] Processing record: 10.0.90.172
Embedding notes for record '10.0.90.172'...
Wrote embeddings to /content/drive/MyDrive/IMM-TSF/data/CESNET/processed/10.0.90.172/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
[6/11] Processing record: firewall-3127
Embedding notes for record 'firewall-3127'...
Wrote embeddings to /content/drive/MyDrive/IMM-TSF/data/CESNET/processed/firewall-3127/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
[7/11] Processing record: firewall-8704
Embedding notes for record 'firewall-8704'...
Wrote embeddings to /content/drive/MyDrive/IMM-TSF/data/CESNET/processed/firewall-8704/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
[8/11] Processing record: router-1902
Embedding notes for record 'router-1902'...
Wrote embeddings to /content/drive/MyDrive/IMM-TSF/data/CESNET/processed/router-1902/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
[9/11] Processing record: router-7669
Embedding notes for record 'router-7669'...
Wrote embeddings to /content/drive/MyDrive/IMM-TSF/data/CESNET/processed/router-7669/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
[10/11] Processing record: server-1245
Embedding notes for record 'server-1245'...
Wrote embeddings to /content/drive/MyDrive/IMM-TSF/data/CESNET/processed/server-1245/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
[11/11] Processing record: switch-9995
Embedding notes for record 'switch-9995'...
Wrote embeddings to /content/drive/MyDrive/IMM-TSF/data/CESNET/processed/switch-9995/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt

In [ ]:
import os
from pathlib import Path

base = Path("/content/drive/MyDrive/IMM-TSF/data/CESNET/processed")
pts = list(base.rglob("text_embeddings_model=GPT2_layers=6_maxlen=1024.pt"))

print("Number of CESNET embedding files found:", len(pts))
for p in pts[:10]:
    print(p)

Number of CESNET embedding files found: 11
/content/drive/MyDrive/IMM-TSF/data/CESNET/processed/10.0.178.41/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
/content/drive/MyDrive/IMM-TSF/data/CESNET/processed/10.0.212.206/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
/content/drive/MyDrive/IMM-TSF/data/CESNET/processed/10.0.31.13/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
/content/drive/MyDrive/IMM-TSF/data/CESNET/processed/10.0.64.221/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
/content/drive/MyDrive/IMM-TSF/data/CESNET/processed/10.0.90.172/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
/content/drive/MyDrive/IMM-TSF/data/CESNET/processed/firewall-3127/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
/content/drive/MyDrive/IMM-TSF/data/CESNET/processed/firewall-8704/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
/content/drive/MyDrive/IMM-TSF/data/CESNET/processed/router-1902/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
/content/drive/MyDrive/IMM-TSF/data/CESNET/processed/router-7669/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
/content/drive/MyDrive/IMM-TSF/data/CESNET/processed/server-1245/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt

In [ ]:
#CESNET tPatchGNN multimodal
!python main.py \
  --dataset CESNET \
  --model tPatchGNN \
  --TTF_module TTF_RecAvg \
  --MMF_module MMF_GR_Add \
  --llm_model_fusion GPT2 \
  --use_text_embeddings \
  --enable_text \
  --split_method instance \
  --history 12 \
  --pred_window 6 \
  --stride 6 \
  --patch_size 6 \
  --patch_stride 6 \
  --npatch 2 \
  -b 16 \
  --epoch 20 \
  --seed 42

PID, device: 17089 cuda
Using dataset path: /content/drive/MyDrive/IMM-TSF/data/CESNET
Record 10.0.178.41: 11 chunks created, 5 dropped (31.25%)
Record 10.0.212.206: 11 chunks created, 3 dropped (21.43%)
Record 10.0.31.13: 11 chunks created, 4 dropped (26.67%)
Record 10.0.64.221: 11 chunks created, 4 dropped (26.67%)
Record 10.0.90.172: 11 chunks created, 5 dropped (31.25%)
Record firewall-3127: 11 chunks created, 5 dropped (31.25%)
Record firewall-8704: 11 chunks created, 3 dropped (21.43%)
Record router-1902: 11 chunks created, 6 dropped (35.29%)
Record router-7669: 11 chunks created, 2 dropped (15.38%)
Record server-1245: 11 chunks created, 5 dropped (31.25%)
Record switch-9995: 11 chunks created, 4 dropped (26.67%)
+-------------------------------------+-----------------------------------------+
|                Metric               |                  Value                  |
+-------------------------------------+-----------------------------------------+
|             num_entities            |                    11                   |
|             num_features            |                    10                   |
|        num_unique_timestamps        |                  18666                  |
|           num_observations          |                  187020                 |
|  Feat observability entropy (norm)  |                   1.0                   |
| Temporal observation entropy (norm) |                   1.0                   |
|               Mean IOI              |                0.049 days               |
|               timespan              | 2023-12-31 23:23:10~2024-03-24 07:33:41 |
|               num_text              |                    81                   |
|     Text temporal entropy (norm)    |                  0.9671                 |
+-------------------------------------+-----------------------------------------+
After chunking & splitting (instance): train=42, val=15, test=18
Using Patch Collate Fn: patch_size=6, npatch=2, patch_stride=6
Scanning train split (3 batches)...
Scanning val split (1 batches)...
Scanning test split (2 batches)...
Using TTF module: TTF_RecAvg
Using MMF module: MMF_GR_Add
/content/drive/MyDrive/IMM-TSF/main.py
2026-04-02 00:34:20
main.py --dataset CESNET --model tPatchGNN --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion GPT2 --use_text_embeddings --enable_text --split_method instance --history 12 --pred_window 6 --stride 6 --patch_size 6 --patch_stride 6 --npatch 2 -b 16 --epoch 20 --seed 42
Namespace(overwrite_args=False, state='def', seed=42, gpu='0', dataset='CESNET', data_root='./data', n=100000000, split_method='instance', enable_text=True, use_text_embeddings=True, time_unit='days', history=12, pred_window=6, stride=6, patch_size=6, npatch=2, patch_stride=6, model='tPatchGNN', outlayer='Linear', hid_dim=64, te_dim=10, node_dim=10, hop=1, tf_layer=1, nlayer=1, top_k=5, e_layers=2, d_layers=1, d_ff=2048, d_model=512, n_heads=2, num_kernels=6, embed='timeF', freq='h', moving_avg=25, factor=1, activation='gelu', distil=True, down_sampling_layers=3, down_sampling_window=2, down_sampling_method='avg', decomp_method='moving_avg', channel_independence=1, use_norm=1, n_vars=7, mode='mix_channel', AP_levels=3, use_decoder=True, d_mode='common_channel', d_d_model=64, ts_vocab_size=1000, domain_des='The Electricity Transformer Temperature (ETT) is a crucial indicator in the electric power long-term deployment.', input_token_len=576, output_token_len=96, llm_model_timellm='GPT2', llm_layers_timellm=6, nf_latents=20, nf_rec_dims=40, nf_gru_units=32, nf_hidden_layers=3, nf_hidden_dim=32, nf_flow_model='coupling', nf_flow_layers=2, nf_time_net='TimeLinear', nf_time_hidden_dim=8, nf_solver='dopri5', nf_solver_step=0.05, nf_atol=0.0001, nf_rtol=0.001, nf_odenet='concat', nf_activation='Tanh', nf_final_activation='Identity', nf_obsrv_std=0.01, nf_weight_decay=0.0001, nf_quantization=0.0, nf_max_t=5.0, nf_mixing=0.0001, nf_gob_prep_hidden=10, nf_gob_cov_hidden=50, nf_gob_p_hidden=25, nf_invertible=1, nf_components=8, nf_decoder_type='continuous', nf_rnn='gru', nf_marks=0, nf_density_model='independent', nf_extrap=0, cru_lsd=64, cru_hidden_units=64, cru_enc_num_layers=1, cru_dec_num_layers=1, cru_num_layers=1, cru_dropout_type='None', cru_dropout_rate=0.0, cru_use_gate_hidden_states=True, cru_use_ode_for_gru=False, cru_use_decay_gravity_gate=True, cru_use_gravity_gate=True, cru_use_decay_input_gate=True, cru_use_input_gate=True, cru_use_skip_connection=True, cru_solver='euler', ts=0.3, grad_clip=False, ode_latents=20, ode_units=32, ode_gen_layers=1, ode_rec_dims=32, ode_rec_layers=1, ode_gru_units=32, ode_poisson=False, ode_classif=False, ode_linear_classif=False, ode_z0_encoder='odernn', ode_obsrv_std=0.01, ode_n_traj_samples=1, TTF_module='TTF_RecAvg', MMF_module='MMF_GR_Add', llm_model_fusion='GPT2', llm_layers_fusion=6, max_length=1024, d_txt=768, recency_sigma=1.0, n_heads_fusion=1, kappa=0.5, epoch=20, patience=3, early_stop_delta=0.0001, lr=0.001, w_decay=0.01, batch_size=16, dropout=0.1, use_amp=False, logmode='a', save='experiments/', load=None, device=device(type='cuda'), PID=17089, C=10, enc_in=10, c_out=10, input_len=2, pred_len=136)
Epoch 0, Loss: 0.98228: 100% 3/3 [00:03<00:00,  1.18s/it]
100% 1/1 [00:00<00:00, 29.58it/s]
100% 2/2 [00:00<00:00, 40.57it/s]
- Epoch 000, ExpID 56598
Train - Loss (one batch): 0.98228
Val - Loss, MSE, MAE: 1.04603, 1.04603, 0.77882
Test - Best epoch, Loss, MSE, MAE: 0, 0.96194, 0.96194, 0.78166
Time spent: 3.63s
Epoch 1, Loss: 1.09940: 100% 3/3 [00:00<00:00,  5.91it/s]
100% 1/1 [00:00<00:00, 34.27it/s]
100% 2/2 [00:00<00:00, 45.64it/s]
- Epoch 001, ExpID 56598
Train - Loss (one batch): 1.09940
Val - Loss, MSE, MAE: 1.04206, 1.04206, 0.78052
Test - Best epoch, Loss, MSE, MAE: 1, 0.95934, 0.95934, 0.78469
Time spent: 0.58s
Epoch 2, Loss: 1.09436: 100% 3/3 [00:00<00:00,  6.04it/s]
100% 1/1 [00:00<00:00, 34.59it/s]
100% 2/2 [00:00<00:00, 45.90it/s]
- Epoch 002, ExpID 56598
Train - Loss (one batch): 1.09436
Val - Loss, MSE, MAE: 1.04135, 1.04135, 0.78250
Test - Best epoch, Loss, MSE, MAE: 2, 0.95949, 0.95949, 0.78762
Time spent: 0.57s
Epoch 3, Loss: 0.99339: 100% 3/3 [00:00<00:00,  6.31it/s]
100% 1/1 [00:00<00:00, 33.58it/s]
100% 2/2 [00:00<00:00, 48.33it/s]
- Epoch 003, ExpID 56598
Train - Loss (one batch): 0.99339
Val - Loss, MSE, MAE: 1.04120, 1.04120, 0.78191
Test - Best epoch, Loss, MSE, MAE: 3, 0.95917, 0.95917, 0.78668
Time spent: 0.55s
Epoch 4, Loss: 1.00720: 100% 3/3 [00:00<00:00,  6.21it/s]
100% 1/1 [00:00<00:00, 35.48it/s]
- Epoch 004, ExpID 56598
Train - Loss (one batch): 1.00720
Val - Loss, MSE, MAE: 1.04123, 1.04123, 0.78135
Test - Best epoch, Loss, MSE, MAE: 3, 0.95917, 0.95917, 0.78668
Time spent: 0.51s
Epoch 5, Loss: 1.13842: 100% 3/3 [00:00<00:00,  6.12it/s]
100% 1/1 [00:00<00:00, 35.43it/s]
- Epoch 005, ExpID 56598
Train - Loss (one batch): 1.13842
Val - Loss, MSE, MAE: 1.04117, 1.04117, 0.78102
Test - Best epoch, Loss, MSE, MAE: 3, 0.95917, 0.95917, 0.78668
Time spent: 0.52s
Epoch 6, Loss: 1.16248: 100% 3/3 [00:00<00:00,  6.29it/s]
100% 1/1 [00:00<00:00, 35.14it/s]
- Epoch 006, ExpID 56598
Train - Loss (one batch): 1.16248
Val - Loss, MSE, MAE: 1.04110, 1.04110, 0.78121
Test - Best epoch, Loss, MSE, MAE: 3, 0.95917, 0.95917, 0.78668
Time spent: 0.51s
Exp has been early stopped!
loss: 0.9591716527938843
mse: 0.9591716527938843
mae: 0.7866839170455933
rmse: 0.9793730974197388
mape: -0.16803021728992462
### Done ###

In [ ]:
#clustertrace unimodal
!python main.py \
  --dataset ClusterTrace \
  --model tPatchGNN \
  --split_method instance \
  -b 32 \
  --epoch 20 \
  --seed 42

PID, device: 18475 cuda
Using dataset path: /content/drive/MyDrive/IMM-TSF/data/ClusterTrace
Record 1c6afd5c227e89b8a29589f4: 1 chunks created, 0 dropped (0.00%)
Record 35fc40d2844c0b899c1ceb1e: 1 chunks created, 0 dropped (0.00%)
Record 7077ec572d50395cafcbcb7d: 1 chunks created, 0 dropped (0.00%)
+-------------------------------------+-----------------------------------------+
|                Metric               |                  Value                  |
+-------------------------------------+-----------------------------------------+
|             num_entities            |                    3                    |
|             num_features            |                    11                   |
|        num_unique_timestamps        |                  12615                  |
|           num_observations          |                  69001                  |
|  Feat observability entropy (norm)  |                  0.893                  |
| Temporal observation entropy (norm) |                  0.9753                 |
|               Mean IOI              |               0.0126 days               |
|               timespan              | 2000-01-12 02:06:22~2000-03-15 15:54:32 |
|               num_text              |                   688                   |
|     Text temporal entropy (norm)    |                  0.9971                 |
+-------------------------------------+-----------------------------------------+
After chunking & splitting (instance): train=1, val=1, test=1
Using Patch Collate Fn: patch_size=24, npatch=1, patch_stride=24
Scanning train split (1 batches)...
Scanning val split (1 batches)...
Scanning test split (1 batches)...
/content/drive/MyDrive/IMM-TSF/main.py
2026-04-02 00:39:52
main.py --dataset ClusterTrace --model tPatchGNN --split_method instance -b 32 --epoch 20 --seed 42
Namespace(overwrite_args=False, state='def', seed=42, gpu='0', dataset='ClusterTrace', data_root='./data', n=100000000, split_method='instance', enable_text=False, use_text_embeddings=False, time_unit='days', history=24, pred_window=24, stride=24, patch_size=24, npatch=1, patch_stride=24, model='tPatchGNN', outlayer='Linear', hid_dim=64, te_dim=10, node_dim=10, hop=1, tf_layer=1, nlayer=1, top_k=5, e_layers=2, d_layers=1, d_ff=2048, d_model=512, n_heads=2, num_kernels=6, embed='timeF', freq='h', moving_avg=25, factor=1, activation='gelu', distil=True, down_sampling_layers=3, down_sampling_window=2, down_sampling_method='avg', decomp_method='moving_avg', channel_independence=1, use_norm=1, n_vars=7, mode='mix_channel', AP_levels=3, use_decoder=True, d_mode='common_channel', d_d_model=64, ts_vocab_size=1000, domain_des='The Electricity Transformer Temperature (ETT) is a crucial indicator in the electric power long-term deployment.', input_token_len=576, output_token_len=96, llm_model_timellm='GPT2', llm_layers_timellm=6, nf_latents=20, nf_rec_dims=40, nf_gru_units=32, nf_hidden_layers=3, nf_hidden_dim=32, nf_flow_model='coupling', nf_flow_layers=2, nf_time_net='TimeLinear', nf_time_hidden_dim=8, nf_solver='dopri5', nf_solver_step=0.05, nf_atol=0.0001, nf_rtol=0.001, nf_odenet='concat', nf_activation='Tanh', nf_final_activation='Identity', nf_obsrv_std=0.01, nf_weight_decay=0.0001, nf_quantization=0.0, nf_max_t=5.0, nf_mixing=0.0001, nf_gob_prep_hidden=10, nf_gob_cov_hidden=50, nf_gob_p_hidden=25, nf_invertible=1, nf_components=8, nf_decoder_type='continuous', nf_rnn='gru', nf_marks=0, nf_density_model='independent', nf_extrap=0, cru_lsd=64, cru_hidden_units=64, cru_enc_num_layers=1, cru_dec_num_layers=1, cru_num_layers=1, cru_dropout_type='None', cru_dropout_rate=0.0, cru_use_gate_hidden_states=True, cru_use_ode_for_gru=False, cru_use_decay_gravity_gate=True, cru_use_gravity_gate=True, cru_use_decay_input_gate=True, cru_use_input_gate=True, cru_use_skip_connection=True, cru_solver='euler', ts=0.3, grad_clip=False, ode_latents=20, ode_units=32, ode_gen_layers=1, ode_rec_dims=32, ode_rec_layers=1, ode_gru_units=32, ode_poisson=False, ode_classif=False, ode_linear_classif=False, ode_z0_encoder='odernn', ode_obsrv_std=0.01, ode_n_traj_samples=1, TTF_module='TTF_T2V_XAttn', MMF_module='MMF_XAttn_Add', llm_model_fusion='GPT2', llm_layers_fusion=6, max_length=1024, d_txt=768, recency_sigma=1.0, n_heads_fusion=1, kappa=0.5, epoch=20, patience=3, early_stop_delta=0.0001, lr=0.001, w_decay=0.01, batch_size=32, dropout=0.1, use_amp=False, logmode='a', save='experiments/', load=None, device=device(type='cuda'), PID=18475, C=11, enc_in=11, c_out=11, input_len=1, pred_len=1798)
Epoch 0, Loss: 0.91492: 100% 1/1 [00:00<00:00,  1.95it/s]
100% 1/1 [00:00<00:00, 44.67it/s]
100% 1/1 [00:00<00:00, 52.67it/s]
- Epoch 000, ExpID 95956
Train - Loss (one batch): 0.91492
Val - Loss, MSE, MAE: 0.78798, 0.78798, 0.73071
Test - Best epoch, Loss, MSE, MAE: 0, 0.86748, 0.86748, 0.75799
Time spent: 0.56s
Epoch 1, Loss: 0.86485: 100% 1/1 [00:00<00:00,  9.31it/s]
100% 1/1 [00:00<00:00, 61.32it/s]
- Epoch 001, ExpID 95956
Train - Loss (one batch): 0.86485
Val - Loss, MSE, MAE: 0.80643, 0.80643, 0.73491
Test - Best epoch, Loss, MSE, MAE: 0, 0.86748, 0.86748, 0.75799
Time spent: 0.13s
Epoch 2, Loss: 0.82694: 100% 1/1 [00:00<00:00,  9.09it/s]
100% 1/1 [00:00<00:00, 59.87it/s]
- Epoch 002, ExpID 95956
Train - Loss (one batch): 0.82694
Val - Loss, MSE, MAE: 0.83364, 0.83364, 0.73885
Test - Best epoch, Loss, MSE, MAE: 0, 0.86748, 0.86748, 0.75799
Time spent: 0.13s
Epoch 3, Loss: 0.80044: 100% 1/1 [00:00<00:00,  9.14it/s]
100% 1/1 [00:00<00:00, 59.75it/s]
- Epoch 003, ExpID 95956
Train - Loss (one batch): 0.80044
Val - Loss, MSE, MAE: 0.86739, 0.86739, 0.74234
Test - Best epoch, Loss, MSE, MAE: 0, 0.86748, 0.86748, 0.75799
Time spent: 0.13s
Exp has been early stopped!
loss: 0.8674755692481995
mse: 0.8674755692481995
mae: 0.7579861283302307
rmse: 0.9313836693763733
mape: 1.4599765539169312
### Done ###

In [ ]:
from pathlib import Path
import shutil
import re

path = Path("/content/drive/MyDrive/IMM-TSF/compute_text_embeddings.py")
backup = Path("/content/drive/MyDrive/IMM-TSF/compute_text_embeddings_backup_before_clustertrace.py")

if path.exists() and not backup.exists():
    shutil.copy(path, backup)
    print("Backup created:", backup)

text = path.read_text(encoding="utf-8")

# Make processed path absolute
text = text.replace(
    'base_dir = f"data/{data_name}/processed"',
    r'base_dir = rf"/content/drive/MyDrive/IMM-TSF/data/{data_name}/processed"'
)

# Force ClusterTrace only
text = re.sub(
    r"data_name_list\s*=\s*\[[^\]]*\]",
    'data_name_list = ["ClusterTrace"]',
    text,
    flags=re.DOTALL
)

# Force GPT2 layer setting to match main.py expectation
text = re.sub(
    r"llm_layers_fusion\s*=\s*None",
    "llm_layers_fusion = 6",
    text
)

path.write_text(text, encoding="utf-8")
print("Patched compute_text_embeddings.py for ClusterTrace only.")

Backup created: /content/drive/MyDrive/IMM-TSF/compute_text_embeddings_backup_before_clustertrace.py
Patched compute_text_embeddings.py for ClusterTrace only.

In [ ]:
%cd /content/drive/MyDrive/IMM-TSF
!python compute_text_embeddings.py

/content/drive/MyDrive/IMM-TSF
### LLM model: GPT2 ###
### Processing dataset: ClusterTrace ###
Detected 1 GPUs. Using model parallelism.
Loaded GPT2 with 6 layers for fusion.
[1/3] Processing record: 1c6afd5c227e89b8a29589f4
Embedding notes for record '1c6afd5c227e89b8a29589f4'...
Wrote embeddings to /content/drive/MyDrive/IMM-TSF/data/ClusterTrace/processed/1c6afd5c227e89b8a29589f4/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
[2/3] Processing record: 35fc40d2844c0b899c1ceb1e
Embedding notes for record '35fc40d2844c0b899c1ceb1e'...
Wrote embeddings to /content/drive/MyDrive/IMM-TSF/data/ClusterTrace/processed/35fc40d2844c0b899c1ceb1e/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
[3/3] Processing record: 7077ec572d50395cafcbcb7d
Embedding notes for record '7077ec572d50395cafcbcb7d'...
Wrote embeddings to /content/drive/MyDrive/IMM-TSF/data/ClusterTrace/processed/7077ec572d50395cafcbcb7d/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt

In [ ]:
from pathlib import Path

base = Path("/content/drive/MyDrive/IMM-TSF/data/ClusterTrace/processed")
pts = list(base.rglob("text_embeddings_model=GPT2_layers=6_maxlen=1024.pt"))

print("Number of ClusterTrace embedding files found:", len(pts))
for p in pts[:10]:
    print(p)

Number of ClusterTrace embedding files found: 3
/content/drive/MyDrive/IMM-TSF/data/ClusterTrace/processed/1c6afd5c227e89b8a29589f4/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
/content/drive/MyDrive/IMM-TSF/data/ClusterTrace/processed/35fc40d2844c0b899c1ceb1e/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
/content/drive/MyDrive/IMM-TSF/data/ClusterTrace/processed/7077ec572d50395cafcbcb7d/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt

In [ ]:
%cd /content/drive/MyDrive/IMM-TSF
#unimodal clusterface
!mkdir -p run_logs/clustertrace_colab

!python main.py \
  --dataset ClusterTrace \
  --model tPatchGNN \
  --split_method instance \
  -b 32 \
  --epoch 20 \
  --seed 42 \
  2>&1 | tee run_logs/clustertrace_colab/clustertrace_unimodal_seed42.log

/content/drive/MyDrive/IMM-TSF
/content/drive/MyDrive/IMM-TSF/main.py
2026-04-02 00:43:01
main.py --dataset ClusterTrace --model tPatchGNN --split_method instance -b 32 --epoch 20 --seed 42
Namespace(overwrite_args=False, state='def', seed=42, gpu='0', dataset='ClusterTrace', data_root='./data', n=100000000, split_method='instance', enable_text=False, use_text_embeddings=False, time_unit='days', history=24, pred_window=24, stride=24, patch_size=24, npatch=1, patch_stride=24, model='tPatchGNN', outlayer='Linear', hid_dim=64, te_dim=10, node_dim=10, hop=1, tf_layer=1, nlayer=1, top_k=5, e_layers=2, d_layers=1, d_ff=2048, d_model=512, n_heads=2, num_kernels=6, embed='timeF', freq='h', moving_avg=25, factor=1, activation='gelu', distil=True, down_sampling_layers=3, down_sampling_window=2, down_sampling_method='avg', decomp_method='moving_avg', channel_independence=1, use_norm=1, n_vars=7, mode='mix_channel', AP_levels=3, use_decoder=True, d_mode='common_channel', d_d_model=64, ts_vocab_size=1000, domain_des='The Electricity Transformer Temperature (ETT) is a crucial indicator in the electric power long-term deployment.', input_token_len=576, output_token_len=96, llm_model_timellm='GPT2', llm_layers_timellm=6, nf_latents=20, nf_rec_dims=40, nf_gru_units=32, nf_hidden_layers=3, nf_hidden_dim=32, nf_flow_model='coupling', nf_flow_layers=2, nf_time_net='TimeLinear', nf_time_hidden_dim=8, nf_solver='dopri5', nf_solver_step=0.05, nf_atol=0.0001, nf_rtol=0.001, nf_odenet='concat', nf_activation='Tanh', nf_final_activation='Identity', nf_obsrv_std=0.01, nf_weight_decay=0.0001, nf_quantization=0.0, nf_max_t=5.0, nf_mixing=0.0001, nf_gob_prep_hidden=10, nf_gob_cov_hidden=50, nf_gob_p_hidden=25, nf_invertible=1, nf_components=8, nf_decoder_type='continuous', nf_rnn='gru', nf_marks=0, nf_density_model='independent', nf_extrap=0, cru_lsd=64, cru_hidden_units=64, cru_enc_num_layers=1, cru_dec_num_layers=1, cru_num_layers=1, cru_dropout_type='None', cru_dropout_rate=0.0, cru_use_gate_hidden_states=True, cru_use_ode_for_gru=False, cru_use_decay_gravity_gate=True, cru_use_gravity_gate=True, cru_use_decay_input_gate=True, cru_use_input_gate=True, cru_use_skip_connection=True, cru_solver='euler', ts=0.3, grad_clip=False, ode_latents=20, ode_units=32, ode_gen_layers=1, ode_rec_dims=32, ode_rec_layers=1, ode_gru_units=32, ode_poisson=False, ode_classif=False, ode_linear_classif=False, ode_z0_encoder='odernn', ode_obsrv_std=0.01, ode_n_traj_samples=1, TTF_module='TTF_T2V_XAttn', MMF_module='MMF_XAttn_Add', llm_model_fusion='GPT2', llm_layers_fusion=6, max_length=1024, d_txt=768, recency_sigma=1.0, n_heads_fusion=1, kappa=0.5, epoch=20, patience=3, early_stop_delta=0.0001, lr=0.001, w_decay=0.01, batch_size=32, dropout=0.1, use_amp=False, logmode='a', save='experiments/', load=None, device=device(type='cuda'), PID=19412, C=11, enc_in=11, c_out=11, input_len=1, pred_len=1798)
PID, device: 19412 cuda
Using dataset path: /content/drive/MyDrive/IMM-TSF/data/ClusterTrace
Record 1c6afd5c227e89b8a29589f4: 1 chunks created, 0 dropped (0.00%)
Record 35fc40d2844c0b899c1ceb1e: 1 chunks created, 0 dropped (0.00%)
Record 7077ec572d50395cafcbcb7d: 1 chunks created, 0 dropped (0.00%)
+-------------------------------------+-----------------------------------------+
|                Metric               |                  Value                  |
+-------------------------------------+-----------------------------------------+
|             num_entities            |                    3                    |
|             num_features            |                    11                   |
|        num_unique_timestamps        |                  12615                  |
|           num_observations          |                  69001                  |
|  Feat observability entropy (norm)  |                  0.893                  |
| Temporal observation entropy (norm) |                  0.9753                 |
|               Mean IOI              |               0.0126 days               |
|               timespan              | 2000-01-12 02:06:22~2000-03-15 15:54:32 |
|               num_text              |                   688                   |
|     Text temporal entropy (norm)    |                  0.9971                 |
+-------------------------------------+-----------------------------------------+
After chunking & splitting (instance): train=1, val=1, test=1
Using Patch Collate Fn: patch_size=24, npatch=1, patch_stride=24
Scanning train split (1 batches)...
Scanning val split (1 batches)...
Scanning test split (1 batches)...
Epoch 0, Loss: 0.91491: 100%|██████████| 1/1 [00:00<00:00,  1.77it/s]
100%|██████████| 1/1 [00:00<00:00, 45.53it/s]
100%|██████████| 1/1 [00:00<00:00, 50.29it/s]
- Epoch 000, ExpID 77201
Train - Loss (one batch): 0.91491
Val - Loss, MSE, MAE: 0.78801, 0.78801, 0.73072
Test - Best epoch, Loss, MSE, MAE: 0, 0.86748, 0.86748, 0.75800
Time spent: 0.61s
Epoch 1, Loss: 0.86481: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
100%|██████████| 1/1 [00:00<00:00, 56.83it/s]
- Epoch 001, ExpID 77201
Train - Loss (one batch): 0.86481
Val - Loss, MSE, MAE: 0.80639, 0.80639, 0.73490
Test - Best epoch, Loss, MSE, MAE: 0, 0.86748, 0.86748, 0.75800
Time spent: 0.18s
Epoch 2, Loss: 0.82702: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
100%|██████████| 1/1 [00:00<00:00, 59.23it/s]
- Epoch 002, ExpID 77201
Train - Loss (one batch): 0.82702
Val - Loss, MSE, MAE: 0.83350, 0.83350, 0.73884
Test - Best epoch, Loss, MSE, MAE: 0, 0.86748, 0.86748, 0.75800
Time spent: 0.17s
Epoch 3, Loss: 0.80051: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
100%|██████████| 1/1 [00:00<00:00, 59.03it/s]
- Epoch 003, ExpID 77201
Train - Loss (one batch): 0.80051
Val - Loss, MSE, MAE: 0.86703, 0.86703, 0.74231
Test - Best epoch, Loss, MSE, MAE: 0, 0.86748, 0.86748, 0.75800
Time spent: 0.13s
Exp has been early stopped!
loss: 0.8674821853637695
mse: 0.8674821853637695
mae: 0.7580004334449768
rmse: 0.9313872456550598
mape: 1.4615200757980347
### Done ###

In [ ]:
#clustertrace multimodal
%cd /content/drive/MyDrive/IMM-TSF

!python main.py \
  --dataset ClusterTrace \
  --model tPatchGNN \
  --TTF_module TTF_RecAvg \
  --MMF_module MMF_GR_Add \
  --llm_model_fusion GPT2 \
  --use_text_embeddings \
  --enable_text \
  --split_method instance \
  -b 32 \
  --epoch 20 \
  --seed 42 \
  2>&1 | tee run_logs/clustertrace_colab/clustertrace_multimodal_seed42.log

/content/drive/MyDrive/IMM-TSF
/content/drive/MyDrive/IMM-TSF/main.py
2026-04-02 00:43:33
main.py --dataset ClusterTrace --model tPatchGNN --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion GPT2 --use_text_embeddings --enable_text --split_method instance -b 32 --epoch 20 --seed 42
Namespace(overwrite_args=False, state='def', seed=42, gpu='0', dataset='ClusterTrace', data_root='./data', n=100000000, split_method='instance', enable_text=True, use_text_embeddings=True, time_unit='days', history=24, pred_window=24, stride=24, patch_size=24, npatch=1, patch_stride=24, model='tPatchGNN', outlayer='Linear', hid_dim=64, te_dim=10, node_dim=10, hop=1, tf_layer=1, nlayer=1, top_k=5, e_layers=2, d_layers=1, d_ff=2048, d_model=512, n_heads=2, num_kernels=6, embed='timeF', freq='h', moving_avg=25, factor=1, activation='gelu', distil=True, down_sampling_layers=3, down_sampling_window=2, down_sampling_method='avg', decomp_method='moving_avg', channel_independence=1, use_norm=1, n_vars=7, mode='mix_channel', AP_levels=3, use_decoder=True, d_mode='common_channel', d_d_model=64, ts_vocab_size=1000, domain_des='The Electricity Transformer Temperature (ETT) is a crucial indicator in the electric power long-term deployment.', input_token_len=576, output_token_len=96, llm_model_timellm='GPT2', llm_layers_timellm=6, nf_latents=20, nf_rec_dims=40, nf_gru_units=32, nf_hidden_layers=3, nf_hidden_dim=32, nf_flow_model='coupling', nf_flow_layers=2, nf_time_net='TimeLinear', nf_time_hidden_dim=8, nf_solver='dopri5', nf_solver_step=0.05, nf_atol=0.0001, nf_rtol=0.001, nf_odenet='concat', nf_activation='Tanh', nf_final_activation='Identity', nf_obsrv_std=0.01, nf_weight_decay=0.0001, nf_quantization=0.0, nf_max_t=5.0, nf_mixing=0.0001, nf_gob_prep_hidden=10, nf_gob_cov_hidden=50, nf_gob_p_hidden=25, nf_invertible=1, nf_components=8, nf_decoder_type='continuous', nf_rnn='gru', nf_marks=0, nf_density_model='independent', nf_extrap=0, cru_lsd=64, cru_hidden_units=64, cru_enc_num_layers=1, cru_dec_num_layers=1, cru_num_layers=1, cru_dropout_type='None', cru_dropout_rate=0.0, cru_use_gate_hidden_states=True, cru_use_ode_for_gru=False, cru_use_decay_gravity_gate=True, cru_use_gravity_gate=True, cru_use_decay_input_gate=True, cru_use_input_gate=True, cru_use_skip_connection=True, cru_solver='euler', ts=0.3, grad_clip=False, ode_latents=20, ode_units=32, ode_gen_layers=1, ode_rec_dims=32, ode_rec_layers=1, ode_gru_units=32, ode_poisson=False, ode_classif=False, ode_linear_classif=False, ode_z0_encoder='odernn', ode_obsrv_std=0.01, ode_n_traj_samples=1, TTF_module='TTF_RecAvg', MMF_module='MMF_GR_Add', llm_model_fusion='GPT2', llm_layers_fusion=6, max_length=1024, d_txt=768, recency_sigma=1.0, n_heads_fusion=1, kappa=0.5, epoch=20, patience=3, early_stop_delta=0.0001, lr=0.001, w_decay=0.01, batch_size=32, dropout=0.1, use_amp=False, logmode='a', save='experiments/', load=None, device=device(type='cuda'), PID=19586, C=11, enc_in=11, c_out=11, input_len=1, pred_len=1798)
PID, device: 19586 cuda
Using dataset path: /content/drive/MyDrive/IMM-TSF/data/ClusterTrace
Record 1c6afd5c227e89b8a29589f4: 1 chunks created, 0 dropped (0.00%)
Record 35fc40d2844c0b899c1ceb1e: 1 chunks created, 0 dropped (0.00%)
Record 7077ec572d50395cafcbcb7d: 1 chunks created, 0 dropped (0.00%)
+-------------------------------------+-----------------------------------------+
|                Metric               |                  Value                  |
+-------------------------------------+-----------------------------------------+
|             num_entities            |                    3                    |
|             num_features            |                    11                   |
|        num_unique_timestamps        |                  12615                  |
|           num_observations          |                  69001                  |
|  Feat observability entropy (norm)  |                  0.893                  |
| Temporal observation entropy (norm) |                  0.9753                 |
|               Mean IOI              |               0.0126 days               |
|               timespan              | 2000-01-12 02:06:22~2000-03-15 15:54:32 |
|               num_text              |                   688                   |
|     Text temporal entropy (norm)    |                  0.9971                 |
+-------------------------------------+-----------------------------------------+
After chunking & splitting (instance): train=1, val=1, test=1
Using Patch Collate Fn: patch_size=24, npatch=1, patch_stride=24
Scanning train split (1 batches)...
Scanning val split (1 batches)...
Scanning test split (1 batches)...
Using TTF module: TTF_RecAvg
Using MMF module: MMF_GR_Add
Epoch 0, Loss: 1.11208: 100%|██████████| 1/1 [00:00<00:00,  1.48it/s]
100%|██████████| 1/1 [00:00<00:00, 41.37it/s]
100%|██████████| 1/1 [00:00<00:00, 40.86it/s]
- Epoch 000, ExpID 41483
Train - Loss (one batch): 1.11208
Val - Loss, MSE, MAE: 0.78700, 0.78700, 0.72479
Test - Best epoch, Loss, MSE, MAE: 0, 0.84856, 0.84856, 0.74686
Time spent: 0.73s
Epoch 1, Loss: 0.85289: 100%|██████████| 1/1 [00:00<00:00,  4.88it/s]
100%|██████████| 1/1 [00:00<00:00, 45.19it/s]
- Epoch 001, ExpID 41483
Train - Loss (one batch): 0.85289
Val - Loss, MSE, MAE: 0.80045, 0.80045, 0.73378
Test - Best epoch, Loss, MSE, MAE: 0, 0.84856, 0.84856, 0.74686
Time spent: 0.23s
Epoch 2, Loss: 0.88613: 100%|██████████| 1/1 [00:00<00:00,  5.01it/s]
100%|██████████| 1/1 [00:00<00:00, 46.70it/s]
- Epoch 002, ExpID 41483
Train - Loss (one batch): 0.88613
Val - Loss, MSE, MAE: 0.82014, 0.82014, 0.73709
Test - Best epoch, Loss, MSE, MAE: 0, 0.84856, 0.84856, 0.74686
Time spent: 0.22s
Epoch 3, Loss: 0.78398: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
100%|██████████| 1/1 [00:00<00:00, 47.26it/s]
- Epoch 003, ExpID 41483
Train - Loss (one batch): 0.78398
Val - Loss, MSE, MAE: 0.84710, 0.84710, 0.74045
Test - Best epoch, Loss, MSE, MAE: 0, 0.84856, 0.84856, 0.74686
Time spent: 0.18s
Exp has been early stopped!
loss: 0.8485605120658875
mse: 0.8485605120658875
mae: 0.7468571662902832
rmse: 0.9211734533309937
mape: 1.2384979724884033
### Done ###

In [ ]:
#GDELT tPatchGNN Multimodal

!python main.py \
  --dataset GDELT \
  --model tPatchGNN \
  --TTF_module TTF_RecAvg \
  --MMF_module MMF_GR_Add \
  --llm_model_fusion GPT2 \
  --use_text_embeddings \
  -b 32 \
  --epoch 20 \
  --seed 42

PID, device: 43890 cuda
Using dataset path: /content/drive/MyDrive/IMM-TSF/data/GDELT
Record AUS_AGR: 59 chunks created, 1 dropped (1.67%)
Record AUS_LAB: 59 chunks created, 0 dropped (0.00%)
Record CAN_AGR: 59 chunks created, 0 dropped (0.00%)
Record CAN_LAB: 59 chunks created, 0 dropped (0.00%)
Record GBR_AGR: 59 chunks created, 0 dropped (0.00%)
Record GBR_LAB: 59 chunks created, 0 dropped (0.00%)
Record USA_AGR: 59 chunks created, 0 dropped (0.00%)
Record USA_LAB: 59 chunks created, 0 dropped (0.00%)
+-------------------------------------+-----------------------------------------+
|                Metric               |                  Value                  |
+-------------------------------------+-----------------------------------------+
|             num_entities            |                    8                    |
|             num_features            |                    5                    |
|        num_unique_timestamps        |                  34317                  |
|           num_observations          |                  193205                 |
|  Feat observability entropy (norm)  |                   1.0                   |
| Temporal observation entropy (norm) |                  0.9964                 |
|               Mean IOI              |               0.3015 days               |
|               timespan              | 2021-01-01 03:15:00~2024-12-31 23:00:00 |
|               num_text              |                  14357                  |
|     Text temporal entropy (norm)    |                  0.9896                 |
+-------------------------------------+-----------------------------------------+
After chunking & splitting (sample): train=279, val=96, test=96
Using Patch Collate Fn: patch_size=24, npatch=1, patch_stride=24
Scanning train split (9 batches)...
Scanning val split (3 batches)...
Scanning test split (3 batches)...
/content/drive/MyDrive/IMM-TSF/main.py
2026-04-01 19:50:33
main.py --dataset GDELT --model tPatchGNN --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion GPT2 --use_text_embeddings -b 32 --epoch 20 --seed 42
Namespace(overwrite_args=False, state='def', seed=42, gpu='0', dataset='GDELT', data_root='./data', n=100000000, split_method='sample', enable_text=False, use_text_embeddings=True, time_unit='days', history=24, pred_window=24, stride=24, patch_size=24, npatch=1, patch_stride=24, model='tPatchGNN', outlayer='Linear', hid_dim=64, te_dim=10, node_dim=10, hop=1, tf_layer=1, nlayer=1, top_k=5, e_layers=2, d_layers=1, d_ff=2048, d_model=512, n_heads=2, num_kernels=6, embed='timeF', freq='h', moving_avg=25, factor=1, activation='gelu', distil=True, down_sampling_layers=3, down_sampling_window=2, down_sampling_method='avg', decomp_method='moving_avg', channel_independence=1, use_norm=1, n_vars=7, mode='mix_channel', AP_levels=3, use_decoder=True, d_mode='common_channel', d_d_model=64, ts_vocab_size=1000, domain_des='The Electricity Transformer Temperature (ETT) is a crucial indicator in the electric power long-term deployment.', input_token_len=576, output_token_len=96, llm_model_timellm='GPT2', llm_layers_timellm=6, nf_latents=20, nf_rec_dims=40, nf_gru_units=32, nf_hidden_layers=3, nf_hidden_dim=32, nf_flow_model='coupling', nf_flow_layers=2, nf_time_net='TimeLinear', nf_time_hidden_dim=8, nf_solver='dopri5', nf_solver_step=0.05, nf_atol=0.0001, nf_rtol=0.001, nf_odenet='concat', nf_activation='Tanh', nf_final_activation='Identity', nf_obsrv_std=0.01, nf_weight_decay=0.0001, nf_quantization=0.0, nf_max_t=5.0, nf_mixing=0.0001, nf_gob_prep_hidden=10, nf_gob_cov_hidden=50, nf_gob_p_hidden=25, nf_invertible=1, nf_components=8, nf_decoder_type='continuous', nf_rnn='gru', nf_marks=0, nf_density_model='independent', nf_extrap=0, cru_lsd=64, cru_hidden_units=64, cru_enc_num_layers=1, cru_dec_num_layers=1, cru_num_layers=1, cru_dropout_type='None', cru_dropout_rate=0.0, cru_use_gate_hidden_states=True, cru_use_ode_for_gru=False, cru_use_decay_gravity_gate=True, cru_use_gravity_gate=True, cru_use_decay_input_gate=True, cru_use_input_gate=True, cru_use_skip_connection=True, cru_solver='euler', ts=0.3, grad_clip=False, ode_latents=20, ode_units=32, ode_gen_layers=1, ode_rec_dims=32, ode_rec_layers=1, ode_gru_units=32, ode_poisson=False, ode_classif=False, ode_linear_classif=False, ode_z0_encoder='odernn', ode_obsrv_std=0.01, ode_n_traj_samples=1, TTF_module='TTF_RecAvg', MMF_module='MMF_GR_Add', llm_model_fusion='GPT2', llm_layers_fusion=6, max_length=1024, d_txt=768, recency_sigma=1.0, n_heads_fusion=1, kappa=0.5, epoch=20, patience=3, early_stop_delta=0.0001, lr=0.001, w_decay=0.01, batch_size=32, dropout=0.1, use_amp=False, logmode='a', save='experiments/', load=None, device=device(type='cuda'), PID=43890, C=5, enc_in=5, c_out=5, input_len=1, pred_len=419)
Epoch 0, Loss: 0.96058: 100% 9/9 [00:01<00:00,  4.92it/s]
100% 3/3 [00:00<00:00, 36.28it/s]
100% 3/3 [00:00<00:00, 39.53it/s]
- Epoch 000, ExpID 15967
Train - Loss (one batch): 0.96058
Val - Loss, MSE, MAE: 0.97412, 0.97412, 0.67923
Test - Best epoch, Loss, MSE, MAE: 0, 1.04033, 1.04033, 0.69163
Time spent: 1.99s
Epoch 1, Loss: 0.92944: 100% 9/9 [00:01<00:00,  6.53it/s]
100% 3/3 [00:00<00:00, 39.18it/s]
- Epoch 001, ExpID 15967
Train - Loss (one batch): 0.92944
Val - Loss, MSE, MAE: 0.97466, 0.97466, 0.67644
Test - Best epoch, Loss, MSE, MAE: 0, 1.04033, 1.04033, 0.69163
Time spent: 1.46s
Epoch 2, Loss: 0.96145: 100% 9/9 [00:01<00:00,  6.58it/s]
100% 3/3 [00:00<00:00, 38.77it/s]
- Epoch 002, ExpID 15967
Train - Loss (one batch): 0.96145
Val - Loss, MSE, MAE: 0.97447, 0.97447, 0.67772
Test - Best epoch, Loss, MSE, MAE: 0, 1.04033, 1.04033, 0.69163
Time spent: 1.45s
Epoch 3, Loss: 0.84280: 100% 9/9 [00:01<00:00,  7.00it/s]
100% 3/3 [00:00<00:00, 39.89it/s]
- Epoch 003, ExpID 15967
Train - Loss (one batch): 0.84280
Val - Loss, MSE, MAE: 0.97432, 0.97432, 0.67863
Test - Best epoch, Loss, MSE, MAE: 0, 1.04033, 1.04033, 0.69163
Time spent: 1.36s
Exp has been early stopped!
loss: 1.0403320789337158
mse: 1.0403320789337158
mae: 0.6916261911392212
rmse: 1.019966721534729
mape: -0.23829138278961182
### Done ###

In [ ]:
#GDELT tPatchGNN Unimodal

!python main.py \
  --dataset GDELT \
  --model tPatchGNN \
  --TTF_module TTF_RecAvg \
  --MMF_module MMF_GR_Add \
  --llm_model_fusion GPT2 \
  -b 32 \
  --epoch 20 \
  --seed 42

PID, device: 44163 cuda
Using dataset path: /content/drive/MyDrive/IMM-TSF/data/GDELT
Record AUS_AGR: 59 chunks created, 1 dropped (1.67%)
Record AUS_LAB: 59 chunks created, 0 dropped (0.00%)
Record CAN_AGR: 59 chunks created, 0 dropped (0.00%)
Record CAN_LAB: 59 chunks created, 0 dropped (0.00%)
Record GBR_AGR: 59 chunks created, 0 dropped (0.00%)
Record GBR_LAB: 59 chunks created, 0 dropped (0.00%)
Record USA_AGR: 59 chunks created, 0 dropped (0.00%)
Record USA_LAB: 59 chunks created, 0 dropped (0.00%)
+-------------------------------------+-----------------------------------------+
|                Metric               |                  Value                  |
+-------------------------------------+-----------------------------------------+
|             num_entities            |                    8                    |
|             num_features            |                    5                    |
|        num_unique_timestamps        |                  34317                  |
|           num_observations          |                  193205                 |
|  Feat observability entropy (norm)  |                   1.0                   |
| Temporal observation entropy (norm) |                  0.9964                 |
|               Mean IOI              |               0.3015 days               |
|               timespan              | 2021-01-01 03:15:00~2024-12-31 23:00:00 |
|               num_text              |                  14357                  |
|     Text temporal entropy (norm)    |                  0.9896                 |
+-------------------------------------+-----------------------------------------+
After chunking & splitting (sample): train=279, val=96, test=96
Using Patch Collate Fn: patch_size=24, npatch=1, patch_stride=24
Scanning train split (9 batches)...
Scanning val split (3 batches)...
Scanning test split (3 batches)...
/content/drive/MyDrive/IMM-TSF/main.py
2026-04-01 19:51:18
main.py --dataset GDELT --model tPatchGNN --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion GPT2 -b 32 --epoch 20 --seed 42
Namespace(overwrite_args=False, state='def', seed=42, gpu='0', dataset='GDELT', data_root='./data', n=100000000, split_method='sample', enable_text=False, use_text_embeddings=False, time_unit='days', history=24, pred_window=24, stride=24, patch_size=24, npatch=1, patch_stride=24, model='tPatchGNN', outlayer='Linear', hid_dim=64, te_dim=10, node_dim=10, hop=1, tf_layer=1, nlayer=1, top_k=5, e_layers=2, d_layers=1, d_ff=2048, d_model=512, n_heads=2, num_kernels=6, embed='timeF', freq='h', moving_avg=25, factor=1, activation='gelu', distil=True, down_sampling_layers=3, down_sampling_window=2, down_sampling_method='avg', decomp_method='moving_avg', channel_independence=1, use_norm=1, n_vars=7, mode='mix_channel', AP_levels=3, use_decoder=True, d_mode='common_channel', d_d_model=64, ts_vocab_size=1000, domain_des='The Electricity Transformer Temperature (ETT) is a crucial indicator in the electric power long-term deployment.', input_token_len=576, output_token_len=96, llm_model_timellm='GPT2', llm_layers_timellm=6, nf_latents=20, nf_rec_dims=40, nf_gru_units=32, nf_hidden_layers=3, nf_hidden_dim=32, nf_flow_model='coupling', nf_flow_layers=2, nf_time_net='TimeLinear', nf_time_hidden_dim=8, nf_solver='dopri5', nf_solver_step=0.05, nf_atol=0.0001, nf_rtol=0.001, nf_odenet='concat', nf_activation='Tanh', nf_final_activation='Identity', nf_obsrv_std=0.01, nf_weight_decay=0.0001, nf_quantization=0.0, nf_max_t=5.0, nf_mixing=0.0001, nf_gob_prep_hidden=10, nf_gob_cov_hidden=50, nf_gob_p_hidden=25, nf_invertible=1, nf_components=8, nf_decoder_type='continuous', nf_rnn='gru', nf_marks=0, nf_density_model='independent', nf_extrap=0, cru_lsd=64, cru_hidden_units=64, cru_enc_num_layers=1, cru_dec_num_layers=1, cru_num_layers=1, cru_dropout_type='None', cru_dropout_rate=0.0, cru_use_gate_hidden_states=True, cru_use_ode_for_gru=False, cru_use_decay_gravity_gate=True, cru_use_gravity_gate=True, cru_use_decay_input_gate=True, cru_use_input_gate=True, cru_use_skip_connection=True, cru_solver='euler', ts=0.3, grad_clip=False, ode_latents=20, ode_units=32, ode_gen_layers=1, ode_rec_dims=32, ode_rec_layers=1, ode_gru_units=32, ode_poisson=False, ode_classif=False, ode_linear_classif=False, ode_z0_encoder='odernn', ode_obsrv_std=0.01, ode_n_traj_samples=1, TTF_module='TTF_RecAvg', MMF_module='MMF_GR_Add', llm_model_fusion='GPT2', llm_layers_fusion=6, max_length=1024, d_txt=768, recency_sigma=1.0, n_heads_fusion=1, kappa=0.5, epoch=20, patience=3, early_stop_delta=0.0001, lr=0.001, w_decay=0.01, batch_size=32, dropout=0.1, use_amp=False, logmode='a', save='experiments/', load=None, device=device(type='cuda'), PID=44163, C=5, enc_in=5, c_out=5, input_len=1, pred_len=419)
Epoch 0, Loss: 0.96058: 100% 9/9 [00:01<00:00,  4.69it/s]
100% 3/3 [00:00<00:00, 35.21it/s]
100% 3/3 [00:00<00:00, 39.03it/s]
- Epoch 000, ExpID 92141
Train - Loss (one batch): 0.96058
Val - Loss, MSE, MAE: 0.97412, 0.97412, 0.67923
Test - Best epoch, Loss, MSE, MAE: 0, 1.04033, 1.04033, 0.69163
Time spent: 2.08s
Epoch 1, Loss: 0.92944: 100% 9/9 [00:01<00:00,  6.73it/s]
100% 3/3 [00:00<00:00, 40.42it/s]
- Epoch 001, ExpID 92141
Train - Loss (one batch): 0.92944
Val - Loss, MSE, MAE: 0.97466, 0.97466, 0.67644
Test - Best epoch, Loss, MSE, MAE: 0, 1.04033, 1.04033, 0.69163
Time spent: 1.41s
Epoch 2, Loss: 0.96145: 100% 9/9 [00:01<00:00,  7.03it/s]
100% 3/3 [00:00<00:00, 41.78it/s]
- Epoch 002, ExpID 92141
Train - Loss (one batch): 0.96145
Val - Loss, MSE, MAE: 0.97447, 0.97447, 0.67772
Test - Best epoch, Loss, MSE, MAE: 0, 1.04033, 1.04033, 0.69163
Time spent: 1.35s
Epoch 3, Loss: 0.84280: 100% 9/9 [00:01<00:00,  6.39it/s]
100% 3/3 [00:00<00:00, 40.13it/s]
- Epoch 003, ExpID 92141
Train - Loss (one batch): 0.84280
Val - Loss, MSE, MAE: 0.97432, 0.97432, 0.67863
Test - Best epoch, Loss, MSE, MAE: 0, 1.04033, 1.04033, 0.69163
Time spent: 1.49s
Exp has been early stopped!
loss: 1.0403320789337158
mse: 1.0403320789337158
mae: 0.6916261911392212
rmse: 1.019966721534729
mape: -0.23829138278961182
### Done ###

In [ ]:
# FNPSID tPatchGNN Multimodal

!python main.py \
  --dataset FNSPID \
  --model tPatchGNN \
  --TTF_module TTF_RecAvg \
  --MMF_module MMF_GR_Add \
  --llm_model_fusion GPT2 \
  --use_text_embeddings \
  -b 32 \
  --epoch 20 \
  --seed 42

PID, device: 44284 cuda
Using dataset path: /content/drive/MyDrive/IMM-TSF/data/FNSPID
Record AMAT: 207 chunks created, 7 dropped (3.27%)
Record AMT: 212 chunks created, 22 dropped (9.40%)
Record DVN: 214 chunks created, 6 dropped (2.73%)
Record EA: 181 chunks created, 0 dropped (0.00%)
Record EXPE: 206 chunks created, 5 dropped (2.37%)
Record KO: 214 chunks created, 2 dropped (0.93%)
Record PEP: 213 chunks created, 6 dropped (2.74%)
Record TXN: 212 chunks created, 5 dropped (2.30%)
Record USO: 219 chunks created, 9 dropped (3.95%)
Record XLF: 219 chunks created, 2 dropped (0.90%)
+-------------------------------------+-----------------------------------------+
|                Metric               |                  Value                  |
+-------------------------------------+-----------------------------------------+
|             num_entities            |                    10                   |
|             num_features            |                    6                    |
|        num_unique_timestamps        |                   3659                  |
|           num_observations          |                  209688                 |
|  Feat observability entropy (norm)  |                   1.0                   |
| Temporal observation entropy (norm) |                  0.9969                 |
|               Mean IOI              |               1.4507 days               |
|               timespan              | 2009-06-08 00:00:00~2023-12-15 00:00:00 |
|               num_text              |                  20826                  |
|     Text temporal entropy (norm)    |                  0.9488                 |
+-------------------------------------+-----------------------------------------+
After chunking & splitting (sample): train=1217, val=405, test=411
Using Patch Collate Fn: patch_size=24, npatch=1, patch_stride=24
Scanning train split (39 batches)...
Scanning val split (13 batches)...
Scanning test split (13 batches)...
/content/drive/MyDrive/IMM-TSF/main.py
2026-04-01 19:51:40
main.py --dataset FNSPID --model tPatchGNN --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion GPT2 --use_text_embeddings -b 32 --epoch 20 --seed 42
Namespace(overwrite_args=False, state='def', seed=42, gpu='0', dataset='FNSPID', data_root='./data', n=100000000, split_method='sample', enable_text=False, use_text_embeddings=True, time_unit='days', history=24, pred_window=24, stride=24, patch_size=24, npatch=1, patch_stride=24, model='tPatchGNN', outlayer='Linear', hid_dim=64, te_dim=10, node_dim=10, hop=1, tf_layer=1, nlayer=1, top_k=5, e_layers=2, d_layers=1, d_ff=2048, d_model=512, n_heads=2, num_kernels=6, embed='timeF', freq='h', moving_avg=25, factor=1, activation='gelu', distil=True, down_sampling_layers=3, down_sampling_window=2, down_sampling_method='avg', decomp_method='moving_avg', channel_independence=1, use_norm=1, n_vars=7, mode='mix_channel', AP_levels=3, use_decoder=True, d_mode='common_channel', d_d_model=64, ts_vocab_size=1000, domain_des='The Electricity Transformer Temperature (ETT) is a crucial indicator in the electric power long-term deployment.', input_token_len=576, output_token_len=96, llm_model_timellm='GPT2', llm_layers_timellm=6, nf_latents=20, nf_rec_dims=40, nf_gru_units=32, nf_hidden_layers=3, nf_hidden_dim=32, nf_flow_model='coupling', nf_flow_layers=2, nf_time_net='TimeLinear', nf_time_hidden_dim=8, nf_solver='dopri5', nf_solver_step=0.05, nf_atol=0.0001, nf_rtol=0.001, nf_odenet='concat', nf_activation='Tanh', nf_final_activation='Identity', nf_obsrv_std=0.01, nf_weight_decay=0.0001, nf_quantization=0.0, nf_max_t=5.0, nf_mixing=0.0001, nf_gob_prep_hidden=10, nf_gob_cov_hidden=50, nf_gob_p_hidden=25, nf_invertible=1, nf_components=8, nf_decoder_type='continuous', nf_rnn='gru', nf_marks=0, nf_density_model='independent', nf_extrap=0, cru_lsd=64, cru_hidden_units=64, cru_enc_num_layers=1, cru_dec_num_layers=1, cru_num_layers=1, cru_dropout_type='None', cru_dropout_rate=0.0, cru_use_gate_hidden_states=True, cru_use_ode_for_gru=False, cru_use_decay_gravity_gate=True, cru_use_gravity_gate=True, cru_use_decay_input_gate=True, cru_use_input_gate=True, cru_use_skip_connection=True, cru_solver='euler', ts=0.3, grad_clip=False, ode_latents=20, ode_units=32, ode_gen_layers=1, ode_rec_dims=32, ode_rec_layers=1, ode_gru_units=32, ode_poisson=False, ode_classif=False, ode_linear_classif=False, ode_z0_encoder='odernn', ode_obsrv_std=0.01, ode_n_traj_samples=1, TTF_module='TTF_RecAvg', MMF_module='MMF_GR_Add', llm_model_fusion='GPT2', llm_layers_fusion=6, max_length=1024, d_txt=768, recency_sigma=1.0, n_heads_fusion=1, kappa=0.5, epoch=20, patience=3, early_stop_delta=0.0001, lr=0.001, w_decay=0.01, batch_size=32, dropout=0.1, use_amp=False, logmode='a', save='experiments/', load=None, device=device(type='cuda'), PID=44284, C=6, enc_in=6, c_out=6, input_len=1, pred_len=18)
Epoch 0, Loss: 0.03576: 100% 39/39 [00:05<00:00,  7.72it/s]
100% 13/13 [00:00<00:00, 51.86it/s]
100% 13/13 [00:00<00:00, 49.94it/s]
- Epoch 000, ExpID 42781
Train - Loss (one batch): 0.03576
Val - Loss, MSE, MAE: 0.24142, 0.24142, 0.25090
Test - Best epoch, Loss, MSE, MAE: 0, 0.24507, 0.24507, 0.36719
Time spent: 5.56s
Epoch 1, Loss: 0.02024: 100% 39/39 [00:04<00:00,  8.77it/s]
100% 13/13 [00:00<00:00, 57.43it/s]
100% 13/13 [00:00<00:00, 54.38it/s]
- Epoch 001, ExpID 42781
Train - Loss (one batch): 0.02024
Val - Loss, MSE, MAE: 0.21306, 0.21306, 0.22822
Test - Best epoch, Loss, MSE, MAE: 1, 0.19086, 0.19086, 0.30975
Time spent: 4.92s
Epoch 2, Loss: 0.04524: 100% 39/39 [00:04<00:00,  7.99it/s]
100% 13/13 [00:00<00:00, 56.51it/s]
- Epoch 002, ExpID 42781
Train - Loss (one batch): 0.04524
Val - Loss, MSE, MAE: 0.21621, 0.21621, 0.24035
Test - Best epoch, Loss, MSE, MAE: 1, 0.19086, 0.19086, 0.30975
Time spent: 5.11s
Epoch 3, Loss: 1.51752: 100% 39/39 [00:04<00:00,  8.20it/s]
100% 13/13 [00:00<00:00, 57.31it/s]
100% 13/13 [00:00<00:00, 55.85it/s]
- Epoch 003, ExpID 42781
Train - Loss (one batch): 1.51752
Val - Loss, MSE, MAE: 0.20620, 0.20620, 0.21253
Test - Best epoch, Loss, MSE, MAE: 3, 0.19110, 0.19110, 0.30642
Time spent: 5.22s
Epoch 4, Loss: 0.22466: 100% 39/39 [00:04<00:00,  8.76it/s]
100% 13/13 [00:00<00:00, 57.62it/s]
- Epoch 004, ExpID 42781
Train - Loss (one batch): 0.22466
Val - Loss, MSE, MAE: 0.21953, 0.21953, 0.24868
Test - Best epoch, Loss, MSE, MAE: 3, 0.19110, 0.19110, 0.30642
Time spent: 4.68s
Epoch 5, Loss: 0.09941: 100% 39/39 [00:04<00:00,  8.06it/s]
100% 13/13 [00:00<00:00, 51.69it/s]
- Epoch 005, ExpID 42781
Train - Loss (one batch): 0.09941
Val - Loss, MSE, MAE: 0.21669, 0.21669, 0.24498
Test - Best epoch, Loss, MSE, MAE: 3, 0.19110, 0.19110, 0.30642
Time spent: 5.09s
Epoch 6, Loss: 0.03494: 100% 39/39 [00:04<00:00,  8.37it/s]
100% 13/13 [00:00<00:00, 56.74it/s]
100% 13/13 [00:00<00:00, 56.60it/s]
- Epoch 006, ExpID 42781
Train - Loss (one batch): 0.03494
Val - Loss, MSE, MAE: 0.20111, 0.20111, 0.20755
Test - Best epoch, Loss, MSE, MAE: 6, 0.15802, 0.15802, 0.26763
Time spent: 5.12s
Epoch 7, Loss: 0.00936: 100% 39/39 [00:04<00:00,  8.84it/s]
100% 13/13 [00:00<00:00, 56.79it/s]
- Epoch 007, ExpID 42781
Train - Loss (one batch): 0.00936
Val - Loss, MSE, MAE: 0.20703, 0.20703, 0.22598
Test - Best epoch, Loss, MSE, MAE: 6, 0.15802, 0.15802, 0.26763
Time spent: 4.64s
Epoch 8, Loss: 0.10650: 100% 39/39 [00:04<00:00,  8.39it/s]
100% 13/13 [00:00<00:00, 57.79it/s]
- Epoch 008, ExpID 42781
Train - Loss (one batch): 0.10650
Val - Loss, MSE, MAE: 0.20386, 0.20386, 0.21905
Test - Best epoch, Loss, MSE, MAE: 6, 0.15802, 0.15802, 0.26763
Time spent: 4.87s
Epoch 9, Loss: 0.09620: 100% 39/39 [00:04<00:00,  8.81it/s]
100% 13/13 [00:00<00:00, 56.76it/s]
- Epoch 009, ExpID 42781
Train - Loss (one batch): 0.09620
Val - Loss, MSE, MAE: 0.21794, 0.21794, 0.24955
Test - Best epoch, Loss, MSE, MAE: 6, 0.15802, 0.15802, 0.26763
Time spent: 4.66s
Exp has been early stopped!
loss: 0.1580183058977127
mse: 0.1580183058977127
mae: 0.2676266133785248
rmse: 0.3975151777267456
mape: 0.22602885961532593
### Done ###

In [ ]:
#FNSPID tPatchGNN unimodal

!python main.py \
  --dataset FNSPID \
  --model tPatchGNN \
  --TTF_module TTF_RecAvg \
  --MMF_module MMF_GR_Add \
  --llm_model_fusion GPT2 \
  -b 32 \
  --epoch 20 \
  --seed 42

PID, device: 44629 cuda
Using dataset path: /content/drive/MyDrive/IMM-TSF/data/FNSPID
Record AMAT: 207 chunks created, 7 dropped (3.27%)
Record AMT: 212 chunks created, 22 dropped (9.40%)
Record DVN: 214 chunks created, 6 dropped (2.73%)
Record EA: 181 chunks created, 0 dropped (0.00%)
Record EXPE: 206 chunks created, 5 dropped (2.37%)
Record KO: 214 chunks created, 2 dropped (0.93%)
Record PEP: 213 chunks created, 6 dropped (2.74%)
Record TXN: 212 chunks created, 5 dropped (2.30%)
Record USO: 219 chunks created, 9 dropped (3.95%)
Record XLF: 219 chunks created, 2 dropped (0.90%)
+-------------------------------------+-----------------------------------------+
|                Metric               |                  Value                  |
+-------------------------------------+-----------------------------------------+
|             num_entities            |                    10                   |
|             num_features            |                    6                    |
|        num_unique_timestamps        |                   3659                  |
|           num_observations          |                  209688                 |
|  Feat observability entropy (norm)  |                   1.0                   |
| Temporal observation entropy (norm) |                  0.9969                 |
|               Mean IOI              |               1.4507 days               |
|               timespan              | 2009-06-08 00:00:00~2023-12-15 00:00:00 |
|               num_text              |                  20826                  |
|     Text temporal entropy (norm)    |                  0.9488                 |
+-------------------------------------+-----------------------------------------+
After chunking & splitting (sample): train=1217, val=405, test=411
Using Patch Collate Fn: patch_size=24, npatch=1, patch_stride=24
Scanning train split (39 batches)...
Scanning val split (13 batches)...
Scanning test split (13 batches)...
/content/drive/MyDrive/IMM-TSF/main.py
2026-04-01 19:52:50
main.py --dataset FNSPID --model tPatchGNN --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion GPT2 -b 32 --epoch 20 --seed 42
Namespace(overwrite_args=False, state='def', seed=42, gpu='0', dataset='FNSPID', data_root='./data', n=100000000, split_method='sample', enable_text=False, use_text_embeddings=False, time_unit='days', history=24, pred_window=24, stride=24, patch_size=24, npatch=1, patch_stride=24, model='tPatchGNN', outlayer='Linear', hid_dim=64, te_dim=10, node_dim=10, hop=1, tf_layer=1, nlayer=1, top_k=5, e_layers=2, d_layers=1, d_ff=2048, d_model=512, n_heads=2, num_kernels=6, embed='timeF', freq='h', moving_avg=25, factor=1, activation='gelu', distil=True, down_sampling_layers=3, down_sampling_window=2, down_sampling_method='avg', decomp_method='moving_avg', channel_independence=1, use_norm=1, n_vars=7, mode='mix_channel', AP_levels=3, use_decoder=True, d_mode='common_channel', d_d_model=64, ts_vocab_size=1000, domain_des='The Electricity Transformer Temperature (ETT) is a crucial indicator in the electric power long-term deployment.', input_token_len=576, output_token_len=96, llm_model_timellm='GPT2', llm_layers_timellm=6, nf_latents=20, nf_rec_dims=40, nf_gru_units=32, nf_hidden_layers=3, nf_hidden_dim=32, nf_flow_model='coupling', nf_flow_layers=2, nf_time_net='TimeLinear', nf_time_hidden_dim=8, nf_solver='dopri5', nf_solver_step=0.05, nf_atol=0.0001, nf_rtol=0.001, nf_odenet='concat', nf_activation='Tanh', nf_final_activation='Identity', nf_obsrv_std=0.01, nf_weight_decay=0.0001, nf_quantization=0.0, nf_max_t=5.0, nf_mixing=0.0001, nf_gob_prep_hidden=10, nf_gob_cov_hidden=50, nf_gob_p_hidden=25, nf_invertible=1, nf_components=8, nf_decoder_type='continuous', nf_rnn='gru', nf_marks=0, nf_density_model='independent', nf_extrap=0, cru_lsd=64, cru_hidden_units=64, cru_enc_num_layers=1, cru_dec_num_layers=1, cru_num_layers=1, cru_dropout_type='None', cru_dropout_rate=0.0, cru_use_gate_hidden_states=True, cru_use_ode_for_gru=False, cru_use_decay_gravity_gate=True, cru_use_gravity_gate=True, cru_use_decay_input_gate=True, cru_use_input_gate=True, cru_use_skip_connection=True, cru_solver='euler', ts=0.3, grad_clip=False, ode_latents=20, ode_units=32, ode_gen_layers=1, ode_rec_dims=32, ode_rec_layers=1, ode_gru_units=32, ode_poisson=False, ode_classif=False, ode_linear_classif=False, ode_z0_encoder='odernn', ode_obsrv_std=0.01, ode_n_traj_samples=1, TTF_module='TTF_RecAvg', MMF_module='MMF_GR_Add', llm_model_fusion='GPT2', llm_layers_fusion=6, max_length=1024, d_txt=768, recency_sigma=1.0, n_heads_fusion=1, kappa=0.5, epoch=20, patience=3, early_stop_delta=0.0001, lr=0.001, w_decay=0.01, batch_size=32, dropout=0.1, use_amp=False, logmode='a', save='experiments/', load=None, device=device(type='cuda'), PID=44629, C=6, enc_in=6, c_out=6, input_len=1, pred_len=18)
Epoch 0, Loss: 0.03576: 100% 39/39 [00:04<00:00,  7.90it/s]
100% 13/13 [00:00<00:00, 57.27it/s]
100% 13/13 [00:00<00:00, 56.28it/s]
- Epoch 000, ExpID 85690
Train - Loss (one batch): 0.03576
Val - Loss, MSE, MAE: 0.24142, 0.24142, 0.25090
Test - Best epoch, Loss, MSE, MAE: 0, 0.24507, 0.24507, 0.36719
Time spent: 5.40s
Epoch 1, Loss: 0.02024: 100% 39/39 [00:04<00:00,  8.33it/s]
100% 13/13 [00:00<00:00, 53.90it/s]
100% 13/13 [00:00<00:00, 57.25it/s]
- Epoch 001, ExpID 85690
Train - Loss (one batch): 0.02024
Val - Loss, MSE, MAE: 0.21306, 0.21306, 0.22822
Test - Best epoch, Loss, MSE, MAE: 1, 0.19086, 0.19086, 0.30975
Time spent: 5.15s
Epoch 2, Loss: 0.04524: 100% 39/39 [00:04<00:00,  8.38it/s]
100% 13/13 [00:00<00:00, 57.34it/s]
- Epoch 002, ExpID 85690
Train - Loss (one batch): 0.04524
Val - Loss, MSE, MAE: 0.21621, 0.21621, 0.24035
Test - Best epoch, Loss, MSE, MAE: 1, 0.19086, 0.19086, 0.30975
Time spent: 4.88s
Epoch 3, Loss: 1.51752: 100% 39/39 [00:04<00:00,  9.01it/s]
100% 13/13 [00:00<00:00, 57.71it/s]
100% 13/13 [00:00<00:00, 56.67it/s]
- Epoch 003, ExpID 85690
Train - Loss (one batch): 1.51752
Val - Loss, MSE, MAE: 0.20620, 0.20620, 0.21253
Test - Best epoch, Loss, MSE, MAE: 3, 0.19110, 0.19110, 0.30642
Time spent: 4.79s
Epoch 4, Loss: 0.22466: 100% 39/39 [00:05<00:00,  7.67it/s]
100% 13/13 [00:00<00:00, 56.78it/s]
- Epoch 004, ExpID 85690
Train - Loss (one batch): 0.22466
Val - Loss, MSE, MAE: 0.21953, 0.21953, 0.24868
Test - Best epoch, Loss, MSE, MAE: 3, 0.19110, 0.19110, 0.30642
Time spent: 5.31s
Epoch 5, Loss: 0.09941: 100% 39/39 [00:04<00:00,  8.63it/s]
100% 13/13 [00:00<00:00, 58.15it/s]
- Epoch 005, ExpID 85690
Train - Loss (one batch): 0.09941
Val - Loss, MSE, MAE: 0.21669, 0.21669, 0.24498
Test - Best epoch, Loss, MSE, MAE: 3, 0.19110, 0.19110, 0.30642
Time spent: 4.74s
Epoch 6, Loss: 0.03494: 100% 39/39 [00:04<00:00,  8.51it/s]
100% 13/13 [00:00<00:00, 54.56it/s]
100% 13/13 [00:00<00:00, 56.51it/s]
- Epoch 006, ExpID 85690
Train - Loss (one batch): 0.03494
Val - Loss, MSE, MAE: 0.20111, 0.20111, 0.20755
Test - Best epoch, Loss, MSE, MAE: 6, 0.15802, 0.15802, 0.26763
Time spent: 5.05s
Epoch 7, Loss: 0.00936: 100% 39/39 [00:04<00:00,  8.29it/s]
100% 13/13 [00:00<00:00, 57.53it/s]
- Epoch 007, ExpID 85690
Train - Loss (one batch): 0.00936
Val - Loss, MSE, MAE: 0.20703, 0.20703, 0.22598
Test - Best epoch, Loss, MSE, MAE: 6, 0.15802, 0.15802, 0.26763
Time spent: 4.93s
Epoch 8, Loss: 0.10650: 100% 39/39 [00:04<00:00,  8.46it/s]
100% 13/13 [00:00<00:00, 56.23it/s]
- Epoch 008, ExpID 85690
Train - Loss (one batch): 0.10650
Val - Loss, MSE, MAE: 0.20386, 0.20386, 0.21905
Test - Best epoch, Loss, MSE, MAE: 6, 0.15802, 0.15802, 0.26763
Time spent: 4.84s
Epoch 9, Loss: 0.09620: 100% 39/39 [00:04<00:00,  8.23it/s]
100% 13/13 [00:00<00:00, 57.81it/s]
- Epoch 009, ExpID 85690
Train - Loss (one batch): 0.09620
Val - Loss, MSE, MAE: 0.21794, 0.21794, 0.24955
Test - Best epoch, Loss, MSE, MAE: 6, 0.15802, 0.15802, 0.26763
Time spent: 4.97s
Exp has been early stopped!
loss: 0.1580183058977127
mse: 0.1580183058977127
mae: 0.2676266133785248
rmse: 0.3975151777267456
mape: 0.22602885961532593
### Done ###

Full paper methods reproduction and MIMIC classification extension pipeline below

In [ ]:
!python time_imm_repro_and_readmission_fixed.py plan_repro --out_csv /content/repro_plan.csv

python3: can't open file '/content/drive/MyDrive/IMM-TSF/time_imm_repro_and_readmission_fixed.py': [Errno 2] No such file or directory

In [ ]:
from __future__ import annotations

"""
TIME-IMM / IMM-TSF reproduction and MIMIC ICU readmission extension.

Colab-safe fixed version.

What this script does
---------------------
1. Reproduction runner for the official IMM-TSF forecasting benchmarks.
2. Experiment-grid generator for TSF backbones and both TTF/MMF fusion modules.
3. Log parser + comparison table builder.
4. A classification extension that adapts the IMM-TSF ideas from forecasting to
   binary ICU readmission prediction on MIMIC.
5. Safe execution in:
   - terminal / CLI
   - Google Colab
   - Jupyter notebook

Most important fix
------------------
The original script used argparse with required subcommands, which crashes inside
Colab/Jupyter because notebook kernel arguments are injected into sys.argv.
This version supports:
    main(["plan_repro", "--out_csv", "repro_plan.csv"])
and also:
    !python time_imm_repro_and_readmission_fixed.py plan_repro --out_csv repro_plan.csv
"""

import argparse
import ast
from dataclasses import dataclass, field
import json
import math
import random
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd

try:
    import torch
    import torch.nn as nn
    from torch.utils.data import Dataset, DataLoader
except Exception:
    torch = None
    nn = None
    Dataset = object
    DataLoader = object


# -----------------------------------------------------------------------------
# Section 1. Paper-derived benchmark settings
# -----------------------------------------------------------------------------

PAPER_MODELS: List[str] = [
    "Informer",
    "DLinear",
    "PatchTST",
    "TimesNet",
    "TimeMixer",
    "TimeLLM",
    "TTM",
    "CRU",
    "LatentODE",
    "NeuralFlow",
    "tPatchGNN",
]

IRREGULAR_MODELS = {"CRU", "LatentODE", "NeuralFlow", "tPatchGNN"}
REGULAR_MODELS = {"Informer", "DLinear", "PatchTST", "TimesNet", "TimeMixer", "TimeLLM", "TTM"}
TTF_MODULES = ["TTF_RecAvg", "TTF_T2V_XAttn"]
MMF_MODULES = ["MMF_GR_Add", "MMF_XAttn_Add"]
TEXT_ENCODERS = ["GPT2", "BERT", "Llama", "DeepSeek"]

PAPER_DATASETS: List[str] = [
    "GDELT",
    "RepoHealth",
    "MIMIC",
    "FNSPID",
    "ClusterTrace",
    "StudentLife",
    "ILINet",
    "CESNET",
    "EPA-Air",
]

PAPER_DEFAULT_MODEL_ARGS: Dict[str, Dict[str, Any]] = {
    "Informer": {},
    "DLinear": {},
    "PatchTST": {"e_layers": 1, "d_layers": 1, "n_heads": 2},
    "TimesNet": {"e_layers": 2, "d_layers": 1, "top_k": 5, "d_model": 16, "d_ff": 32},
    "TimeMixer": {"e_layers": 2, "d_model": 16, "d_ff": 32, "down_sampling_layers": 3},
    "TimeLLM": {"llm_layers": 6, "input_token_len": 16, "output_token_len": 96, "d_model": 32, "d_ff": 128},
    "TTM": {"e_layers": 3, "d_layers": 2, "d_model": 1024, "decoder_d_model": 64},
    "CRU": {"latent_state": 32, "hidden_units": 32},
    "LatentODE": {"rec_hidden": 32, "ode_units": 32},
    "NeuralFlow": {"latent_dim": 20, "hidden_dim": 32, "gru_units": 32},
    "tPatchGNN": {"patch_size": 24, "nlayer": 1, "gnn_layer": 1, "te_dim": 10, "node_dim": 10, "d_hidden": 32},
}

PAPER_MIMIC_RESULTS = {
    "Informer": {"uni_mse": 0.8519, "multi_mse": 0.7988, "uni_mae": 0.5588, "multi_mae": 0.6083},
    "DLinear": {"uni_mse": 0.8770, "multi_mse": 0.8515, "uni_mae": 0.6152, "multi_mae": 0.6456},
    "PatchTST": {"uni_mse": 0.9394, "multi_mse": 0.9281, "uni_mae": 0.6794, "multi_mae": 0.6799},
    "TimesNet": {"uni_mse": 1.0374, "multi_mse": 0.9335, "uni_mae": 0.7348, "multi_mae": 0.6821},
    "TimeMixer": {"uni_mse": 0.8856, "multi_mse": 0.8179, "uni_mae": 0.5686, "multi_mae": 0.5821},
    "TimeLLM": {"uni_mse": 0.7901, "multi_mse": 0.7535, "uni_mae": 0.5457, "multi_mae": 0.5620},
    "TTM": {"uni_mse": 0.8620, "multi_mse": 0.9105, "uni_mae": 0.6283, "multi_mae": 0.6707},
    "CRU": {"uni_mse": 1.0122, "multi_mse": 0.9847, "uni_mae": 0.7235, "multi_mae": 0.7087},
    "LatentODE": {"uni_mse": 0.9325, "multi_mse": 0.9423, "uni_mae": 0.6868, "multi_mae": 0.6785},
    "NeuralFlow": {"uni_mse": 1.0086, "multi_mse": 0.9884, "uni_mae": 0.7219, "multi_mae": 0.7079},
    "tPatchGNN": {"uni_mse": 0.7250, "multi_mse": 0.7656, "uni_mae": 0.5479, "multi_mae": 0.5794},
}


# -----------------------------------------------------------------------------
# Section 2. Utilities
# -----------------------------------------------------------------------------

def set_seed(seed: int = 42) -> None:
    random.seed(seed)
    np.random.seed(seed)
    if torch is not None:
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def run_command(cmd: Sequence[str], cwd: Optional[Path] = None, log_file: Optional[Path] = None) -> int:
    cwd_str = str(cwd) if cwd else None
    print("RUN:", " ".join(map(str, cmd)))
    proc = subprocess.Popen(
        list(map(str, cmd)),
        cwd=cwd_str,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    assert proc.stdout is not None
    writer = open(log_file, "w", encoding="utf-8") if log_file else None
    try:
        for line in proc.stdout:
            print(line, end="")
            if writer:
                writer.write(line)
    finally:
        if writer:
            writer.close()
    return proc.wait()


def save_df(df: pd.DataFrame, path: Path) -> None:
    ensure_dir(path.parent)
    df.to_csv(path, index=False)
    print(f"[INFO] Saved {path}")


def _running_in_notebook() -> bool:
    try:
        from IPython import get_ipython
        return get_ipython() is not None
    except Exception:
        return False


# -----------------------------------------------------------------------------
# Section 3. Reproduction runner for the official IMM-TSF repo
# -----------------------------------------------------------------------------

@dataclass
class ReproRunConfig:
    dataset: str
    model: str
    multimodal: bool
    seed: int = 42
    batch_size: int = 8
    epochs: int = 20
    split_method: str = "instance"
    ttf_module: Optional[str] = None
    mmf_module: Optional[str] = None
    text_encoder: Optional[str] = None
    dataset_overrides: Dict[str, Any] = field(default_factory=dict)

    def run_name(self) -> str:
        pieces = [self.dataset, self.model, f"seed{self.seed}", "multi" if self.multimodal else "uni"]
        if self.multimodal:
            pieces.extend([self.ttf_module or "NA", self.mmf_module or "NA", self.text_encoder or "NA"])
        return "__".join(pieces)


@dataclass
class RepoPaths:
    repo_root: Path
    data_root: Path
    log_root: Path
    results_root: Path


class IMMTSFReproducer:
    def __init__(self, paths: RepoPaths):
        self.paths = paths
        ensure_dir(paths.log_root)
        ensure_dir(paths.results_root)

    def patch_evaluation_for_empty_splits(self) -> None:
        target_file = self.paths.repo_root / "lib" / "evaluation.py"
        if not target_file.exists():
            print(f"[WARN] {target_file} not found; skipping empty-split patch.")
            return

        backup = target_file.with_name("evaluation_backup_before_empty_split_patch.py")
        if not backup.exists():
            shutil.copy(target_file, backup)

        text = target_file.read_text(encoding="utf-8")
        target = "n_avai_var = torch.count_nonzero(n_eval_samples)"

        if "auto-patch for empty validation/test splits" in text:
            print("[INFO] evaluation.py already patched.")
            return

        replacement = '''# ---- auto-patch for empty validation/test splits ----
    if isinstance(n_eval_samples, int):
        if n_eval_samples == 0:
            return {
                "loss": float("nan"),
                "mse": float("nan"),
                "mae": float("nan"),
                "rmse": float("nan"),
                "mape": float("nan"),
            }
        n_eval_samples = torch.tensor(n_eval_samples)

    n_avai_var = torch.count_nonzero(n_eval_samples)

    if isinstance(n_avai_var, torch.Tensor) and n_avai_var.item() == 0:
        return {
            "loss": float("nan"),
            "mse": float("nan"),
            "mae": float("nan"),
            "rmse": float("nan"),
            "mape": float("nan"),
        }'''

        if target in text:
            text = text.replace(target, replacement)
            target_file.write_text(text, encoding="utf-8")
            print("[INFO] Patched evaluation.py for empty validation/test splits.")
        else:
            print("[WARN] Expected line not found in evaluation.py; patch not applied.")

    def build_main_command(self, cfg: ReproRunConfig) -> List[str]:
        cmd = [
            sys.executable,
            "main.py",
            "--dataset", cfg.dataset,
            "--model", cfg.model,
            "--split_method", cfg.split_method,
            "-b", str(cfg.batch_size),
            "--epoch", str(cfg.epochs),
            "--seed", str(cfg.seed),
        ]

        model_defaults = dict(PAPER_DEFAULT_MODEL_ARGS.get(cfg.model, {}))
        model_defaults.update(cfg.dataset_overrides)

        for k, v in model_defaults.items():
            cmd.extend([f"--{k}", str(v)])

        if cfg.multimodal:
            if cfg.ttf_module:
                cmd.extend(["--TTF_module", cfg.ttf_module])
            if cfg.mmf_module:
                cmd.extend(["--MMF_module", cfg.mmf_module])
            if cfg.text_encoder:
                cmd.extend(["--llm_model_fusion", cfg.text_encoder])
            cmd.extend(["--use_text_embeddings", "--enable_text"])

        return cmd

    def generate_experiment_grid(
        self,
        datasets: Sequence[str],
        models: Sequence[str],
        seeds: Sequence[int],
        include_unimodal: bool = True,
        include_multimodal: bool = True,
    ) -> List[ReproRunConfig]:
        grid: List[ReproRunConfig] = []
        for dataset in datasets:
            for model in models:
                for seed in seeds:
                    overrides = self.dataset_specific_overrides(dataset, model)

                    if include_unimodal:
                        grid.append(
                            ReproRunConfig(
                                dataset=dataset,
                                model=model,
                                multimodal=False,
                                seed=seed,
                                dataset_overrides=overrides,
                            )
                        )

                    if include_multimodal:
                        for ttf in TTF_MODULES:
                            for mmf in MMF_MODULES:
                                for enc in TEXT_ENCODERS:
                                    grid.append(
                                        ReproRunConfig(
                                            dataset=dataset,
                                            model=model,
                                            multimodal=True,
                                            seed=seed,
                                            ttf_module=ttf,
                                            mmf_module=mmf,
                                            text_encoder=enc,
                                            dataset_overrides=overrides,
                                        )
                                    )
        return grid

    def dataset_specific_overrides(self, dataset: str, model: str) -> Dict[str, Any]:
        if dataset == "CESNET" and model == "tPatchGNN":
            return {
                "history": 12,
                "pred_window": 6,
                "stride": 6,
                "patch_size": 6,
                "patch_stride": 6,
                "npatch": 2,
            }
        return {}

    def run_one(self, cfg: ReproRunConfig) -> int:
        log_file = self.paths.log_root / f"{cfg.run_name()}.log"
        cmd = self.build_main_command(cfg)
        return run_command(cmd, cwd=self.paths.repo_root, log_file=log_file)

    def parse_metrics_from_log(self, log_file: Path) -> Dict[str, Any]:
        text = log_file.read_text(encoding="utf-8", errors="ignore")
        out: Dict[str, Any] = {"log_file": str(log_file)}

        patterns = {
            "mse": [r"\bmse\b\s*[:=]\s*([0-9]*\.?[0-9]+)", r"\bMSE\b\s*[:=]\s*([0-9]*\.?[0-9]+)"],
            "mae": [r"\bmae\b\s*[:=]\s*([0-9]*\.?[0-9]+)", r"\bMAE\b\s*[:=]\s*([0-9]*\.?[0-9]+)"],
            "rmse": [r"\brmse\b\s*[:=]\s*([0-9]*\.?[0-9]+)", r"\bRMSE\b\s*[:=]\s*([0-9]*\.?[0-9]+)"],
            "mape": [r"\bmape\b\s*[:=]\s*([0-9]*\.?[0-9]+)", r"\bMAPE\b\s*[:=]\s*([0-9]*\.?[0-9]+)"],
            "val_loss": [r"val(?:idation)?\s*loss\s*[:=]\s*([0-9]*\.?[0-9]+)"],
        }

        for name, pats in patterns.items():
            vals = []
            for pat in pats:
                vals.extend(re.findall(pat, text, flags=re.IGNORECASE))
            if vals:
                out[name] = float(vals[-1])

        return out

    def collect_results(self) -> pd.DataFrame:
        rows = []
        for log_file in sorted(self.paths.log_root.glob("*.log")):
            metrics = self.parse_metrics_from_log(log_file)
            stem = log_file.stem.split("__")

            row = {
                "dataset": stem[0] if len(stem) > 0 else None,
                "model": stem[1] if len(stem) > 1 else None,
                "seed": stem[2] if len(stem) > 2 else None,
                "modality": stem[3] if len(stem) > 3 else None,
                "ttf_module": stem[4] if len(stem) > 4 else None,
                "mmf_module": stem[5] if len(stem) > 5 else None,
                "text_encoder": stem[6] if len(stem) > 6 else None,
            }
            row.update(metrics)
            rows.append(row)

        df = pd.DataFrame(rows)
        if not df.empty:
            sort_cols = [c for c in ["dataset", "model", "modality", "text_encoder", "ttf_module", "mmf_module", "seed"] if c in df.columns]
            df = df.sort_values(sort_cols)
        return df

    def build_mimic_comparison_table(self, results_df: pd.DataFrame) -> pd.DataFrame:
        if results_df.empty or "dataset" not in results_df.columns:
            return pd.DataFrame()

        mimic = results_df[results_df["dataset"] == "MIMIC"].copy()
        if mimic.empty:
            return pd.DataFrame()

        rows = []
        for model in sorted(mimic["model"].dropna().unique()):
            sub = mimic[mimic["model"] == model]
            uni = sub[sub["modality"] == "uni"]
            multi = sub[sub["modality"] == "multi"]

            best_uni_mse = uni["mse"].min() if (not uni.empty and "mse" in uni.columns) else np.nan
            best_multi_mse = multi["mse"].min() if (not multi.empty and "mse" in multi.columns) else np.nan
            best_uni_mae = uni["mae"].min() if (not uni.empty and "mae" in uni.columns) else np.nan
            best_multi_mae = multi["mae"].min() if (not multi.empty and "mae" in multi.columns) else np.nan

            paper = PAPER_MIMIC_RESULTS.get(model, {})
            rows.append({
                "model": model,
                "paper_uni_mse": paper.get("uni_mse"),
                "our_best_uni_mse": best_uni_mse,
                "paper_multi_mse": paper.get("multi_mse"),
                "our_best_multi_mse": best_multi_mse,
                "paper_uni_mae": paper.get("uni_mae"),
                "our_best_uni_mae": best_uni_mae,
                "paper_multi_mae": paper.get("multi_mae"),
                "our_best_multi_mae": best_multi_mae,
                "delta_multi_mse_vs_paper": best_multi_mse - paper.get("multi_mse", np.nan) if not np.isnan(best_multi_mse) else np.nan,
                "delta_uni_mse_vs_paper": best_uni_mse - paper.get("uni_mse", np.nan) if not np.isnan(best_uni_mse) else np.nan,
            })

        return pd.DataFrame(rows).sort_values("model")


# -----------------------------------------------------------------------------
# Section 4. Classification extension: forecasting -> ICU readmission
# -----------------------------------------------------------------------------

class ICUReadmissionWindowDataset(Dataset):
    def __init__(self, path: Path):
        self.path = path
        suffix = path.suffix.lower()

        if suffix == ".jsonl":
            self.records = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
        elif suffix == ".json":
            obj = json.loads(path.read_text(encoding="utf-8"))
            self.records = obj if isinstance(obj, list) else obj["records"]
        elif suffix == ".csv":
            df = pd.read_csv(path)
            self.records = [self._from_row(row) for _, row in df.iterrows()]
        elif suffix == ".parquet":
            df = pd.read_parquet(path)
            self.records = [self._from_row(row) for _, row in df.iterrows()]
        else:
            raise ValueError(f"Unsupported dataset suffix: {suffix}")

    def _from_row(self, row: pd.Series) -> Dict[str, Any]:
        def parse_obj(x: Any) -> Any:
            if isinstance(x, str):
                try:
                    return ast.literal_eval(x)
                except Exception:
                    return x
            return x
        return {k: parse_obj(v) for k, v in row.to_dict().items()}

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, idx: int) -> Dict[str, Any]:
        if torch is None:
            raise RuntimeError("PyTorch is required to load the classification dataset.")

        rec = self.records[idx]

        out = {
            "patient_id": rec["patient_id"],
            "label": int(rec["label"]),
            "ts_values": torch.tensor(rec["ts_values"], dtype=torch.float32),
            "ts_mask": torch.tensor(rec["ts_mask"], dtype=torch.float32),
            "ts_times": torch.tensor(rec["ts_times"], dtype=torch.float32),
            "text_embeddings": torch.tensor(rec["text_embeddings"], dtype=torch.float32),
            "text_times": torch.tensor(rec["text_times"], dtype=torch.float32),
        }

        static_features = rec.get("static_features", [])
        out["static_features"] = torch.tensor(static_features, dtype=torch.float32)
        out["note_density"] = torch.tensor(float(rec.get("note_density", 0.0)), dtype=torch.float32)
        out["missingness_rate"] = torch.tensor(float(rec.get("missingness_rate", 0.0)), dtype=torch.float32)
        out["alignment_score"] = torch.tensor(float(rec.get("alignment_score", 0.0)), dtype=torch.float32)
        return out


def collate_readmission(batch: List[Dict[str, Any]]) -> Dict[str, Any]:
    def pad_sequence_2d(tensors: List[torch.Tensor], pad_value: float = 0.0) -> Tuple[torch.Tensor, torch.Tensor]:
        lengths = torch.tensor([t.shape[0] for t in tensors], dtype=torch.long)
        max_len = int(lengths.max().item()) if len(lengths) else 0
        feat_dim = int(tensors[0].shape[1]) if tensors else 0

        out = torch.full((len(tensors), max_len, feat_dim), pad_value, dtype=torch.float32)
        mask = torch.zeros((len(tensors), max_len), dtype=torch.float32)

        for i, t in enumerate(tensors):
            if t.shape[0] > 0:
                out[i, : t.shape[0], :] = t
                mask[i, : t.shape[0]] = 1.0
        return out, mask

    def pad_sequence_1d(tensors: List[torch.Tensor], pad_value: float = 0.0) -> Tuple[torch.Tensor, torch.Tensor]:
        lengths = torch.tensor([t.shape[0] for t in tensors], dtype=torch.long)
        max_len = int(lengths.max().item()) if len(lengths) else 0

        out = torch.full((len(tensors), max_len), pad_value, dtype=torch.float32)
        mask = torch.zeros((len(tensors), max_len), dtype=torch.float32)

        for i, t in enumerate(tensors):
            if t.shape[0] > 0:
                out[i, : t.shape[0]] = t
                mask[i, : t.shape[0]] = 1.0
        return out, mask

    ts_values, ts_pad_mask = pad_sequence_2d([b["ts_values"] for b in batch])
    ts_obs_mask, _ = pad_sequence_2d([b["ts_mask"] for b in batch])
    ts_times, _ = pad_sequence_1d([b["ts_times"] for b in batch])

    text_embeddings, text_pad_mask = pad_sequence_2d([b["text_embeddings"] for b in batch])
    text_times, _ = pad_sequence_1d([b["text_times"] for b in batch])

    static_dim = max((b["static_features"].shape[0] for b in batch), default=0)
    static_features = torch.zeros((len(batch), static_dim), dtype=torch.float32)

    for i, b in enumerate(batch):
        n = b["static_features"].shape[0]
        if n > 0:
            static_features[i, :n] = b["static_features"]

    return {
        "patient_id": [b["patient_id"] for b in batch],
        "label": torch.tensor([b["label"] for b in batch], dtype=torch.float32),
        "ts_values": ts_values,
        "ts_obs_mask": ts_obs_mask,
        "ts_pad_mask": ts_pad_mask,
        "ts_times": ts_times,
        "text_embeddings": text_embeddings,
        "text_pad_mask": text_pad_mask,
        "text_times": text_times,
        "static_features": static_features,
        "note_density": torch.stack([b["note_density"] for b in batch]),
        "missingness_rate": torch.stack([b["missingness_rate"] for b in batch]),
        "alignment_score": torch.stack([b["alignment_score"] for b in batch]),
    }


class Time2Vec(nn.Module):
    def __init__(self, out_dim: int):
        super().__init__()
        self.out_dim = out_dim
        self.w0 = nn.Parameter(torch.randn(1))
        self.b0 = nn.Parameter(torch.randn(1))
        self.w = nn.Parameter(torch.randn(out_dim - 1))
        self.b = nn.Parameter(torch.randn(out_dim - 1))

    def forward(self, t: torch.Tensor) -> torch.Tensor:
        v0 = self.w0 * t + self.b0
        v1 = torch.sin(t.unsqueeze(-1) * self.w + self.b)
        return torch.cat([v0.unsqueeze(-1), v1], dim=-1)


class SimpleIrregularTSEncoder(nn.Module):
    def __init__(self, input_dim: int, hidden_dim: int = 128):
        super().__init__()
        self.time_mlp = nn.Sequential(
            nn.Linear(1, 16),
            nn.ReLU(),
            nn.Linear(16, 16),
        )
        self.value_mlp = nn.Sequential(
            nn.Linear(input_dim * 2 + 16, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
        )
        self.gru = nn.GRU(hidden_dim, hidden_dim, batch_first=True)

    def forward(
        self,
        ts_values: torch.Tensor,
        ts_obs_mask: torch.Tensor,
        ts_pad_mask: torch.Tensor,
        ts_times: torch.Tensor
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        time_feat = self.time_mlp(ts_times.unsqueeze(-1))
        x = torch.cat([ts_values, ts_obs_mask, time_feat], dim=-1)
        x = self.value_mlp(x)

        lengths = ts_pad_mask.sum(dim=1).long().cpu()
        lengths = torch.clamp(lengths, min=1)

        packed = nn.utils.rnn.pack_padded_sequence(
            x, lengths=lengths, batch_first=True, enforce_sorted=False
        )
        _, h = self.gru(packed)
        patient_repr = h[-1]
        return patient_repr, x


class RecAvgTTF(nn.Module):
    def __init__(self, sigma: float = 1.0):
        super().__init__()
        self.sigma = sigma

    def forward(
        self,
        text_embeddings: torch.Tensor,
        text_times: torch.Tensor,
        text_mask: torch.Tensor,
        query_time: torch.Tensor
    ) -> torch.Tensor:
        dt2 = (text_times - query_time.unsqueeze(1)) ** 2
        weights = torch.exp(-dt2 / (2 * self.sigma ** 2)) * text_mask
        denom = weights.sum(dim=1, keepdim=True).clamp_min(1e-8)
        weights = weights / denom
        return torch.einsum("bl,bld->bd", weights, text_embeddings)


class T2VXAttnTTF(nn.Module):
    def __init__(self, text_dim: int, hidden_dim: int):
        super().__init__()
        self.t2v = Time2Vec(out_dim=16)
        self.text_proj = nn.Linear(text_dim + 16, hidden_dim)
        self.query_proj = nn.Linear(hidden_dim, hidden_dim)
        self.attn = nn.MultiheadAttention(hidden_dim, num_heads=1, batch_first=True)

    def forward(
        self,
        text_embeddings: torch.Tensor,
        text_times: torch.Tensor,
        text_mask: torch.Tensor,
        query_repr: torch.Tensor
    ) -> torch.Tensor:
        time_feat = self.t2v(text_times)
        kvt = self.text_proj(torch.cat([text_embeddings, time_feat], dim=-1))
        q = self.query_proj(query_repr).unsqueeze(1)
        key_padding_mask = (text_mask == 0)
        out, _ = self.attn(q, kvt, kvt, key_padding_mask=key_padding_mask)
        return out.squeeze(1)


class GRAddFusion(nn.Module):
    def __init__(self, hidden_dim: int):
        super().__init__()
        self.seq_proj = nn.Linear(hidden_dim, hidden_dim * 2)
        self.gru = nn.GRU(hidden_dim * 2, hidden_dim, batch_first=True)
        self.resid = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
        )
        self.gate = nn.Sequential(
            nn.Linear(hidden_dim * 2, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.Sigmoid(),
        )

    def forward(self, ts_repr: torch.Tensor, text_repr: torch.Tensor) -> torch.Tensor:
        seq = torch.stack([ts_repr, text_repr], dim=1)
        seq = self.seq_proj(seq)
        _, h = self.gru(seq)
        residual = self.resid(h[-1])
        gate = self.gate(torch.cat([ts_repr, text_repr], dim=-1))
        return ts_repr + gate * residual


class XAttnAddFusion(nn.Module):
    def __init__(self, hidden_dim: int, kappa: float = 0.5):
        super().__init__()
        self.kappa = kappa
        self.attn = nn.MultiheadAttention(hidden_dim, num_heads=1, batch_first=True)

    def forward(self, ts_repr: torch.Tensor, text_repr: torch.Tensor) -> torch.Tensor:
        q = ts_repr.unsqueeze(1)
        kv = text_repr.unsqueeze(1)
        out, _ = self.attn(q, kv, kv)
        return ts_repr + self.kappa * out.squeeze(1)


class ReliabilityAwareGRAdd(nn.Module):
    def __init__(self, hidden_dim: int, reliability_dim: int = 4):
        super().__init__()
        self.seq_proj = nn.Linear(hidden_dim, hidden_dim * 2)
        self.gru = nn.GRU(hidden_dim * 2, hidden_dim, batch_first=True)
        self.resid = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
        )
        self.rel_mlp = nn.Sequential(
            nn.Linear(reliability_dim, hidden_dim // 2),
            nn.ReLU(),
        )
        self.gate = nn.Sequential(
            nn.Linear(hidden_dim * 2 + hidden_dim // 2, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.Sigmoid(),
        )

    def forward(self, ts_repr: torch.Tensor, text_repr: torch.Tensor, reliability_feats: torch.Tensor) -> torch.Tensor:
        seq = torch.stack([ts_repr, text_repr], dim=1)
        seq = self.seq_proj(seq)
        _, h = self.gru(seq)
        residual = self.resid(h[-1])
        rel = self.rel_mlp(reliability_feats)
        gate = self.gate(torch.cat([ts_repr, text_repr, rel], dim=-1))
        return ts_repr + gate * residual


class ReadmissionIMMClassifier(nn.Module):
    def __init__(
        self,
        ts_input_dim: int,
        text_dim: int,
        static_dim: int = 0,
        hidden_dim: int = 128,
        ttf_type: str = "recavg",
        mmf_type: str = "gradd",
    ):
        super().__init__()
        self.ttf_type = ttf_type.lower()
        self.mmf_type = mmf_type.lower()

        self.ts_encoder = SimpleIrregularTSEncoder(ts_input_dim, hidden_dim)
        self.text_proj = nn.Linear(text_dim, hidden_dim)
        self.static_proj = nn.Linear(static_dim, hidden_dim) if static_dim > 0 else None

        if self.ttf_type == "recavg":
            self.ttf = RecAvgTTF(sigma=1.0)
        elif self.ttf_type == "t2v_xattn":
            self.ttf = T2VXAttnTTF(text_dim=hidden_dim, hidden_dim=hidden_dim)
        else:
            raise ValueError(f"Unknown ttf_type: {ttf_type}")

        if self.mmf_type == "gradd":
            self.mmf = GRAddFusion(hidden_dim)
        elif self.mmf_type == "xattn_add":
            self.mmf = XAttnAddFusion(hidden_dim)
        elif self.mmf_type == "ra_gradd":
            self.mmf = ReliabilityAwareGRAdd(hidden_dim)
        else:
            raise ValueError(f"Unknown mmf_type: {mmf_type}")

        clf_in = hidden_dim * 2 if static_dim > 0 else hidden_dim
        self.classifier = nn.Sequential(
            nn.Linear(clf_in, hidden_dim),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(hidden_dim, 1),
        )

    def forward(self, batch: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
        ts_repr, _ = self.ts_encoder(
            batch["ts_values"],
            batch["ts_obs_mask"],
            batch["ts_pad_mask"],
            batch["ts_times"]
        )

        text_emb = self.text_proj(batch["text_embeddings"])

        decision_time = (batch["ts_times"] * batch["ts_pad_mask"]).max(dim=1).values

        if self.ttf_type == "recavg":
            text_repr = self.ttf(text_emb, batch["text_times"], batch["text_pad_mask"], decision_time)
        else:
            text_repr = self.ttf(text_emb, batch["text_times"], batch["text_pad_mask"], ts_repr)

        if self.mmf_type == "ra_gradd":
            lag = (decision_time.unsqueeze(1) - batch["text_times"]) * batch["text_pad_mask"]
            mean_recency = lag.sum(dim=1) / batch["text_pad_mask"].sum(dim=1).clamp_min(1.0)
            reliability = torch.stack(
                [
                    batch["note_density"],
                    batch["missingness_rate"],
                    batch["alignment_score"],
                    mean_recency,
                ],
                dim=1,
            )
            fused = self.mmf(ts_repr, text_repr, reliability)
        else:
            fused = self.mmf(ts_repr, text_repr)

        if self.static_proj is not None and batch["static_features"].shape[1] > 0:
            static_repr = self.static_proj(batch["static_features"])
            fused = torch.cat([fused, static_repr], dim=-1)

        logits = self.classifier(fused).squeeze(-1)
        probs = torch.sigmoid(logits)
        return {"logits": logits, "probs": probs}


# -----------------------------------------------------------------------------
# Section 5. Training and evaluation for the classification extension
# -----------------------------------------------------------------------------

def binary_classification_metrics(y_true: np.ndarray, y_prob: np.ndarray, threshold: float = 0.5) -> Dict[str, float]:
    y_pred = (y_prob >= threshold).astype(int)
    eps = 1e-8

    tp = float(((y_true == 1) & (y_pred == 1)).sum())
    tn = float(((y_true == 0) & (y_pred == 0)).sum())
    fp = float(((y_true == 0) & (y_pred == 1)).sum())
    fn = float(((y_true == 1) & (y_pred == 0)).sum())

    acc = (tp + tn) / max(tp + tn + fp + fn, eps)
    precision = tp / max(tp + fp, eps)
    recall = tp / max(tp + fn, eps)
    specificity = tn / max(tn + fp, eps)
    f1 = 2 * precision * recall / max(precision + recall, eps)

    order = np.argsort(y_prob)
    ranks = np.empty_like(order)
    ranks[order] = np.arange(len(y_prob)) + 1
    pos = y_true == 1
    n_pos = int(pos.sum())
    n_neg = int((~pos).sum())
    auc = np.nan
    if n_pos > 0 and n_neg > 0:
        auc = (ranks[pos].sum() - n_pos * (n_pos + 1) / 2) / (n_pos * n_neg)

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "specificity": specificity,
        "f1": f1,
        "auroc": float(auc) if not np.isnan(auc) else np.nan,
    }


@dataclass
class TrainConfig:
    train_path: Path
    valid_path: Path
    test_path: Path
    output_dir: Path
    ttf_type: str = "recavg"
    mmf_type: str = "ra_gradd"
    hidden_dim: int = 128
    batch_size: int = 32
    lr: float = 1e-3
    weight_decay: float = 1e-4
    max_epochs: int = 25
    patience: int = 5
    seed: int = 42
    pos_weight: Optional[float] = None
    device: str = "cuda" if (torch is not None and torch.cuda.is_available()) else "cpu"


def train_readmission_model(cfg: TrainConfig) -> pd.DataFrame:
    if torch is None:
        raise RuntimeError("PyTorch is required for the classification extension.")

    set_seed(cfg.seed)
    ensure_dir(cfg.output_dir)

    train_ds = ICUReadmissionWindowDataset(cfg.train_path)
    valid_ds = ICUReadmissionWindowDataset(cfg.valid_path)
    test_ds = ICUReadmissionWindowDataset(cfg.test_path)

    if len(train_ds) == 0:
        raise RuntimeError("Training dataset is empty.")

    train_loader = DataLoader(train_ds, batch_size=cfg.batch_size, shuffle=True, collate_fn=collate_readmission)
    valid_loader = DataLoader(valid_ds, batch_size=cfg.batch_size, shuffle=False, collate_fn=collate_readmission)
    test_loader = DataLoader(test_ds, batch_size=cfg.batch_size, shuffle=False, collate_fn=collate_readmission)

    sample = train_ds[0]
    ts_input_dim = int(sample["ts_values"].shape[1])
    text_dim = int(sample["text_embeddings"].shape[1])
    static_dim = int(sample["static_features"].shape[0])

    model = ReadmissionIMMClassifier(
        ts_input_dim=ts_input_dim,
        text_dim=text_dim,
        static_dim=static_dim,
        hidden_dim=cfg.hidden_dim,
        ttf_type=cfg.ttf_type,
        mmf_type=cfg.mmf_type,
    ).to(cfg.device)

    pos_weight = None
    if cfg.pos_weight is not None:
        pos_weight = torch.tensor([cfg.pos_weight], device=cfg.device)

    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    optimizer = torch.optim.Adam(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)

    best_state = None
    best_val = math.inf
    bad_epochs = 0
    history: List[Dict[str, Any]] = []

    def move_batch(batch: Dict[str, Any]) -> Dict[str, Any]:
        out: Dict[str, Any] = {}
        for k, v in batch.items():
            out[k] = v.to(cfg.device) if torch.is_tensor(v) else v
        return out

    def evaluate(loader: DataLoader, split: str) -> Dict[str, float]:
        model.eval()
        losses, probs, labels = [], [], []
        with torch.no_grad():
            for batch in loader:
                batch = move_batch(batch)
                out = model(batch)
                loss = criterion(out["logits"], batch["label"])
                losses.append(float(loss.item()))
                probs.append(out["probs"].detach().cpu().numpy())
                labels.append(batch["label"].detach().cpu().numpy())

        if not probs:
            metrics = {k: np.nan for k in ["accuracy", "precision", "recall", "specificity", "f1", "auroc"]}
            metrics["loss"] = np.nan
            metrics["split"] = split
            return metrics

        y_prob = np.concatenate(probs)
        y_true = np.concatenate(labels).astype(int)
        metrics = binary_classification_metrics(y_true, y_prob)
        metrics["loss"] = float(np.mean(losses)) if losses else np.nan
        metrics["split"] = split
        return metrics

    for epoch in range(1, cfg.max_epochs + 1):
        model.train()
        train_losses = []

        for batch in train_loader:
            batch = move_batch(batch)
            optimizer.zero_grad()
            out = model(batch)
            loss = criterion(out["logits"], batch["label"])
            loss.backward()
            optimizer.step()
            train_losses.append(float(loss.item()))

        train_metrics = evaluate(train_loader, "train")
        valid_metrics = evaluate(valid_loader, "valid")

        row = {
            "epoch": epoch,
            "train_loss_epoch_mean": float(np.mean(train_losses)) if train_losses else np.nan,
            **{f"train_{k}": v for k, v in train_metrics.items() if k != "split"},
            **{f"valid_{k}": v for k, v in valid_metrics.items() if k != "split"},
        }
        history.append(row)
        print(json.dumps(row, indent=2))

        if valid_metrics["loss"] < best_val:
            best_val = valid_metrics["loss"]
            bad_epochs = 0
            best_state = {k: v.detach().cpu() for k, v in model.state_dict().items()}
            torch.save(best_state, cfg.output_dir / "best_model.pt")
        else:
            bad_epochs += 1
            if bad_epochs >= cfg.patience:
                print(f"[INFO] Early stopping at epoch {epoch}.")
                break

    history_df = pd.DataFrame(history)
    save_df(history_df, cfg.output_dir / "training_history.csv")

    if best_state is None:
        raise RuntimeError("No model checkpoint was saved.")
    model.load_state_dict(best_state)

    test_metrics = evaluate(test_loader, "test")
    test_df = pd.DataFrame([test_metrics])
    save_df(test_df, cfg.output_dir / "test_metrics.csv")
    print("[INFO] Test metrics:")
    print(test_df)

    return test_df


# -----------------------------------------------------------------------------
# Section 6. High-level experiment entry points
# -----------------------------------------------------------------------------

def write_reproduction_plan_csv(
    out_csv: Path,
    datasets: Sequence[str],
    models: Sequence[str],
    seeds: Sequence[int]
) -> pd.DataFrame:
    rows = []
    for d in datasets:
        for m in models:
            for s in seeds:
                rows.append({"dataset": d, "model": m, "seed": s, "modality": "uni"})
                for ttf in TTF_MODULES:
                    for mmf in MMF_MODULES:
                        for enc in TEXT_ENCODERS:
                            rows.append({
                                "dataset": d,
                                "model": m,
                                "seed": s,
                                "modality": "multi",
                                "ttf_module": ttf,
                                "mmf_module": mmf,
                                "text_encoder": enc,
                            })
    df = pd.DataFrame(rows)
    save_df(df, out_csv)
    return df


def summarize_algorithm_changes() -> str:
    return (
        "Algorithm changes from IMM-TSF forecasting to ICU readmission classification:\n"
        "1. Problem target changes from predicting future numeric values Y at query times Q to predicting a binary label r in {0,1} for 30-day ICU readmission.\n"
        "2. The irregular time-series encoder is retained because the patient history is still irregular and missing-rich.\n"
        "3. The timestamp-to-text fusion block is retained because clinical notes are still asynchronous relative to structured measurements.\n"
        "4. The multimodality fusion block is retained, but now its output modifies a patient-level latent representation instead of a future forecast vector.\n"
        "5. The final head changes from regression to a sigmoid classification head trained with BCEWithLogitsLoss.\n"
        "6. The proposed RA-GRAdd extension adds explicit reliability signals to the gate: note density, missingness, alignment, and recency.\n"
        "7. Evaluation changes from MSE/MAE to AUROC, F1, recall, specificity, and calibration-oriented probability outputs."
    )


# -----------------------------------------------------------------------------
# Section 7. CLI (FULL COLAB/JUPYTER FIX)
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Section 7. CLI (ROBUST COLAB/JUPYTER FIX)
# -----------------------------------------------------------------------------

VALID_MODES = {
    "plan_repro",
    "run_repro",
    "collect_repro",
    "train_readmission",
    "show_changes",
}


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="TIME-IMM / IMM-TSF reproduction and MIMIC ICU readmission extension"
    )
    sub = p.add_subparsers(dest="mode", required=False)

    r = sub.add_parser("plan_repro")
    r.add_argument("--out_csv", type=Path, required=True)
    r.add_argument("--datasets", nargs="+", default=["MIMIC", "ClusterTrace", "FNSPID", "CESNET"])
    r.add_argument("--models", nargs="+", default=PAPER_MODELS)
    r.add_argument("--seeds", nargs="+", type=int, default=[42])

    rr = sub.add_parser("run_repro")
    rr.add_argument("--repo_root", type=Path, required=True)
    rr.add_argument("--data_root", type=Path, required=False, default=Path("data"))
    rr.add_argument("--log_root", type=Path, required=True)
    rr.add_argument("--results_root", type=Path, required=True)
    rr.add_argument("--datasets", nargs="+", default=["MIMIC"])
    rr.add_argument("--models", nargs="+", default=["tPatchGNN", "CRU", "Informer", "DLinear"])
    rr.add_argument("--seeds", nargs="+", type=int, default=[42])
    rr.add_argument("--run_limit", type=int, default=5)
    rr.add_argument("--patch_empty_split_eval", action="store_true")

    c = sub.add_parser("collect_repro")
    c.add_argument("--repo_root", type=Path, required=True)
    c.add_argument("--data_root", type=Path, required=False, default=Path("data"))
    c.add_argument("--log_root", type=Path, required=True)
    c.add_argument("--results_root", type=Path, required=True)

    t = sub.add_parser("train_readmission")
    t.add_argument("--train_path", type=Path, required=True)
    t.add_argument("--valid_path", type=Path, required=True)
    t.add_argument("--test_path", type=Path, required=True)
    t.add_argument("--output_dir", type=Path, required=True)
    t.add_argument("--ttf_type", choices=["recavg", "t2v_xattn"], default="recavg")
    t.add_argument("--mmf_type", choices=["gradd", "xattn_add", "ra_gradd"], default="ra_gradd")
    t.add_argument("--hidden_dim", type=int, default=128)
    t.add_argument("--batch_size", type=int, default=32)
    t.add_argument("--lr", type=float, default=1e-3)
    t.add_argument("--weight_decay", type=float, default=1e-4)
    t.add_argument("--max_epochs", type=int, default=25)
    t.add_argument("--patience", type=int, default=5)
    t.add_argument("--seed", type=int, default=42)
    t.add_argument("--pos_weight", type=float, default=None)

    sub.add_parser("show_changes")
    return p


def _running_in_notebook() -> bool:
    try:
        from IPython import get_ipython
        return get_ipython() is not None
    except Exception:
        return False


def _clean_argv_for_notebook(raw_argv: Sequence[str]) -> List[str]:
    """
    Keep only arguments if the first real token is one of our valid modes.
    Otherwise return [] so argparse never sees the kernel json path.
    """
    cleaned = [str(x) for x in raw_argv if str(x).strip()]
    if not cleaned:
        return []

    first = cleaned[0]
    if first in VALID_MODES:
        return cleaned

    # In notebooks, argv often looks like:
    # ['/root/.local/share/jupyter/runtime/kernel-....json']
    # or has extra IPython flags.
    # If first token is not a valid subcommand, ignore all of it.
    return []


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = build_parser()

    # Best path: explicit args from notebook, e.g.
    # main(["plan_repro", "--out_csv", "/content/repro_plan.csv"])
    if argv is not None:
        return parser.parse_args(list(argv))

    # Notebook-safe path: DO NOT parse raw sys.argv unless first token is a valid mode.
    if _running_in_notebook():
        notebook_args = _clean_argv_for_notebook(sys.argv[1:])
        return parser.parse_args(notebook_args)

    # Normal CLI path
    return parser.parse_args()


def main(argv: Optional[Sequence[str]] = None) -> None:
    parser = build_parser()
    args = parse_args(argv)

    if args.mode is None:
        print("[INFO] No mode supplied.")
        parser.print_help()
        print("\nColab examples:")
        print('main(["show_changes"])')
        print('main(["plan_repro", "--out_csv", "/content/repro_plan.csv"])')
        return

    if args.mode == "plan_repro":
        df = write_reproduction_plan_csv(args.out_csv, args.datasets, args.models, args.seeds)
        print(df.head())
        print(f"[INFO] Saved reproduction plan to {args.out_csv}")
        return

    if args.mode == "run_repro":
        paths = RepoPaths(args.repo_root, args.data_root, args.log_root, args.results_root)
        runner = IMMTSFReproducer(paths)
        if args.patch_empty_split_eval:
            runner.patch_evaluation_for_empty_splits()
        grid = runner.generate_experiment_grid(args.datasets, args.models, args.seeds)
        grid = grid[: args.run_limit]
        print(f"[INFO] Launching {len(grid)} runs.")
        for cfg in grid:
            code = runner.run_one(cfg)
            print(f"[INFO] {cfg.run_name()} exit code: {code}")
        return

    if args.mode == "collect_repro":
        paths = RepoPaths(args.repo_root, args.data_root, args.log_root, args.results_root)
        runner = IMMTSFReproducer(paths)
        results = runner.collect_results()
        results_path = paths.results_root / "all_repro_results.csv"
        results.to_csv(results_path, index=False)
        print(f"[INFO] Saved {results_path}")
        mimic_table = runner.build_mimic_comparison_table(results)
        mimic_path = paths.results_root / "mimic_paper_vs_ours.csv"
        mimic_table.to_csv(mimic_path, index=False)
        print(f"[INFO] Saved {mimic_path}")
        print(mimic_table.head())
        return

    if args.mode == "train_readmission":
        cfg = TrainConfig(
            train_path=args.train_path,
            valid_path=args.valid_path,
            test_path=args.test_path,
            output_dir=args.output_dir,
            ttf_type=args.ttf_type,
            mmf_type=args.mmf_type,
            hidden_dim=args.hidden_dim,
            batch_size=args.batch_size,
            lr=args.lr,
            weight_decay=args.weight_decay,
            max_epochs=args.max_epochs,
            patience=args.patience,
            seed=args.seed,
            pos_weight=args.pos_weight,
        )
        train_readmission_model(cfg)
        return

    if args.mode == "show_changes":
        print(summarize_algorithm_changes())
        return


if __name__ == "__main__":
    main()

[INFO] No mode supplied.
usage: colab_kernel_launcher.py [-h]
                                {plan_repro,run_repro,collect_repro,train_readmission,show_changes}
                                ...

TIME-IMM / IMM-TSF reproduction and MIMIC ICU readmission extension

positional arguments:
  {plan_repro,run_repro,collect_repro,train_readmission,show_changes}

options:
  -h, --help            show this help message and exit

Colab examples:
main(["show_changes"])
main(["plan_repro", "--out_csv", "/content/repro_plan.csv"])

In [ ]:
%%writefile /content/time_imm_repro_and_readmission_fixed.py
from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass, field
import json
import math
import random
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd

try:
    import torch
    import torch.nn as nn
    from torch.utils.data import Dataset, DataLoader
except Exception:
    torch = None
    nn = None
    Dataset = object
    DataLoader = object


PAPER_MODELS: List[str] = [
    "Informer",
    "DLinear",
    "PatchTST",
    "TimesNet",
    "TimeMixer",
    "TimeLLM",
    "TTM",
    "CRU",
    "LatentODE",
    "NeuralFlow",
    "tPatchGNN",
]

IRREGULAR_MODELS = {"CRU", "LatentODE", "NeuralFlow", "tPatchGNN"}
REGULAR_MODELS = {"Informer", "DLinear", "PatchTST", "TimesNet", "TimeMixer", "TimeLLM", "TTM"}
TTF_MODULES = ["TTF_RecAvg", "TTF_T2V_XAttn"]
MMF_MODULES = ["MMF_GR_Add", "MMF_XAttn_Add"]
TEXT_ENCODERS = ["GPT2", "BERT", "Llama", "DeepSeek"]

PAPER_DATASETS: List[str] = [
    "GDELT",
    "RepoHealth",
    "MIMIC",
    "FNSPID",
    "ClusterTrace",
    "StudentLife",
    "ILINet",
    "CESNET",
    "EPA-Air",
]

PAPER_DEFAULT_MODEL_ARGS: Dict[str, Dict[str, Any]] = {
    "Informer": {},
    "DLinear": {},
    "PatchTST": {"e_layers": 1, "d_layers": 1, "n_heads": 2},
    "TimesNet": {"e_layers": 2, "d_layers": 1, "top_k": 5, "d_model": 16, "d_ff": 32},
    "TimeMixer": {"e_layers": 2, "d_model": 16, "d_ff": 32, "down_sampling_layers": 3},
    "TimeLLM": {"llm_layers": 6, "input_token_len": 16, "output_token_len": 96, "d_model": 32, "d_ff": 128},
    "TTM": {"e_layers": 3, "d_layers": 2, "d_model": 1024, "decoder_d_model": 64},
    "CRU": {"latent_state": 32, "hidden_units": 32},
    "LatentODE": {"rec_hidden": 32, "ode_units": 32},
    "NeuralFlow": {"latent_dim": 20, "hidden_dim": 32, "gru_units": 32},
    "tPatchGNN": {"patch_size": 24, "nlayer": 1, "gnn_layer": 1, "te_dim": 10, "node_dim": 10, "d_hidden": 32},
}

PAPER_MIMIC_RESULTS = {
    "Informer": {"uni_mse": 0.8519, "multi_mse": 0.7988, "uni_mae": 0.5588, "multi_mae": 0.6083},
    "DLinear": {"uni_mse": 0.8770, "multi_mse": 0.8515, "uni_mae": 0.6152, "multi_mae": 0.6456},
    "PatchTST": {"uni_mse": 0.9394, "multi_mse": 0.9281, "uni_mae": 0.6794, "multi_mae": 0.6799},
    "TimesNet": {"uni_mse": 1.0374, "multi_mse": 0.9335, "uni_mae": 0.7348, "multi_mae": 0.6821},
    "TimeMixer": {"uni_mse": 0.8856, "multi_mse": 0.8179, "uni_mae": 0.5686, "multi_mae": 0.5821},
    "TimeLLM": {"uni_mse": 0.7901, "multi_mse": 0.7535, "uni_mae": 0.5457, "multi_mae": 0.5620},
    "TTM": {"uni_mse": 0.8620, "multi_mse": 0.9105, "uni_mae": 0.6283, "multi_mae": 0.6707},
    "CRU": {"uni_mse": 1.0122, "multi_mse": 0.9847, "uni_mae": 0.7235, "multi_mae": 0.7087},
    "LatentODE": {"uni_mse": 0.9325, "multi_mse": 0.9423, "uni_mae": 0.6868, "multi_mae": 0.6785},
    "NeuralFlow": {"uni_mse": 1.0086, "multi_mse": 0.9884, "uni_mae": 0.7219, "multi_mae": 0.7079},
    "tPatchGNN": {"uni_mse": 0.7250, "multi_mse": 0.7656, "uni_mae": 0.5479, "multi_mae": 0.5794},
}


def set_seed(seed: int = 42) -> None:
    random.seed(seed)
    np.random.seed(seed)
    if torch is not None:
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def run_command(cmd: Sequence[str], cwd: Optional[Path] = None, log_file: Optional[Path] = None) -> int:
    cwd_str = str(cwd) if cwd else None
    print("RUN:", " ".join(map(str, cmd)))
    proc = subprocess.Popen(
        list(map(str, cmd)),
        cwd=cwd_str,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    assert proc.stdout is not None
    writer = open(log_file, "w", encoding="utf-8") if log_file else None
    try:
        for line in proc.stdout:
            print(line, end="")
            if writer:
                writer.write(line)
    finally:
        if writer:
            writer.close()
    return proc.wait()


def save_df(df: pd.DataFrame, path: Path) -> None:
    ensure_dir(path.parent)
    df.to_csv(path, index=False)
    print(f"[INFO] Saved {path}")


VALID_MODES = {
    "plan_repro",
    "run_repro",
    "collect_repro",
    "train_readmission",
    "show_changes",
}


def _running_in_notebook() -> bool:
    try:
        from IPython import get_ipython
        return get_ipython() is not None
    except Exception:
        return False


def _clean_argv_for_notebook(raw_argv: Sequence[str]) -> List[str]:
    cleaned = [str(x) for x in raw_argv if str(x).strip()]
    if not cleaned:
        return []
    if cleaned[0] in VALID_MODES:
        return cleaned
    return []


@dataclass
class ReproRunConfig:
    dataset: str
    model: str
    multimodal: bool
    seed: int = 42
    batch_size: int = 8
    epochs: int = 20
    split_method: str = "instance"
    ttf_module: Optional[str] = None
    mmf_module: Optional[str] = None
    text_encoder: Optional[str] = None
    dataset_overrides: Dict[str, Any] = field(default_factory=dict)

    def run_name(self) -> str:
        pieces = [self.dataset, self.model, f"seed{self.seed}", "multi" if self.multimodal else "uni"]
        if self.multimodal:
            pieces.extend([self.ttf_module or "NA", self.mmf_module or "NA", self.text_encoder or "NA"])
        return "__".join(pieces)


@dataclass
class RepoPaths:
    repo_root: Path
    data_root: Path
    log_root: Path
    results_root: Path


class IMMTSFReproducer:
    def __init__(self, paths: RepoPaths):
        self.paths = paths
        ensure_dir(paths.log_root)
        ensure_dir(paths.results_root)

    def patch_evaluation_for_empty_splits(self) -> None:
        target_file = self.paths.repo_root / "lib" / "evaluation.py"
        if not target_file.exists():
            print(f"[WARN] {target_file} not found; skipping empty-split patch.")
            return

        backup = target_file.with_name("evaluation_backup_before_empty_split_patch.py")
        if not backup.exists():
            shutil.copy(target_file, backup)

        text = target_file.read_text(encoding="utf-8")
        target = "n_avai_var = torch.count_nonzero(n_eval_samples)"

        if "auto-patch for empty validation/test splits" in text:
            print("[INFO] evaluation.py already patched.")
            return

        replacement = '''# ---- auto-patch for empty validation/test splits ----
    if isinstance(n_eval_samples, int):
        if n_eval_samples == 0:
            return {
                "loss": float("nan"),
                "mse": float("nan"),
                "mae": float("nan"),
                "rmse": float("nan"),
                "mape": float("nan"),
            }
        n_eval_samples = torch.tensor(n_eval_samples)

    n_avai_var = torch.count_nonzero(n_eval_samples)

    if isinstance(n_avai_var, torch.Tensor) and n_avai_var.item() == 0:
        return {
            "loss": float("nan"),
            "mse": float("nan"),
            "mae": float("nan"),
            "rmse": float("nan"),
            "mape": float("nan"),
        }'''

        if target in text:
            text = text.replace(target, replacement)
            target_file.write_text(text, encoding="utf-8")
            print("[INFO] Patched evaluation.py for empty validation/test splits.")
        else:
            print("[WARN] Expected line not found in evaluation.py; patch not applied.")

    def build_main_command(self, cfg: ReproRunConfig) -> List[str]:
        cmd = [
            sys.executable,
            "main.py",
            "--dataset", cfg.dataset,
            "--model", cfg.model,
            "--split_method", cfg.split_method,
            "-b", str(cfg.batch_size),
            "--epoch", str(cfg.epochs),
            "--seed", str(cfg.seed),
        ]

        model_defaults = dict(PAPER_DEFAULT_MODEL_ARGS.get(cfg.model, {}))
        model_defaults.update(cfg.dataset_overrides)

        for k, v in model_defaults.items():
            cmd.extend([f"--{k}", str(v)])

        if cfg.multimodal:
            if cfg.ttf_module:
                cmd.extend(["--TTF_module", cfg.ttf_module])
            if cfg.mmf_module:
                cmd.extend(["--MMF_module", cfg.mmf_module])
            if cfg.text_encoder:
                cmd.extend(["--llm_model_fusion", cfg.text_encoder])
            cmd.extend(["--use_text_embeddings", "--enable_text"])

        return cmd

    def generate_experiment_grid(
        self,
        datasets: Sequence[str],
        models: Sequence[str],
        seeds: Sequence[int],
        include_unimodal: bool = True,
        include_multimodal: bool = True,
    ) -> List[ReproRunConfig]:
        grid: List[ReproRunConfig] = []
        for dataset in datasets:
            for model in models:
                for seed in seeds:
                    overrides = self.dataset_specific_overrides(dataset, model)

                    if include_unimodal:
                        grid.append(
                            ReproRunConfig(
                                dataset=dataset,
                                model=model,
                                multimodal=False,
                                seed=seed,
                                dataset_overrides=overrides,
                            )
                        )

                    if include_multimodal:
                        for ttf in TTF_MODULES:
                            for mmf in MMF_MODULES:
                                for enc in TEXT_ENCODERS:
                                    grid.append(
                                        ReproRunConfig(
                                            dataset=dataset,
                                            model=model,
                                            multimodal=True,
                                            seed=seed,
                                            ttf_module=ttf,
                                            mmf_module=mmf,
                                            text_encoder=enc,
                                            dataset_overrides=overrides,
                                        )
                                    )
        return grid

    def dataset_specific_overrides(self, dataset: str, model: str) -> Dict[str, Any]:
        if dataset == "CESNET" and model == "tPatchGNN":
            return {
                "history": 12,
                "pred_window": 6,
                "stride": 6,
                "patch_size": 6,
                "patch_stride": 6,
                "npatch": 2,
            }
        return {}

    def run_one(self, cfg: ReproRunConfig) -> int:
        log_file = self.paths.log_root / f"{cfg.run_name()}.log"
        cmd = self.build_main_command(cfg)
        return run_command(cmd, cwd=self.paths.repo_root, log_file=log_file)

    def parse_metrics_from_log(self, log_file: Path) -> Dict[str, Any]:
        text = log_file.read_text(encoding="utf-8", errors="ignore")
        out: Dict[str, Any] = {"log_file": str(log_file)}

        patterns = {
            "mse": [r"\bmse\b\s*[:=]\s*([0-9]*\.?[0-9]+)", r"\bMSE\b\s*[:=]\s*([0-9]*\.?[0-9]+)"],
            "mae": [r"\bmae\b\s*[:=]\s*([0-9]*\.?[0-9]+)", r"\bMAE\b\s*[:=]\s*([0-9]*\.?[0-9]+)"],
            "rmse": [r"\brmse\b\s*[:=]\s*([0-9]*\.?[0-9]+)", r"\bRMSE\b\s*[:=]\s*([0-9]*\.?[0-9]+)"],
            "mape": [r"\bmape\b\s*[:=]\s*([0-9]*\.?[0-9]+)", r"\bMAPE\b\s*[:=]\s*([0-9]*\.?[0-9]+)"],
            "val_loss": [r"val(?:idation)?\s*loss\s*[:=]\s*([0-9]*\.?[0-9]+)"],
        }

        for name, pats in patterns.items():
            vals = []
            for pat in pats:
                vals.extend(re.findall(pat, text, flags=re.IGNORECASE))
            if vals:
                out[name] = float(vals[-1])

        return out

    def collect_results(self) -> pd.DataFrame:
        rows = []
        for log_file in sorted(self.paths.log_root.glob("*.log")):
            metrics = self.parse_metrics_from_log(log_file)
            stem = log_file.stem.split("__")
            row = {
                "dataset": stem[0] if len(stem) > 0 else None,
                "model": stem[1] if len(stem) > 1 else None,
                "seed": stem[2] if len(stem) > 2 else None,
                "modality": stem[3] if len(stem) > 3 else None,
                "ttf_module": stem[4] if len(stem) > 4 else None,
                "mmf_module": stem[5] if len(stem) > 5 else None,
                "text_encoder": stem[6] if len(stem) > 6 else None,
            }
            row.update(metrics)
            rows.append(row)

        df = pd.DataFrame(rows)
        if not df.empty:
            sort_cols = [c for c in ["dataset", "model", "modality", "text_encoder", "ttf_module", "mmf_module", "seed"] if c in df.columns]
            df = df.sort_values(sort_cols)
        return df

    def build_mimic_comparison_table(self, results_df: pd.DataFrame) -> pd.DataFrame:
        if results_df.empty or "dataset" not in results_df.columns:
            return pd.DataFrame()

        mimic = results_df[results_df["dataset"] == "MIMIC"].copy()
        if mimic.empty:
            return pd.DataFrame()

        rows = []
        for model in sorted(mimic["model"].dropna().unique()):
            sub = mimic[mimic["model"] == model]
            uni = sub[sub["modality"] == "uni"]
            multi = sub[sub["modality"] == "multi"]

            best_uni_mse = uni["mse"].min() if (not uni.empty and "mse" in uni.columns) else np.nan
            best_multi_mse = multi["mse"].min() if (not multi.empty and "mse" in multi.columns) else np.nan
            best_uni_mae = uni["mae"].min() if (not uni.empty and "mae" in uni.columns) else np.nan
            best_multi_mae = multi["mae"].min() if (not multi.empty and "mae" in multi.columns) else np.nan

            paper = PAPER_MIMIC_RESULTS.get(model, {})
            rows.append({
                "model": model,
                "paper_uni_mse": paper.get("uni_mse"),
                "our_best_uni_mse": best_uni_mse,
                "paper_multi_mse": paper.get("multi_mse"),
                "our_best_multi_mse": best_multi_mse,
                "paper_uni_mae": paper.get("uni_mae"),
                "our_best_uni_mae": best_uni_mae,
                "paper_multi_mae": paper.get("multi_mae"),
                "our_best_multi_mae": best_multi_mae,
                "delta_multi_mse_vs_paper": best_multi_mse - paper.get("multi_mse", np.nan) if not np.isnan(best_multi_mse) else np.nan,
                "delta_uni_mse_vs_paper": best_uni_mse - paper.get("uni_mse", np.nan) if not np.isnan(best_uni_mse) else np.nan,
            })

        return pd.DataFrame(rows).sort_values("model")


def write_reproduction_plan_csv(out_csv: Path, datasets: Sequence[str], models: Sequence[str], seeds: Sequence[int]) -> pd.DataFrame:
    rows = []
    for d in datasets:
        for m in models:
            for s in seeds:
                rows.append({"dataset": d, "model": m, "seed": s, "modality": "uni"})
                for ttf in TTF_MODULES:
                    for mmf in MMF_MODULES:
                        for enc in TEXT_ENCODERS:
                            rows.append({
                                "dataset": d,
                                "model": m,
                                "seed": s,
                                "modality": "multi",
                                "ttf_module": ttf,
                                "mmf_module": mmf,
                                "text_encoder": enc,
                            })
    df = pd.DataFrame(rows)
    save_df(df, out_csv)
    return df


def summarize_algorithm_changes() -> str:
    return (
        "Algorithm changes from IMM-TSF forecasting to ICU readmission classification:\\n"
        "1. Problem target changes from predicting future numeric values Y at query times Q to predicting a binary label r in {0,1} for 30-day ICU readmission.\\n"
        "2. The irregular time-series encoder is retained because the patient history is still irregular and missing-rich.\\n"
        "3. The timestamp-to-text fusion block is retained because clinical notes are still asynchronous relative to structured measurements.\\n"
        "4. The multimodality fusion block is retained, but now its output modifies a patient-level latent representation instead of a future forecast vector.\\n"
        "5. The final head changes from regression to a sigmoid classification head trained with BCEWithLogitsLoss.\\n"
        "6. The proposed RA-GRAdd extension adds explicit reliability signals to the gate: note density, missingness, alignment, and recency.\\n"
        "7. Evaluation changes from MSE/MAE to AUROC, F1, recall, specificity, and calibration-oriented probability outputs."
    )


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="TIME-IMM / IMM-TSF reproduction and MIMIC ICU readmission extension"
    )
    sub = p.add_subparsers(dest="mode", required=False)

    r = sub.add_parser("plan_repro")
    r.add_argument("--out_csv", type=Path, required=True)
    r.add_argument("--datasets", nargs="+", default=["MIMIC", "ClusterTrace", "FNSPID", "CESNET"])
    r.add_argument("--models", nargs="+", default=PAPER_MODELS)
    r.add_argument("--seeds", nargs="+", type=int, default=[42])

    rr = sub.add_parser("run_repro")
    rr.add_argument("--repo_root", type=Path, required=True)
    rr.add_argument("--data_root", type=Path, required=False, default=Path("data"))
    rr.add_argument("--log_root", type=Path, required=True)
    rr.add_argument("--results_root", type=Path, required=True)
    rr.add_argument("--datasets", nargs="+", default=["MIMIC"])
    rr.add_argument("--models", nargs="+", default=["tPatchGNN", "CRU", "Informer", "DLinear"])
    rr.add_argument("--seeds", nargs="+", type=int, default=[42])
    rr.add_argument("--run_limit", type=int, default=5)
    rr.add_argument("--patch_empty_split_eval", action="store_true")

    c = sub.add_parser("collect_repro")
    c.add_argument("--repo_root", type=Path, required=True)
    c.add_argument("--data_root", type=Path, required=False, default=Path("data"))
    c.add_argument("--log_root", type=Path, required=True)
    c.add_argument("--results_root", type=Path, required=True)

    sub.add_parser("show_changes")
    return p


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = build_parser()

    if argv is not None:
        return parser.parse_args(list(argv))

    if _running_in_notebook():
        raw = list(sys.argv[1:])
        if not raw or raw[0] not in VALID_MODES:
            raw = []
        return parser.parse_args(raw)

    return parser.parse_args()


def main(argv: Optional[Sequence[str]] = None) -> None:
    parser = build_parser()
    args = parse_args(argv)

    if args.mode is None:
        print("[INFO] No mode supplied.")
        parser.print_help()
        print('\\nColab examples:')
        print('main(["show_changes"])')
        print('main(["plan_repro", "--out_csv", "/content/repro_plan.csv"])')
        return

    if args.mode == "plan_repro":
        df = write_reproduction_plan_csv(args.out_csv, args.datasets, args.models, args.seeds)
        print(df.head())
        print(f"[INFO] Saved reproduction plan to {args.out_csv}")
        return

    if args.mode == "run_repro":
        paths = RepoPaths(args.repo_root, args.data_root, args.log_root, args.results_root)
        runner = IMMTSFReproducer(paths)
        if args.patch_empty_split_eval:
            runner.patch_evaluation_for_empty_splits()
        grid = runner.generate_experiment_grid(args.datasets, args.models, args.seeds)
        grid = grid[: args.run_limit]
        print(f"[INFO] Launching {len(grid)} runs.")
        for cfg in grid:
            code = runner.run_one(cfg)
            print(f"[INFO] {cfg.run_name()} exit code: {code}")
        return

    if args.mode == "collect_repro":
        paths = RepoPaths(args.repo_root, args.data_root, args.log_root, args.results_root)
        runner = IMMTSFReproducer(paths)
        results = runner.collect_results()
        results_path = paths.results_root / "all_repro_results.csv"
        save_df(results, results_path)
        mimic_table = runner.build_mimic_comparison_table(results)
        mimic_path = paths.results_root / "mimic_paper_vs_ours.csv"
        save_df(mimic_table, mimic_path)
        print(mimic_table.head())
        return

    if args.mode == "show_changes":
        print(summarize_algorithm_changes())
        return


if __name__ == "__main__":
    main()

Writing /content/time_imm_repro_and_readmission_fixed.py

In [ ]:
!python /content/time_imm_repro_and_readmission_fixed.py plan_repro --out_csv /content/repro_plan.csv

[INFO] Saved /content/repro_plan.csv
  dataset     model  seed modality  ttf_module  mmf_module text_encoder
0   MIMIC  Informer    42      uni         NaN         NaN          NaN
1   MIMIC  Informer    42    multi  TTF_RecAvg  MMF_GR_Add         GPT2
2   MIMIC  Informer    42    multi  TTF_RecAvg  MMF_GR_Add         BERT
3   MIMIC  Informer    42    multi  TTF_RecAvg  MMF_GR_Add        Llama
4   MIMIC  Informer    42    multi  TTF_RecAvg  MMF_GR_Add     DeepSeek
[INFO] Saved reproduction plan to /content/repro_plan.csv

In [ ]:
!cd /content/drive/MyDrive/IMM-TSF && python compute_text_embeddings.py --llm_model GPT2
!cd /content/drive/MyDrive/IMM-TSF && python compute_text_embeddings.py --llm_model BERT

### LLM model: GPT2 ###
### Processing dataset: ClusterTrace ###
config.json: 100% 665/665 [00:00<00:00, 2.68MB/s]
tokenizer_config.json: 100% 26.0/26.0 [00:00<00:00, 194kB/s]
vocab.json: 1.04MB [00:00, 24.5MB/s]
merges.txt: 456kB [00:00, 77.6MB/s]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
tokenizer.json: 1.36MB [00:00, 94.3MB/s]
Detected 1 GPUs. Using model parallelism.
model.safetensors: 100% 548M/548M [00:02<00:00, 238MB/s]
Loading weights: 100% 148/148 [00:00<00:00, 911.43it/s, Materializing param=wte.weight]
GPT2Model LOAD REPORT from: openai-community/gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loaded GPT2 with 6 layers for fusion.
[1/3] Processing record: 1c6afd5c227e89b8a29589f4
[SKIP] Embeddings already exist for '1c6afd5c227e89b8a29589f4', skipping.
[2/3] Processing record: 35fc40d2844c0b899c1ceb1e
[SKIP] Embeddings already exist for '35fc40d2844c0b899c1ceb1e', skipping.
[3/3] Processing record: 7077ec572d50395cafcbcb7d
[SKIP] Embeddings already exist for '7077ec572d50395cafcbcb7d', skipping.
### LLM model: GPT2 ###
### Processing dataset: ClusterTrace ###
Detected 1 GPUs. Using model parallelism.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100% 148/148 [00:00<00:00, 942.99it/s, Materializing param=wte.weight]
GPT2Model LOAD REPORT from: openai-community/gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loaded GPT2 with 6 layers for fusion.
[1/3] Processing record: 1c6afd5c227e89b8a29589f4
[SKIP] Embeddings already exist for '1c6afd5c227e89b8a29589f4', skipping.
[2/3] Processing record: 35fc40d2844c0b899c1ceb1e
[SKIP] Embeddings already exist for '35fc40d2844c0b899c1ceb1e', skipping.
[3/3] Processing record: 7077ec572d50395cafcbcb7d
[SKIP] Embeddings already exist for '7077ec572d50395cafcbcb7d', skipping.

In [ ]:
!python /content/time_imm_repro_and_readmission_fixed.py run_repro \
  --repo_root /content/drive/MyDrive/IMM-TSF \
  --log_root /content/drive/MyDrive/IMM-TSF/run_logs_full \
  --results_root /content/drive/MyDrive/IMM-TSF/results_full \
  --datasets MIMIC ClusterTrace \
  --models tPatchGNN CRU Informer DLinear \
  --seeds 42 \
  --run_limit 8 \
  --patch_empty_split_eval

[INFO] evaluation.py already patched.
[INFO] Launching 8 runs.
RUN: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --gnn_layer 1 --te_dim 10 --node_dim 10 --d_hidden 32
Traceback (most recent call last):
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 23, in <module>
    from models.tPatchGNN import tPatchGNN
  File "/content/drive/MyDrive/IMM-TSF/models/tPatchGNN.py", line 7, in <module>
    from layers.SelfAttention_Family import FullAttention, AttentionLayer
  File "/content/drive/MyDrive/IMM-TSF/layers/SelfAttention_Family.py", line 6, in <module>
    from reformer_pytorch import LSHSelfAttention
ModuleNotFoundError: No module named 'reformer_pytorch'
[INFO] MIMIC__tPatchGNN__seed42__uni exit code: 1
RUN: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --gnn_layer 1 --te_dim 10 --node_dim 10 --d_hidden 32 --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion GPT2 --use_text_embeddings --enable_text
Traceback (most recent call last):
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 23, in <module>
    from models.tPatchGNN import tPatchGNN
  File "/content/drive/MyDrive/IMM-TSF/models/tPatchGNN.py", line 7, in <module>
    from layers.SelfAttention_Family import FullAttention, AttentionLayer
  File "/content/drive/MyDrive/IMM-TSF/layers/SelfAttention_Family.py", line 6, in <module>
    from reformer_pytorch import LSHSelfAttention
ModuleNotFoundError: No module named 'reformer_pytorch'
[INFO] MIMIC__tPatchGNN__seed42__multi__TTF_RecAvg__MMF_GR_Add__GPT2 exit code: 1
RUN: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --gnn_layer 1 --te_dim 10 --node_dim 10 --d_hidden 32 --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion BERT --use_text_embeddings --enable_text
Traceback (most recent call last):
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 23, in <module>
    from models.tPatchGNN import tPatchGNN
  File "/content/drive/MyDrive/IMM-TSF/models/tPatchGNN.py", line 7, in <module>
    from layers.SelfAttention_Family import FullAttention, AttentionLayer
  File "/content/drive/MyDrive/IMM-TSF/layers/SelfAttention_Family.py", line 6, in <module>
    from reformer_pytorch import LSHSelfAttention
ModuleNotFoundError: No module named 'reformer_pytorch'
[INFO] MIMIC__tPatchGNN__seed42__multi__TTF_RecAvg__MMF_GR_Add__BERT exit code: 1
RUN: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --gnn_layer 1 --te_dim 10 --node_dim 10 --d_hidden 32 --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion Llama --use_text_embeddings --enable_text
Traceback (most recent call last):
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 23, in <module>
    from models.tPatchGNN import tPatchGNN
  File "/content/drive/MyDrive/IMM-TSF/models/tPatchGNN.py", line 7, in <module>
    from layers.SelfAttention_Family import FullAttention, AttentionLayer
  File "/content/drive/MyDrive/IMM-TSF/layers/SelfAttention_Family.py", line 6, in <module>
    from reformer_pytorch import LSHSelfAttention
ModuleNotFoundError: No module named 'reformer_pytorch'
[INFO] MIMIC__tPatchGNN__seed42__multi__TTF_RecAvg__MMF_GR_Add__Llama exit code: 1
RUN: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --gnn_layer 1 --te_dim 10 --node_dim 10 --d_hidden 32 --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion DeepSeek --use_text_embeddings --enable_text
Traceback (most recent call last):
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 23, in <module>
    from models.tPatchGNN import tPatchGNN
  File "/content/drive/MyDrive/IMM-TSF/models/tPatchGNN.py", line 7, in <module>
    from layers.SelfAttention_Family import FullAttention, AttentionLayer
  File "/content/drive/MyDrive/IMM-TSF/layers/SelfAttention_Family.py", line 6, in <module>
    from reformer_pytorch import LSHSelfAttention
ModuleNotFoundError: No module named 'reformer_pytorch'
[INFO] MIMIC__tPatchGNN__seed42__multi__TTF_RecAvg__MMF_GR_Add__DeepSeek exit code: 1
RUN: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --gnn_layer 1 --te_dim 10 --node_dim 10 --d_hidden 32 --TTF_module TTF_RecAvg --MMF_module MMF_XAttn_Add --llm_model_fusion GPT2 --use_text_embeddings --enable_text
Traceback (most recent call last):
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 23, in <module>
    from models.tPatchGNN import tPatchGNN
  File "/content/drive/MyDrive/IMM-TSF/models/tPatchGNN.py", line 7, in <module>
    from layers.SelfAttention_Family import FullAttention, AttentionLayer
  File "/content/drive/MyDrive/IMM-TSF/layers/SelfAttention_Family.py", line 6, in <module>
    from reformer_pytorch import LSHSelfAttention
ModuleNotFoundError: No module named 'reformer_pytorch'
[INFO] MIMIC__tPatchGNN__seed42__multi__TTF_RecAvg__MMF_XAttn_Add__GPT2 exit code: 1
RUN: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --gnn_layer 1 --te_dim 10 --node_dim 10 --d_hidden 32 --TTF_module TTF_RecAvg --MMF_module MMF_XAttn_Add --llm_model_fusion BERT --use_text_embeddings --enable_text
Traceback (most recent call last):
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 23, in <module>
    from models.tPatchGNN import tPatchGNN
  File "/content/drive/MyDrive/IMM-TSF/models/tPatchGNN.py", line 7, in <module>
    from layers.SelfAttention_Family import FullAttention, AttentionLayer
  File "/content/drive/MyDrive/IMM-TSF/layers/SelfAttention_Family.py", line 6, in <module>
    from reformer_pytorch import LSHSelfAttention
ModuleNotFoundError: No module named 'reformer_pytorch'
[INFO] MIMIC__tPatchGNN__seed42__multi__TTF_RecAvg__MMF_XAttn_Add__BERT exit code: 1
RUN: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --gnn_layer 1 --te_dim 10 --node_dim 10 --d_hidden 32 --TTF_module TTF_RecAvg --MMF_module MMF_XAttn_Add --llm_model_fusion Llama --use_text_embeddings --enable_text
Traceback (most recent call last):
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 23, in <module>
    from models.tPatchGNN import tPatchGNN
  File "/content/drive/MyDrive/IMM-TSF/models/tPatchGNN.py", line 7, in <module>
    from layers.SelfAttention_Family import FullAttention, AttentionLayer
  File "/content/drive/MyDrive/IMM-TSF/layers/SelfAttention_Family.py", line 6, in <module>
    from reformer_pytorch import LSHSelfAttention
ModuleNotFoundError: No module named 'reformer_pytorch'
[INFO] MIMIC__tPatchGNN__seed42__multi__TTF_RecAvg__MMF_XAttn_Add__Llama exit code: 1

In [ ]:
!python /content/time_imm_repro_and_readmission_fixed.py collect_repro \
  --repo_root /content/drive/MyDrive/IMM-TSF \
  --log_root /content/drive/MyDrive/IMM-TSF/run_logs_full \
  --results_root /content/drive/MyDrive/IMM-TSF/results_full

In [ ]:
!/usr/bin/python3 -m pip install -q reformer-pytorch

In [ ]:
!/usr/bin/python3 -m pip install -q reformer-pytorch

In [ ]:
!/usr/bin/python3 -c "import reformer_pytorch; print('reformer_pytorch import OK')"

reformer_pytorch import OK

In [ ]:
!python /content/time_imm_repro_and_readmission_fixed.py run_repro \
  --repo_root /content/drive/MyDrive/IMM-TSF \
  --log_root /content/drive/MyDrive/IMM-TSF/run_logs_full \
  --results_root /content/drive/MyDrive/IMM-TSF/results_full \
  --datasets MIMIC \
  --models tPatchGNN \
  --seeds 42 \
  --run_limit 1 \
  --patch_empty_split_eval

[INFO] evaluation.py already patched.
[INFO] Launching 1 runs.
RUN: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --gnn_layer 1 --te_dim 10 --node_dim 10 --d_hidden 32
Traceback (most recent call last):
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 27, in <module>
    from models.NeuralFlow import NeuralFlow
  File "/content/drive/MyDrive/IMM-TSF/models/NeuralFlow.py", line 7, in <module>
    from lib.neural_flow_components.latent_ode_lib.create_latent_ode_model import create_LatentODE_model
  File "/content/drive/MyDrive/IMM-TSF/lib/neural_flow_components/latent_ode_lib/create_latent_ode_model.py", line 6, in <module>
    from lib.neural_flow_components.models import CouplingFlow, ODEModel, ResNetFlow
  File "/content/drive/MyDrive/IMM-TSF/lib/neural_flow_components/models/__init__.py", line 1, in <module>
    from .flow import CouplingFlow, ResNetFlow
  File "/content/drive/MyDrive/IMM-TSF/lib/neural_flow_components/models/flow.py", line 4, in <module>
    import stribor as st
ModuleNotFoundError: No module named 'stribor'
[INFO] MIMIC__tPatchGNN__seed42__uni exit code: 1

In [ ]:
!/usr/bin/python3 -m pip install -q stribor

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 2.3 MB/s eta 0:00:00

In [ ]:
!python /content/time_imm_repro_and_readmission_fixed.py run_repro \
  --repo_root /content/drive/MyDrive/IMM-TSF \
  --log_root /content/drive/MyDrive/IMM-TSF/run_logs_full \
  --results_root /content/drive/MyDrive/IMM-TSF/results_full \
  --datasets MIMIC \
  --models tPatchGNN \
  --seeds 42 \
  --run_limit 1 \
  --patch_empty_split_eval

[INFO] evaluation.py already patched.
[INFO] Launching 1 runs.
RUN: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --gnn_layer 1 --te_dim 10 --node_dim 10 --d_hidden 32
Traceback (most recent call last):
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 27, in <module>
    from models.NeuralFlow import NeuralFlow
  File "/content/drive/MyDrive/IMM-TSF/models/NeuralFlow.py", line 7, in <module>
    from lib.neural_flow_components.latent_ode_lib.create_latent_ode_model import create_LatentODE_model
  File "/content/drive/MyDrive/IMM-TSF/lib/neural_flow_components/latent_ode_lib/create_latent_ode_model.py", line 6, in <module>
    from lib.neural_flow_components.models import CouplingFlow, ODEModel, ResNetFlow
  File "/content/drive/MyDrive/IMM-TSF/lib/neural_flow_components/models/__init__.py", line 1, in <module>
    from .flow import CouplingFlow, ResNetFlow
  File "/content/drive/MyDrive/IMM-TSF/lib/neural_flow_components/models/flow.py", line 4, in <module>
    import stribor as st
  File "/usr/local/lib/python3.12/dist-packages/stribor/__init__.py", line 1, in <module>
    from .dist import *
  File "/usr/local/lib/python3.12/dist-packages/stribor/dist/__init__.py", line 1, in <module>
    from .normal import *
  File "/usr/local/lib/python3.12/dist-packages/stribor/dist/normal.py", line 2, in <module>
    from torchtyping import TensorType
  File "/usr/local/lib/python3.12/dist-packages/torchtyping/__init__.py", line 10, in <module>
    from .tensor_type import TensorType
  File "/usr/local/lib/python3.12/dist-packages/torchtyping/tensor_type.py", line 37, in <module>
    class TensorTypeMixin(metaclass=_TensorTypeMeta):
RuntimeError: Cannot subclass _TensorBase directly
[INFO] MIMIC__tPatchGNN__seed42__uni exit code: 1

In [ ]:
!/usr/bin/python3 -m pip install -q --upgrade torchtyping typeguard

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
stribor 0.2.0 requires torchtyping==0.1.4, but you have torchtyping 0.1.5 which is incompatible.
inflect 7.5.0 requires typeguard>=4.0.1, but you have typeguard 2.13.3 which is incompatible.

In [ ]:
!python /content/time_imm_repro_and_readmission_fixed.py run_repro \
  --repo_root /content/drive/MyDrive/IMM-TSF \
  --log_root /content/drive/MyDrive/IMM-TSF/run_logs_full \
  --results_root /content/drive/MyDrive/IMM-TSF/results_full \
  --datasets MIMIC \
  --models tPatchGNN \
  --seeds 42 \
  --run_limit 1 \
  --patch_empty_split_eval

[INFO] evaluation.py already patched.
[INFO] Launching 1 runs.
RUN: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --gnn_layer 1 --te_dim 10 --node_dim 10 --d_hidden 32
Traceback (most recent call last):
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 28, in <module>
    from models.CRU import CRU
  File "/content/drive/MyDrive/IMM-TSF/models/CRU.py", line 5, in <module>
    from lib.cru_components.cru_models import Physionet_USHCN # Using this as the general CRU model structure
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/IMM-TSF/lib/cru_components/cru_models.py", line 21, in <module>
    from lib.cru_components.CRU_Module import CRU_Module
  File "/content/drive/MyDrive/IMM-TSF/lib/cru_components/CRU_Module.py", line 42, in <module>
    from lib.cru_components.CRULayer import CRULayer
  File "/content/drive/MyDrive/IMM-TSF/lib/cru_components/CRULayer.py", line 22, in <module>
    from lib.cru_components.CRUCell import RKNCell, CRUCell
  File "/content/drive/MyDrive/IMM-TSF/lib/cru_components/CRUCell.py", line 23, in <module>
    import geotorch
ModuleNotFoundError: No module named 'geotorch'
[INFO] MIMIC__tPatchGNN__seed42__uni exit code: 1

In [ ]:
!sed -n '1,80p' /content/drive/MyDrive/IMM-TSF/main.py

import os
import sys

import time
import datetime
import argparse
import numpy as np
import pandas as pd
from random import SystemRandom
from tqdm import tqdm
from torch.cuda.amp import autocast, GradScaler
import torch
import torch.nn as nn
import torch.optim as optim

from utils.tools import set_seed, print_formatted_dict, select_best_metrics
import lib.utils as utils
from lib.evaluation import compute_all_losses, evaluation

# from lib.parse_datasets_old import parse_datasets, get_input_and_pred_len

from lib.parse_datasets import parse_datasets, get_input_and_pred_len
from models.tPatchGNN import tPatchGNN
from models.TimesNet import TimesNet
from models.DLinear import DLinear
from models.PatchTST import PatchTST
from models.NeuralFlow import NeuralFlow
from models.CRU import CRU
from models.LatentODE import LatentODE  # Added LatentODE import

# from models.MTGNN import MTGNN
from models.Informer import Informer

# from models.TimeXer import TimeXer
from models.TimeMixer import TimeMixer
from models.TimeLLM import TimeLLM
from models.TTM import TTM

from fusions.FusionModel import FusionModel
from fusions.load_llm import get_context_window_size


def get_args_from_parser() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="IMMTSF")

    # ── General / Execution Options ──────────────────────────────────────────────
    parser.add_argument(
        "--overwrite_args",
        action="store_true",
        help="overwrite args with fixed_params and tunable_params",
        default=False,
    )
    parser.add_argument(
        "--state",
        type=str,
        default="def",
        help='State of the experiment (e.g., "def", "train", "eval")',
    )
    parser.add_argument(
        "--seed", type=int, default=1, help="Random seed for reproducibility"
    )
    parser.add_argument("--gpu", type=str, default="0", help="GPU device ID to use")

    # ── Paths & Data Selection ───────────────────────────────────────────────────
    parser.add_argument(
        "--dataset", type=str, default="FNSPID", help="Which dataset to load"
    )
    parser.add_argument(
        "--data_root",
        type=str,
        default="./data",
        help="Root directory for all data files",
    )
    parser.add_argument(
        "-n",
        type=int,
        default=int(1e8),
        help="Max size of the dataset (number of samples)",
    )
    parser.add_argument(

In [ ]:
from pathlib import Path
import shutil

main_path = Path("/content/drive/MyDrive/IMM-TSF/main.py")
backup_path = Path("/content/drive/MyDrive/IMM-TSF/main_backup_before_lazy_import_patch_v2.py")

if main_path.exists() and not backup_path.exists():
    shutil.copy(main_path, backup_path)
    print(f"Backup created: {backup_path}")

text = main_path.read_text(encoding="utf-8")

model_import_lines = [
    "from models.tPatchGNN import tPatchGNN",
    "from models.TimesNet import TimesNet",
    "from models.DLinear import DLinear",
    "from models.PatchTST import PatchTST",
    "from models.NeuralFlow import NeuralFlow",
    "from models.CRU import CRU",
    "from models.LatentODE import LatentODE  # Added LatentODE import",
    "from models.Informer import Informer",
    "from models.TimeMixer import TimeMixer",
    "from models.TimeLLM import TimeLLM",
    "from models.TTM import TTM",
]

for line in model_import_lines:
    text = text.replace(line, "# " + line)

if "def get_model_class(" not in text:
    insert_block = """

def get_model_class(model_name):
    if model_name == "tPatchGNN":
        from models.tPatchGNN import tPatchGNN
        return tPatchGNN
    elif model_name == "TimesNet":
        from models.TimesNet import TimesNet
        return TimesNet
    elif model_name == "DLinear":
        from models.DLinear import DLinear
        return DLinear
    elif model_name == "PatchTST":
        from models.PatchTST import PatchTST
        return PatchTST
    elif model_name == "NeuralFlow":
        from models.NeuralFlow import NeuralFlow
        return NeuralFlow
    elif model_name == "CRU":
        from models.CRU import CRU
        return CRU
    elif model_name == "LatentODE":
        from models.LatentODE import LatentODE
        return LatentODE
    elif model_name == "Informer":
        from models.Informer import Informer
        return Informer
    elif model_name == "TimeMixer":
        from models.TimeMixer import TimeMixer
        return TimeMixer
    elif model_name == "TimeLLM":
        from models.TimeLLM import TimeLLM
        return TimeLLM
    elif model_name == "TTM":
        from models.TTM import TTM
        return TTM
    else:
        raise ValueError(f"Unknown model: {model_name}")

"""
    marker = "def get_args_from_parser() -> argparse.Namespace:"
    text = text.replace(marker, insert_block + "\n" + marker)

main_path.write_text(text, encoding="utf-8")
print("Patched top-level model imports.")

Backup created: /content/drive/MyDrive/IMM-TSF/main_backup_before_lazy_import_patch_v2.py
Patched top-level model imports.

In [ ]:
!grep -n "args.model" /content/drive/MyDrive/IMM-TSF/main.py | head -30

882:    if args.model == "Informer":
886:    elif args.model == "DLinear":
888:    elif args.model == "PatchTST":
892:    elif args.model == "TimesNet":
899:    elif args.model == "TimeMixer":
907:    elif args.model == "TimeLLM":
914:    elif args.model == "TTM":
929:    elif args.model == "CRU":
936:    elif args.model == "LatentODE":
942:    elif args.model == "NeuralFlow":
953:    elif args.model == "tPatchGNN":
1028:    model_class = globals()[args.model]
1036:        log_path = "logs/{}_{}_{}.log".format(args.dataset, args.model, args.state)
1040:            args.model,

In [ ]:
from pathlib import Path

main_path = Path("/content/drive/MyDrive/IMM-TSF/main.py")
text = main_path.read_text(encoding="utf-8")

text = text.replace("model_class = globals()[args.model]", "model_class = get_model_class(args.model)")

main_path.write_text(text, encoding="utf-8")
print("Replaced globals()[args.model] with get_model_class(args.model)")

Replaced globals()[args.model] with get_model_class(args.model)

In [ ]:
!sed -n '1018,1034p' /content/drive/MyDrive/IMM-TSF/main.py

        #     args.max_length = context_window_size

    # Pass model name to parse_datasets to select the correct collate_fn
    data_obj = parse_datasets(args)

    ### Model setting ###
    args.C = data_obj["input_dim"]
    args.enc_in = args.C
    args.c_out = args.C
    args.input_len, args.pred_len = get_input_and_pred_len(data_obj)
    model_class = get_model_class(args.model)
    model = model_class(args).to(args.device)
    fusion = FusionModel(args).to(args.device) if args.enable_text else None

    ##################################################################

    if args.n < 12000:

In [ ]:
!sed -n '15,40p' /content/drive/MyDrive/IMM-TSF/main.py

from utils.tools import set_seed, print_formatted_dict, select_best_metrics
import lib.utils as utils
from lib.evaluation import compute_all_losses, evaluation

# from lib.parse_datasets_old import parse_datasets, get_input_and_pred_len

from lib.parse_datasets import parse_datasets, get_input_and_pred_len
# from models.tPatchGNN import tPatchGNN
# from models.TimesNet import TimesNet
# from models.DLinear import DLinear
# from models.PatchTST import PatchTST
# from models.NeuralFlow import NeuralFlow
# from models.CRU import CRU
# from models.LatentODE import LatentODE  # Added LatentODE import

# from models.MTGNN import MTGNN
# from models.Informer import Informer

# from models.TimeXer import TimeXer
# from models.TimeMixer import TimeMixer
# from models.TimeLLM import TimeLLM
# from models.TTM import TTM

from fusions.FusionModel import FusionModel
from fusions.load_llm import get_context_window_size

In [ ]:
!python /content/time_imm_repro_and_readmission_fixed.py run_repro \
  --repo_root /content/drive/MyDrive/IMM-TSF \
  --log_root /content/drive/MyDrive/IMM-TSF/run_logs_full \
  --results_root /content/drive/MyDrive/IMM-TSF/results_full \
  --datasets MIMIC \
  --models tPatchGNN \
  --seeds 42 \
  --run_limit 1 \
  --patch_empty_split_eval

[INFO] evaluation.py already patched.
[INFO] Launching 1 runs.
RUN: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --gnn_layer 1 --te_dim 10 --node_dim 10 --d_hidden 32
usage: main.py [-h] [--overwrite_args] [--state STATE] [--seed SEED]
               [--gpu GPU] [--dataset DATASET] [--data_root DATA_ROOT] [-n N]
               [--split_method {instance,sample}] [--enable_text]
               [--use_text_embeddings]
               [--time_unit {seconds,minutes,hours,days,weeks,custom}]
               [--history HISTORY] [--pred_window PRED_WINDOW]
               [--stride STRIDE] [-ps PATCH_SIZE] [--npatch NPATCH]
               [--patch_stride PATCH_STRIDE] [--model MODEL]
               [--outlayer OUTLAYER] [-hd HID_DIM] [-td TE_DIM] [-nd NODE_DIM]
               [--hop HOP] [--tf_layer TF_LAYER] [--nlayer NLAYER]
               [--top_k TOP_K] [--e_layers E_LAYERS] [--d_layers D_LAYERS]
               [--d_ff D_FF] [--d_model D_MODEL] [--n_heads N_HEADS]
               [--num_kernels NUM_KERNELS] [--embed EMBED] [--freq FREQ]
               [--moving_avg MOVING_AVG] [--factor FACTOR]
               [--activation ACTIVATION] [--distil]
               [--down_sampling_layers DOWN_SAMPLING_LAYERS]
               [--down_sampling_window DOWN_SAMPLING_WINDOW]
               [--down_sampling_method DOWN_SAMPLING_METHOD]
               [--decomp_method DECOMP_METHOD]
               [--channel_independence CHANNEL_INDEPENDENCE]
               [--use_norm USE_NORM] [--n_vars N_VARS] [--mode MODE]
               [--AP_levels AP_LEVELS] [--use_decoder] [--d_mode D_MODE]
               [--d_d_model D_D_MODEL] [--ts_vocab_size TS_VOCAB_SIZE]
               [--domain_des DOMAIN_DES] [--input_token_len INPUT_TOKEN_LEN]
               [--output_token_len OUTPUT_TOKEN_LEN]
               [--llm_model_timellm LLM_MODEL_TIMELLM]
               [--llm_layers_timellm LLM_LAYERS_TIMELLM]
               [--nf_latents NF_LATENTS] [--nf_rec_dims NF_REC_DIMS]
               [--nf_gru_units NF_GRU_UNITS]
               [--nf_hidden_layers NF_HIDDEN_LAYERS]
               [--nf_hidden_dim NF_HIDDEN_DIM]
               [--nf_flow_model {coupling,resnet,gru}]
               [--nf_flow_layers NF_FLOW_LAYERS] [--nf_time_net NF_TIME_NET]
               [--nf_time_hidden_dim NF_TIME_HIDDEN_DIM]
               [--nf_solver NF_SOLVER] [--nf_solver_step NF_SOLVER_STEP]
               [--nf_atol NF_ATOL] [--nf_rtol NF_RTOL] [--nf_odenet NF_ODENET]
               [--nf_activation NF_ACTIVATION]
               [--nf_final_activation NF_FINAL_ACTIVATION]
               [--nf_obsrv_std NF_OBSRV_STD]
               [--nf_weight_decay NF_WEIGHT_DECAY]
               [--nf_quantization NF_QUANTIZATION] [--nf_max_t NF_MAX_T]
               [--nf_mixing NF_MIXING]
               [--nf_gob_prep_hidden NF_GOB_PREP_HIDDEN]
               [--nf_gob_cov_hidden NF_GOB_COV_HIDDEN]
               [--nf_gob_p_hidden NF_GOB_P_HIDDEN]
               [--nf_invertible NF_INVERTIBLE] [--nf_components NF_COMPONENTS]
               [--nf_decoder_type NF_DECODER_TYPE] [--nf_rnn NF_RNN]
               [--nf_marks NF_MARKS] [--nf_density_model NF_DENSITY_MODEL]
               [--nf_extrap NF_EXTRAP] [--cru_lsd CRU_LSD]
               [--cru_hidden_units CRU_HIDDEN_UNITS]
               [--cru_enc_num_layers CRU_ENC_NUM_LAYERS]
               [--cru_dec_num_layers CRU_DEC_NUM_LAYERS]
               [--cru_num_layers CRU_NUM_LAYERS]
               [--cru_dropout_type {None,Zoneout,Variational}]
               [--cru_dropout_rate CRU_DROPOUT_RATE]
               [--cru_use_gate_hidden_states CRU_USE_GATE_HIDDEN_STATES]
               [--cru_use_ode_for_gru CRU_USE_ODE_FOR_GRU]
               [--cru_use_decay_gravity_gate CRU_USE_DECAY_GRAVITY_GATE]
               [--cru_use_gravity_gate CRU_USE_GRAVITY_GATE]
               [--cru_use_decay_input_gate CRU_USE_DECAY_INPUT_GATE]
               [--cru_use_input_gate CRU_USE_INPUT_GATE]
               [--cru_use_skip_connection CRU_USE_SKIP_CONNECTION]
               [--cru_solver {euler,rk4}] [--ts TS] [--grad_clip]
               [--ode_latents ODE_LATENTS] [--ode_units ODE_UNITS]
               [--ode_gen_layers ODE_GEN_LAYERS] [--ode_rec_dims ODE_REC_DIMS]
               [--ode_rec_layers ODE_REC_LAYERS]
               [--ode_gru_units ODE_GRU_UNITS] [--ode_poisson ODE_POISSON]
               [--ode_classif ODE_CLASSIF]
               [--ode_linear_classif ODE_LINEAR_CLASSIF]
               [--ode_z0_encoder {odernn,rnn}] [--ode_obsrv_std ODE_OBSRV_STD]
               [--ode_n_traj_samples ODE_N_TRAJ_SAMPLES]
               [--TTF_module {TTF_RecAvg,TTF_T2V_XAttn}]
               [--MMF_module {MMF_GR_Add,MMF_XAttn_Add}]
               [--llm_model_fusion LLM_MODEL_FUSION]
               [--llm_layers_fusion LLM_LAYERS_FUSION]
               [--max_length MAX_LENGTH] [--d_txt D_TXT]
               [--recency_sigma RECENCY_SIGMA]
               [--n_heads_fusion N_HEADS_FUSION] [--kappa KAPPA]
               [--epoch EPOCH] [--patience PATIENCE]
               [--early_stop_delta EARLY_STOP_DELTA] [--lr LR]
               [--w_decay W_DECAY] [-b BATCH_SIZE] [--dropout DROPOUT]
               [--use_amp] [--logmode LOGMODE] [--save SAVE] [--load LOAD]
main.py: error: unrecognized arguments: --gnn_layer 1 --d_hidden 32
[INFO] MIMIC__tPatchGNN__seed42__uni exit code: 2

In [ ]:
from pathlib import Path

script_path = Path("/content/time_imm_repro_and_readmission_fixed.py")
text = script_path.read_text(encoding="utf-8")

old = '"tPatchGNN": {"patch_size": 24, "nlayer": 1, "gnn_layer": 1, "te_dim": 10, "node_dim": 10, "d_hidden": 32},'
new = '"tPatchGNN": {"patch_size": 24, "nlayer": 1, "te_dim": 10, "node_dim": 10, "hid_dim": 32},'

text = text.replace(old, new)
script_path.write_text(text, encoding="utf-8")
print("Patched tPatchGNN args in wrapper script.")

Patched tPatchGNN args in wrapper script.

In [ ]:
!python /content/time_imm_repro_and_readmission_fixed.py run_repro \
  --repo_root /content/drive/MyDrive/IMM-TSF \
  --log_root /content/drive/MyDrive/IMM-TSF/run_logs_full \
  --results_root /content/drive/MyDrive/IMM-TSF/results_full \
  --datasets MIMIC \
  --models tPatchGNN \
  --seeds 42 \
  --run_limit 1 \
  --patch_empty_split_eval

[INFO] evaluation.py already patched.
[INFO] Launching 1 runs.
RUN: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --te_dim 10 --node_dim 10 --hid_dim 32
PID, device: 15965 cuda
Using dataset path: /content/drive/MyDrive/IMM-TSF/data/MIMIC
Traceback (most recent call last):
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets
    ds = ChunkedTimeSeriesDataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/IMM-TSF/lib/parse_datasets.py", line 81, in __init__
    d for d in os.listdir(proc_dir) if os.path.isdir(os.path.join(proc_dir, d))
               ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/IMM-TSF/data/MIMIC/processed'
[INFO] MIMIC__tPatchGNN__seed42__uni exit code: 1

In [ ]:
!python /content/time_imm_repro_and_readmission_fixed.py run_repro \
  --repo_root /content/drive/MyDrive/IMM-TSF \
  --log_root /content/drive/MyDrive/IMM-TSF/run_logs_full \
  --results_root /content/drive/MyDrive/IMM-TSF/results_full \
  --datasets ClusterTrace CESNET FNSPID GDELT \
  --models tPatchGNN \
  --seeds 42 \
  --run_limit 4 \
  --patch_empty_split_eval

[INFO] evaluation.py already patched.
[INFO] Launching 4 runs.
RUN: /usr/bin/python3 main.py --dataset ClusterTrace --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --te_dim 10 --node_dim 10 --hid_dim 32
/content/drive/MyDrive/IMM-TSF/main.py
2026-04-07 22:38:06
main.py --dataset ClusterTrace --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --te_dim 10 --node_dim 10 --hid_dim 32
Namespace(overwrite_args=False, state='def', seed=42, gpu='0', dataset='ClusterTrace', data_root='./data', n=100000000, split_method='instance', enable_text=False, use_text_embeddings=False, time_unit='days', history=24, pred_window=24, stride=24, patch_size=24, npatch=1, patch_stride=24, model='tPatchGNN', outlayer='Linear', hid_dim=32, te_dim=10, node_dim=10, hop=1, tf_layer=1, nlayer=1, top_k=5, e_layers=2, d_layers=1, d_ff=2048, d_model=512, n_heads=2, num_kernels=6, embed='timeF', freq='h', moving_avg=25, factor=1, activation='gelu', distil=True, down_sampling_layers=3, down_sampling_window=2, down_sampling_method='avg', decomp_method='moving_avg', channel_independence=1, use_norm=1, n_vars=7, mode='mix_channel', AP_levels=3, use_decoder=True, d_mode='common_channel', d_d_model=64, ts_vocab_size=1000, domain_des='The Electricity Transformer Temperature (ETT) is a crucial indicator in the electric power long-term deployment.', input_token_len=576, output_token_len=96, llm_model_timellm='GPT2', llm_layers_timellm=6, nf_latents=20, nf_rec_dims=40, nf_gru_units=32, nf_hidden_layers=3, nf_hidden_dim=32, nf_flow_model='coupling', nf_flow_layers=2, nf_time_net='TimeLinear', nf_time_hidden_dim=8, nf_solver='dopri5', nf_solver_step=0.05, nf_atol=0.0001, nf_rtol=0.001, nf_odenet='concat', nf_activation='Tanh', nf_final_activation='Identity', nf_obsrv_std=0.01, nf_weight_decay=0.0001, nf_quantization=0.0, nf_max_t=5.0, nf_mixing=0.0001, nf_gob_prep_hidden=10, nf_gob_cov_hidden=50, nf_gob_p_hidden=25, nf_invertible=1, nf_components=8, nf_decoder_type='continuous', nf_rnn='gru', nf_marks=0, nf_density_model='independent', nf_extrap=0, cru_lsd=32, cru_hidden_units=32, cru_enc_num_layers=1, cru_dec_num_layers=1, cru_num_layers=1, cru_dropout_type='None', cru_dropout_rate=0.0, cru_use_gate_hidden_states=True, cru_use_ode_for_gru=False, cru_use_decay_gravity_gate=True, cru_use_gravity_gate=True, cru_use_decay_input_gate=True, cru_use_input_gate=True, cru_use_skip_connection=True, cru_solver='euler', ts=0.3, grad_clip=False, ode_latents=20, ode_units=32, ode_gen_layers=1, ode_rec_dims=32, ode_rec_layers=1, ode_gru_units=32, ode_poisson=False, ode_classif=False, ode_linear_classif=False, ode_z0_encoder='odernn', ode_obsrv_std=0.01, ode_n_traj_samples=1, TTF_module='TTF_T2V_XAttn', MMF_module='MMF_XAttn_Add', llm_model_fusion='GPT2', llm_layers_fusion=6, max_length=1024, d_txt=768, recency_sigma=1.0, n_heads_fusion=1, kappa=0.5, epoch=20, patience=3, early_stop_delta=0.0001, lr=0.001, w_decay=0.01, batch_size=8, dropout=0.1, use_amp=False, logmode='a', save='experiments/', load=None, device=device(type='cuda'), PID=16343, C=11, enc_in=11, c_out=11, input_len=1, pred_len=1798)
PID, device: 16343 cuda
Using dataset path: /content/drive/MyDrive/IMM-TSF/data/ClusterTrace
Record 1c6afd5c227e89b8a29589f4: 1 chunks created, 0 dropped (0.00%)
Record 35fc40d2844c0b899c1ceb1e: 1 chunks created, 0 dropped (0.00%)
Record 7077ec572d50395cafcbcb7d: 1 chunks created, 0 dropped (0.00%)
+-------------------------------------+-----------------------------------------+
|                Metric               |                  Value                  |
+-------------------------------------+-----------------------------------------+
|             num_entities            |                    3                    |
|             num_features            |                    11                   |
|        num_unique_timestamps        |                  12615                  |
|           num_observations          |                  69001                  |
|  Feat observability entropy (norm)  |                  0.893                  |
| Temporal observation entropy (norm) |                  0.9753                 |
|               Mean IOI              |               0.0126 days               |
|               timespan              | 2000-01-12 02:06:22~2000-03-15 15:54:32 |
|               num_text              |                   688                   |
|     Text temporal entropy (norm)    |                  0.9971                 |
+-------------------------------------+-----------------------------------------+
After chunking & splitting (instance): train=1, val=1, test=1
Using Patch Collate Fn: patch_size=24, npatch=1, patch_stride=24
Scanning train split (1 batches)...
Scanning val split (1 batches)...
Scanning test split (1 batches)...

Training:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 0, Loss: 1.02802:   0%|          | 0/1 [00:01<?, ?it/s]
Epoch 0, Loss: 1.02802: 100%|██████████| 1/1 [00:01<00:00,  1.19s/it]
Epoch 0, Loss: 1.02802: 100%|██████████| 1/1 [00:01<00:00,  1.19s/it]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 42.91it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 62.29it/s]
- Epoch 000, ExpID 72502
Train - Loss (one batch): 1.02802
Val - Loss, MSE, MAE: 0.78710, 0.78710, 0.72178
Test - Best epoch, Loss, MSE, MAE: 0, 0.84210, 0.84210, 0.75084
Time spent: 1.23s

Training:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 1, Loss: 0.95967:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 1, Loss: 0.95967: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Epoch 1, Loss: 0.95967: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 71.45it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 66.30it/s]
- Epoch 001, ExpID 72502
Train - Loss (one batch): 0.95967
Val - Loss, MSE, MAE: 0.78251, 0.78251, 0.72390
Test - Best epoch, Loss, MSE, MAE: 1, 0.84434, 0.84434, 0.74559
Time spent: 0.14s

Training:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 2, Loss: 0.91883:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 2, Loss: 0.91883: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Epoch 2, Loss: 0.91883: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 71.12it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 66.98it/s]
- Epoch 002, ExpID 72502
Train - Loss (one batch): 0.91883
Val - Loss, MSE, MAE: 0.78164, 0.78164, 0.72592
Test - Best epoch, Loss, MSE, MAE: 2, 0.84733, 0.84733, 0.74088
Time spent: 0.14s

Training:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 3, Loss: 0.89423:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 3, Loss: 0.89423: 100%|██████████| 1/1 [00:00<00:00,  9.88it/s]
Epoch 3, Loss: 0.89423: 100%|██████████| 1/1 [00:00<00:00,  9.87it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 73.05it/s]
- Epoch 003, ExpID 72502
Train - Loss (one batch): 0.89423
Val - Loss, MSE, MAE: 0.78254, 0.78254, 0.72778
Test - Best epoch, Loss, MSE, MAE: 2, 0.84733, 0.84733, 0.74088
Time spent: 0.12s

Training:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 4, Loss: 0.87022:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 4, Loss: 0.87022: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Epoch 4, Loss: 0.87022: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 72.60it/s]
- Epoch 004, ExpID 72502
Train - Loss (one batch): 0.87022
Val - Loss, MSE, MAE: 0.78448, 0.78448, 0.72923
Test - Best epoch, Loss, MSE, MAE: 2, 0.84733, 0.84733, 0.74088
Time spent: 0.12s

Training:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 5, Loss: 0.84678:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 5, Loss: 0.84678: 100%|██████████| 1/1 [00:00<00:00,  9.90it/s]
Epoch 5, Loss: 0.84678: 100%|██████████| 1/1 [00:00<00:00,  9.88it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 70.16it/s]
- Epoch 005, ExpID 72502
Train - Loss (one batch): 0.84678
Val - Loss, MSE, MAE: 0.78822, 0.78822, 0.73078
Test - Best epoch, Loss, MSE, MAE: 2, 0.84733, 0.84733, 0.74088
Time spent: 0.12s
Exp has been early stopped!
loss: 0.8473267555236816
mse: 0.8473267555236816
mae: 0.7408758997917175
rmse: 0.920503556728363
mape: 0.5068988800048828
### Done ###
[INFO] ClusterTrace__tPatchGNN__seed42__uni exit code: 0
RUN: /usr/bin/python3 main.py --dataset ClusterTrace --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --te_dim 10 --node_dim 10 --hid_dim 32 --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion GPT2 --use_text_embeddings --enable_text
/content/drive/MyDrive/IMM-TSF/main.py
2026-04-07 22:38:19
main.py --dataset ClusterTrace --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --te_dim 10 --node_dim 10 --hid_dim 32 --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion GPT2 --use_text_embeddings --enable_text
Namespace(overwrite_args=False, state='def', seed=42, gpu='0', dataset='ClusterTrace', data_root='./data', n=100000000, split_method='instance', enable_text=True, use_text_embeddings=True, time_unit='days', history=24, pred_window=24, stride=24, patch_size=24, npatch=1, patch_stride=24, model='tPatchGNN', outlayer='Linear', hid_dim=32, te_dim=10, node_dim=10, hop=1, tf_layer=1, nlayer=1, top_k=5, e_layers=2, d_layers=1, d_ff=2048, d_model=512, n_heads=2, num_kernels=6, embed='timeF', freq='h', moving_avg=25, factor=1, activation='gelu', distil=True, down_sampling_layers=3, down_sampling_window=2, down_sampling_method='avg', decomp_method='moving_avg', channel_independence=1, use_norm=1, n_vars=7, mode='mix_channel', AP_levels=3, use_decoder=True, d_mode='common_channel', d_d_model=64, ts_vocab_size=1000, domain_des='The Electricity Transformer Temperature (ETT) is a crucial indicator in the electric power long-term deployment.', input_token_len=576, output_token_len=96, llm_model_timellm='GPT2', llm_layers_timellm=6, nf_latents=20, nf_rec_dims=40, nf_gru_units=32, nf_hidden_layers=3, nf_hidden_dim=32, nf_flow_model='coupling', nf_flow_layers=2, nf_time_net='TimeLinear', nf_time_hidden_dim=8, nf_solver='dopri5', nf_solver_step=0.05, nf_atol=0.0001, nf_rtol=0.001, nf_odenet='concat', nf_activation='Tanh', nf_final_activation='Identity', nf_obsrv_std=0.01, nf_weight_decay=0.0001, nf_quantization=0.0, nf_max_t=5.0, nf_mixing=0.0001, nf_gob_prep_hidden=10, nf_gob_cov_hidden=50, nf_gob_p_hidden=25, nf_invertible=1, nf_components=8, nf_decoder_type='continuous', nf_rnn='gru', nf_marks=0, nf_density_model='independent', nf_extrap=0, cru_lsd=32, cru_hidden_units=32, cru_enc_num_layers=1, cru_dec_num_layers=1, cru_num_layers=1, cru_dropout_type='None', cru_dropout_rate=0.0, cru_use_gate_hidden_states=True, cru_use_ode_for_gru=False, cru_use_decay_gravity_gate=True, cru_use_gravity_gate=True, cru_use_decay_input_gate=True, cru_use_input_gate=True, cru_use_skip_connection=True, cru_solver='euler', ts=0.3, grad_clip=False, ode_latents=20, ode_units=32, ode_gen_layers=1, ode_rec_dims=32, ode_rec_layers=1, ode_gru_units=32, ode_poisson=False, ode_classif=False, ode_linear_classif=False, ode_z0_encoder='odernn', ode_obsrv_std=0.01, ode_n_traj_samples=1, TTF_module='TTF_RecAvg', MMF_module='MMF_GR_Add', llm_model_fusion='GPT2', llm_layers_fusion=6, max_length=1024, d_txt=768, recency_sigma=1.0, n_heads_fusion=1, kappa=0.5, epoch=20, patience=3, early_stop_delta=0.0001, lr=0.001, w_decay=0.01, batch_size=8, dropout=0.1, use_amp=False, logmode='a', save='experiments/', load=None, device=device(type='cuda'), PID=16443, C=11, enc_in=11, c_out=11, input_len=1, pred_len=1798)
PID, device: 16443 cuda
Using dataset path: /content/drive/MyDrive/IMM-TSF/data/ClusterTrace
Record 1c6afd5c227e89b8a29589f4: 1 chunks created, 0 dropped (0.00%)
Record 35fc40d2844c0b899c1ceb1e: 1 chunks created, 0 dropped (0.00%)
Record 7077ec572d50395cafcbcb7d: 1 chunks created, 0 dropped (0.00%)
+-------------------------------------+-----------------------------------------+
|                Metric               |                  Value                  |
+-------------------------------------+-----------------------------------------+
|             num_entities            |                    3                    |
|             num_features            |                    11                   |
|        num_unique_timestamps        |                  12615                  |
|           num_observations          |                  69001                  |
|  Feat observability entropy (norm)  |                  0.893                  |
| Temporal observation entropy (norm) |                  0.9753                 |
|               Mean IOI              |               0.0126 days               |
|               timespan              | 2000-01-12 02:06:22~2000-03-15 15:54:32 |
|               num_text              |                   688                   |
|     Text temporal entropy (norm)    |                  0.9971                 |
+-------------------------------------+-----------------------------------------+
After chunking & splitting (instance): train=1, val=1, test=1
Using Patch Collate Fn: patch_size=24, npatch=1, patch_stride=24
Scanning train split (1 batches)...
Scanning val split (1 batches)...
Scanning test split (1 batches)...
Using TTF module: TTF_RecAvg
Using MMF module: MMF_GR_Add

Training:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 0, Loss: 1.47643:   0%|          | 0/1 [00:02<?, ?it/s]
Epoch 0, Loss: 1.47643: 100%|██████████| 1/1 [00:02<00:00,  2.99s/it]
Epoch 0, Loss: 1.47643: 100%|██████████| 1/1 [00:02<00:00,  2.99s/it]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 48.31it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 48.70it/s]
- Epoch 000, ExpID 90614
Train - Loss (one batch): 1.47643
Val - Loss, MSE, MAE: 0.84329, 0.84329, 0.73547
Test - Best epoch, Loss, MSE, MAE: 0, 0.92361, 0.92361, 0.78744
Time spent: 3.03s

Training:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 1, Loss: 1.20913:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 1, Loss: 1.20913: 100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
Epoch 1, Loss: 1.20913: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 55.93it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 52.44it/s]
- Epoch 001, ExpID 90614
Train - Loss (one batch): 1.20913
Val - Loss, MSE, MAE: 0.82215, 0.82215, 0.72981
Test - Best epoch, Loss, MSE, MAE: 1, 0.89768, 0.89768, 0.77823
Time spent: 0.19s

Training:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 2, Loss: 0.92545:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 2, Loss: 0.92545: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Epoch 2, Loss: 0.92545: 100%|██████████| 1/1 [00:00<00:00,  7.26it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 56.24it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 52.70it/s]
- Epoch 002, ExpID 90614
Train - Loss (one batch): 0.92545
Val - Loss, MSE, MAE: 0.79508, 0.79508, 0.72888
Test - Best epoch, Loss, MSE, MAE: 2, 0.86806, 0.86806, 0.75923
Time spent: 0.18s

Training:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 3, Loss: 0.85182:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 3, Loss: 0.85182: 100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
Epoch 3, Loss: 0.85182: 100%|██████████| 1/1 [00:00<00:00,  5.83it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 55.89it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 53.13it/s]
- Epoch 003, ExpID 90614
Train - Loss (one batch): 0.85182
Val - Loss, MSE, MAE: 0.78439, 0.78439, 0.72846
Test - Best epoch, Loss, MSE, MAE: 3, 0.85665, 0.85665, 0.74527
Time spent: 0.21s

Training:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 4, Loss: 0.82241:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 4, Loss: 0.82241: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Epoch 4, Loss: 0.82241: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 55.69it/s]
- Epoch 004, ExpID 90614
Train - Loss (one batch): 0.82241
Val - Loss, MSE, MAE: 0.78453, 0.78453, 0.72917
Test - Best epoch, Loss, MSE, MAE: 3, 0.85665, 0.85665, 0.74527
Time spent: 0.16s

Training:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 5, Loss: 0.84291:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 5, Loss: 0.84291: 100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
Epoch 5, Loss: 0.84291: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 54.04it/s]
- Epoch 005, ExpID 90614
Train - Loss (one batch): 0.84291
Val - Loss, MSE, MAE: 0.78647, 0.78647, 0.73012
Test - Best epoch, Loss, MSE, MAE: 3, 0.85665, 0.85665, 0.74527
Time spent: 0.16s

Training:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 6, Loss: 0.81800:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 6, Loss: 0.81800: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Epoch 6, Loss: 0.81800: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 56.04it/s]
- Epoch 006, ExpID 90614
Train - Loss (one batch): 0.81800
Val - Loss, MSE, MAE: 0.78929, 0.78929, 0.73113
Test - Best epoch, Loss, MSE, MAE: 3, 0.85665, 0.85665, 0.74527
Time spent: 0.16s
Exp has been early stopped!
loss: 0.8566524386405945
mse: 0.8566524386405945
mae: 0.7452725768089294
rmse: 0.9255552291870117
mape: 0.5870633721351624
### Done ###
[INFO] ClusterTrace__tPatchGNN__seed42__multi__TTF_RecAvg__MMF_GR_Add__GPT2 exit code: 0
RUN: /usr/bin/python3 main.py --dataset ClusterTrace --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --te_dim 10 --node_dim 10 --hid_dim 32 --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion BERT --use_text_embeddings --enable_text
PID, device: 16547 cuda
Using dataset path: /content/drive/MyDrive/IMM-TSF/data/ClusterTrace
Traceback (most recent call last):
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets
    ds = ChunkedTimeSeriesDataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/IMM-TSF/lib/parse_datasets.py", line 149, in __init__
    raise FileNotFoundError(f"Missing text embeddings file: {path}")
FileNotFoundError: Missing text embeddings file: /content/drive/MyDrive/IMM-TSF/data/ClusterTrace/processed/1c6afd5c227e89b8a29589f4/text_embeddings_model=BERT_layers=6_maxlen=512.pt
[INFO] ClusterTrace__tPatchGNN__seed42__multi__TTF_RecAvg__MMF_GR_Add__BERT exit code: 1
RUN: /usr/bin/python3 main.py --dataset ClusterTrace --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --te_dim 10 --node_dim 10 --hid_dim 32 --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion Llama --use_text_embeddings --enable_text
PID, device: 16609 cuda
Using dataset path: /content/drive/MyDrive/IMM-TSF/data/ClusterTrace
Traceback (most recent call last):
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^

In [ ]:
!mkdir -p /content/drive/MyDrive/time_imm_project/IMM-TSF/data
!rm -rf /content/drive/MyDrive/time_imm_project/IMM-TSF/data/MIMIC
!ln -s /content/drive/MyDrive/time_imm_project/Time-IMM-master/data/MIMIC \
      /content/drive/MyDrive/time_imm_project/IMM-TSF/data/MIMIC

In [ ]:
!ls -l /content/drive/MyDrive/time_imm_project/IMM-TSF/data
!ls -l /content/drive/MyDrive/time_imm_project/IMM-TSF/data/MIMIC
!ls -l /content/drive/MyDrive/time_imm_project/IMM-TSF/data/MIMIC/processed | head

total 0
lrw------- 1 root root 0 Apr  7 22:43 MIMIC -> /content/drive/MyDrive/time_imm_project/Time-IMM-master/data/MIMIC
lrw------- 1 root root 0 Apr  7 22:43 /content/drive/MyDrive/time_imm_project/IMM-TSF/data/MIMIC -> /content/drive/MyDrive/time_imm_project/Time-IMM-master/data/MIMIC
total 217
drwx------ 2 root root  4096 Apr  1 22:09 20079585
drwx------ 2 root root  4096 Apr  1 22:09 20104023
drwx------ 2 root root  4096 Apr  1 22:09 20698316
drwx------ 2 root root  4096 Apr  1 22:09 21386394
drwx------ 2 root root  4096 Apr  1 22:09 21986375
drwx------ 2 root root  4096 Apr  1 22:09 22320526
drwx------ 2 root root  4096 Apr  1 22:09 23365149
drwx------ 2 root root  4096 Apr  1 22:09 23996524
drwx------ 2 root root  4096 Apr  1 22:09 24325350

In [ ]:
!python /content/time_imm_repro_and_readmission_fixed.py run_repro \
  --repo_root /content/drive/MyDrive/time_imm_project/IMM-TSF \
  --log_root /content/drive/MyDrive/time_imm_project/IMM-TSF/run_logs_full \
  --results_root /content/drive/MyDrive/time_imm_project/IMM-TSF/results_full \
  --datasets MIMIC \
  --models tPatchGNN \
  --seeds 42 \
  --run_limit 1 \
  --patch_empty_split_eval

[INFO] Patched evaluation.py for empty validation/test splits.
[INFO] Launching 1 runs.
RUN: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --te_dim 10 --node_dim 10 --hid_dim 32
Traceback (most recent call last):
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 28, in <module>
    from models.CRU import CRU
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/models/CRU.py", line 5, in <module>
    from lib.cru_components.cru_models import Physionet_USHCN # Using this as the general CRU model structure
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/cru_components/cru_models.py", line 21, in <module>
    from lib.cru_components.CRU_Module import CRU_Module
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/cru_components/CRU_Module.py", line 42, in <module>
    from lib.cru_components.CRULayer import CRULayer
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/cru_components/CRULayer.py", line 22, in <module>
    from lib.cru_components.CRUCell import RKNCell, CRUCell
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/cru_components/CRUCell.py", line 23, in <module>
    import geotorch
ModuleNotFoundError: No module named 'geotorch'
[INFO] MIMIC__tPatchGNN__seed42__uni exit code: 1

In [ ]:
!/usr/bin/python3 -m pip install -q geotorch reformer-pytorch stribor torchtyping typeguard

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.8/54.8 kB 2.7 MB/s eta 0:00:00

In [ ]:
!rm -rf /content/drive/MyDrive/time_imm_project/IMM-TSF/data
!ln -s /content/drive/MyDrive/time_imm_project/Time-IMM-master/data \
      /content/drive/MyDrive/time_imm_project/IMM-TSF/data
!ls -l /content/drive/MyDrive/time_imm_project/IMM-TSF
!ls -l /content/drive/MyDrive/time_imm_project/IMM-TSF/data/MIMIC

total 90
-rw------- 1 root root  5178 Apr  1 20:03 compute_text_embeddings.py
lrw------- 1 root root     0 Apr  7 22:46 data -> /content/drive/MyDrive/time_imm_project/Time-IMM-master/data
drwx------ 2 root root  4096 Apr  1 22:09 fusions
-rw------- 1 root root    47 Mar 29 15:00 go.sh
drwx------ 3 root root  4096 Apr  1 22:09 layers
drwx------ 6 root root  4096 Apr  7 22:43 lib
-rw------- 1 root root  1073 Mar 29 15:00 LICENSE
-rw------- 1 root root  5953 Mar 29 15:00 main_all.py
-rw------- 1 root root    51 Mar 29 15:00 main_all.sh
-rw------- 1 root root 41541 Mar 29 15:00 main.py
drwx------ 4 root root  4096 Apr  1 22:09 models
-rw------- 1 root root  5747 Mar 29 15:00 README.md
-rw------- 1 root root   196 Mar 29 15:00 requirements.txt
drwx------ 2 root root  4096 Apr  7 22:43 results_full
drwx------ 2 root root  4096 Apr  7 22:44 run_logs_full
drwx------ 3 root root  4096 Apr  1 22:09 utils
total 12219686
drwx------  2 root root        4096 Apr  1 22:09 mimiciv
-rw-------  1 root root 10551747784 Mar 30 10:32 mimic-iv-3.1.zip
drwx------  2 root root        4096 Apr  1 22:09 mimic-iv-note
-rw-------  1 root root  1960856617 Mar 29 22:44 mimic-iv-note-deidentified-free-text-clinical-notes-2.2.zip
-rw-------  1 root root      335985 Apr  1 20:35 mimic_preprocess.ipynb
drwx------ 22 root root        4096 Apr  1 22:09 processed
drwx------  2 root root        4096 Apr  1 22:09 raw

In [ ]:
from pathlib import Path
import shutil

main_path = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py")
backup_path = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF/main_backup_before_lazy_import_patch.py")

if main_path.exists() and not backup_path.exists():
    shutil.copy(main_path, backup_path)

text = main_path.read_text(encoding="utf-8")

model_import_lines = [
    "from models.tPatchGNN import tPatchGNN",
    "from models.TimesNet import TimesNet",
    "from models.DLinear import DLinear",
    "from models.PatchTST import PatchTST",
    "from models.NeuralFlow import NeuralFlow",
    "from models.CRU import CRU",
    "from models.LatentODE import LatentODE  # Added LatentODE import",
    "from models.Informer import Informer",
    "from models.TimeMixer import TimeMixer",
    "from models.TimeLLM import TimeLLM",
    "from models.TTM import TTM",
]

for line in model_import_lines:
    text = text.replace(line, "# " + line)

if "def get_model_class(" not in text:
    insert_block = """

def get_model_class(model_name):
    if model_name == "tPatchGNN":
        from models.tPatchGNN import tPatchGNN
        return tPatchGNN
    elif model_name == "TimesNet":
        from models.TimesNet import TimesNet
        return TimesNet
    elif model_name == "DLinear":
        from models.DLinear import DLinear
        return DLinear
    elif model_name == "PatchTST":
        from models.PatchTST import PatchTST
        return PatchTST
    elif model_name == "NeuralFlow":
        from models.NeuralFlow import NeuralFlow
        return NeuralFlow
    elif model_name == "CRU":
        from models.CRU import CRU
        return CRU
    elif model_name == "LatentODE":
        from models.LatentODE import LatentODE
        return LatentODE
    elif model_name == "Informer":
        from models.Informer import Informer
        return Informer
    elif model_name == "TimeMixer":
        from models.TimeMixer import TimeMixer
        return TimeMixer
    elif model_name == "TimeLLM":
        from models.TimeLLM import TimeLLM
        return TimeLLM
    elif model_name == "TTM":
        from models.TTM import TTM
        return TTM
    else:
        raise ValueError(f"Unknown model: {model_name}")

"""
    marker = "def get_args_from_parser() -> argparse.Namespace:"
    text = text.replace(marker, insert_block + "\n" + marker)

text = text.replace("model_class = globals()[args.model]", "model_class = get_model_class(args.model)")

main_path.write_text(text, encoding="utf-8")
print("Patched correct main.py")

Patched correct main.py

In [ ]:
!sed -n '15,40p' /content/drive/MyDrive/time_imm_project/IMM-TSF/main.py
!grep -n "model_class =" /content/drive/MyDrive/time_imm_project/IMM-TSF/main.py

from utils.tools import set_seed, print_formatted_dict, select_best_metrics
import lib.utils as utils
from lib.evaluation import compute_all_losses, evaluation

# from lib.parse_datasets_old import parse_datasets, get_input_and_pred_len

from lib.parse_datasets import parse_datasets, get_input_and_pred_len
# from models.tPatchGNN import tPatchGNN
# from models.TimesNet import TimesNet
# from models.DLinear import DLinear
# from models.PatchTST import PatchTST
# from models.NeuralFlow import NeuralFlow
# from models.CRU import CRU
# from models.LatentODE import LatentODE  # Added LatentODE import

# from models.MTGNN import MTGNN
# from models.Informer import Informer

# from models.TimeXer import TimeXer
# from models.TimeMixer import TimeMixer
# from models.TimeLLM import TimeLLM
# from models.TTM import TTM

from fusions.FusionModel import FusionModel
from fusions.load_llm import get_context_window_size
1028:    model_class = get_model_class(args.model)

In [ ]:
!python /content/time_imm_repro_and_readmission_fixed.py run_repro \
  --repo_root /content/drive/MyDrive/time_imm_project/IMM-TSF \
  --log_root /content/drive/MyDrive/time_imm_project/IMM-TSF/run_logs_full \
  --results_root /content/drive/MyDrive/time_imm_project/IMM-TSF/results_full \
  --datasets MIMIC \
  --models tPatchGNN \
  --seeds 42 \
  --run_limit 1 \
  --patch_empty_split_eval

[INFO] evaluation.py already patched.
[INFO] Launching 1 runs.
RUN: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --te_dim 10 --node_dim 10 --hid_dim 32
/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py
2026-04-07 22:47:44
main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --te_dim 10 --node_dim 10 --hid_dim 32
Namespace(overwrite_args=False, state='def', seed=42, gpu='0', dataset='MIMIC', data_root='./data', n=100000000, split_method='instance', enable_text=False, use_text_embeddings=False, time_unit='days', history=24, pred_window=24, stride=24, patch_size=24, npatch=1, patch_stride=24, model='tPatchGNN', outlayer='Linear', hid_dim=32, te_dim=10, node_dim=10, hop=1, tf_layer=1, nlayer=1, top_k=5, e_layers=2, d_layers=1, d_ff=2048, d_model=512, n_heads=2, num_kernels=6, embed='timeF', freq='h', moving_avg=25, factor=1, activation='gelu', distil=True, down_sampling_layers=3, down_sampling_window=2, down_sampling_method='avg', decomp_method='moving_avg', channel_independence=1, use_norm=1, n_vars=7, mode='mix_channel', AP_levels=3, use_decoder=True, d_mode='common_channel', d_d_model=64, ts_vocab_size=1000, domain_des='The Electricity Transformer Temperature (ETT) is a crucial indicator in the electric power long-term deployment.', input_token_len=576, output_token_len=96, llm_model_timellm='GPT2', llm_layers_timellm=6, nf_latents=20, nf_rec_dims=40, nf_gru_units=32, nf_hidden_layers=3, nf_hidden_dim=32, nf_flow_model='coupling', nf_flow_layers=2, nf_time_net='TimeLinear', nf_time_hidden_dim=8, nf_solver='dopri5', nf_solver_step=0.05, nf_atol=0.0001, nf_rtol=0.001, nf_odenet='concat', nf_activation='Tanh', nf_final_activation='Identity', nf_obsrv_std=0.01, nf_weight_decay=0.0001, nf_quantization=0.0, nf_max_t=5.0, nf_mixing=0.0001, nf_gob_prep_hidden=10, nf_gob_cov_hidden=50, nf_gob_p_hidden=25, nf_invertible=1, nf_components=8, nf_decoder_type='continuous', nf_rnn='gru', nf_marks=0, nf_density_model='independent', nf_extrap=0, cru_lsd=32, cru_hidden_units=32, cru_enc_num_layers=1, cru_dec_num_layers=1, cru_num_layers=1, cru_dropout_type='None', cru_dropout_rate=0.0, cru_use_gate_hidden_states=True, cru_use_ode_for_gru=False, cru_use_decay_gravity_gate=True, cru_use_gravity_gate=True, cru_use_decay_input_gate=True, cru_use_input_gate=True, cru_use_skip_connection=True, cru_solver='euler', ts=0.3, grad_clip=False, ode_latents=20, ode_units=32, ode_gen_layers=1, ode_rec_dims=32, ode_rec_layers=1, ode_gru_units=32, ode_poisson=False, ode_classif=False, ode_linear_classif=False, ode_z0_encoder='odernn', ode_obsrv_std=0.01, ode_n_traj_samples=1, TTF_module='TTF_T2V_XAttn', MMF_module='MMF_XAttn_Add', llm_model_fusion='GPT2', llm_layers_fusion=6, max_length=1024, d_txt=768, recency_sigma=1.0, n_heads_fusion=1, kappa=0.5, epoch=20, patience=3, early_stop_delta=0.0001, lr=0.001, w_decay=0.01, batch_size=8, dropout=0.1, use_amp=False, logmode='a', save='experiments/', load=None, device=device(type='cuda'), PID=18931, C=30, enc_in=30, c_out=30, input_len=1, pred_len=5743)
PID, device: 18931 cuda
Using dataset path: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/MIMIC
Record 20079585: 2 chunks created, 0 dropped (0.00%)
Record 20104023: 1 chunks created, 0 dropped (0.00%)
Record 20698316: 1 chunks created, 0 dropped (0.00%)
Record 21386394: 1 chunks created, 0 dropped (0.00%)
Record 21986375: 1 chunks created, 0 dropped (0.00%)
Record 22320526: 1 chunks created, 0 dropped (0.00%)
Record 23365149: 9 chunks created, 0 dropped (0.00%)
Record 23996524: 1 chunks created, 0 dropped (0.00%)
Record 24325350: 1 chunks created, 0 dropped (0.00%)
Record 24443695: 1 chunks created, 0 dropped (0.00%)
Record 25443707: 1 chunks created, 0 dropped (0.00%)
Record 25447858: 1 chunks created, 0 dropped (0.00%)
Record 25777608: 3 chunks created, 0 dropped (0.00%)
Record 26691544: 1 chunks created, 0 dropped (0.00%)
Record 27321750: 2 chunks created, 0 dropped (0.00%)
Record 27488620: 1 chunks created, 0 dropped (0.00%)
Record 27658935: 1 chunks created, 0 dropped (0.00%)
Record 28113079: 2 chunks created, 0 dropped (0.00%)
Record 29065979: 1 chunks created, 0 dropped (0.00%)
Record 29281474: 3 chunks created, 0 dropped (0.00%)
+-------------------------------------+-----------------------------------------+
|                Metric               |                  Value                  |
+-------------------------------------+-----------------------------------------+
|             num_entities            |                    20                   |
|             num_features            |                    30                   |
|        num_unique_timestamps        |                  91098                  |
|           num_observations          |                  219949                 |
|  Feat observability entropy (norm)  |                  0.8461                 |
| Temporal observation entropy (norm) |                  0.6556                 |
|               Mean IOI              |               0.0101 days               |
|               timespan              | 2000-01-01 00:00:00~2000-09-05 10:42:00 |
|               num_text              |                   1593                  |
|     Text temporal entropy (norm)    |                  0.6758                 |
+-------------------------------------+-----------------------------------------+
After chunking & splitting (instance): train=16, val=13, test=6
Using Patch Collate Fn: patch_size=24, npatch=1, patch_stride=24
Scanning train split (2 batches)...
Scanning val split (2 batches)...
Scanning test split (1 batches)...

Training:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 0, Loss: 1.16872:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 0, Loss: 1.16872:  50%|█████     | 1/2 [00:00<00:00,  1.23it/s]
Epoch 0, Loss: 0.97016:  50%|█████     | 1/2 [00:01<00:00,  1.23it/s]
Epoch 0, Loss: 0.97016: 100%|██████████| 2/2 [00:01<00:00,  1.68it/s]
Epoch 0, Loss: 0.97016: 100%|██████████| 2/2 [00:01<00:00,  1.59it/s]

  0%|          | 0/2 [00:00<?, ?it/s]
100%|██████████| 2/2 [00:00<00:00, 14.32it/s]
100%|██████████| 2/2 [00:00<00:00, 14.30it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
- Epoch 000, ExpID 29524
Train - Loss (one batch): 0.97016
Val - Loss, MSE, MAE: 0.95344, 0.95344, 0.70956
Test - Best epoch, Loss, MSE, MAE: 0, 1.02891, 1.02891, 0.69192
Time spent: 1.51s

Training:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 1, Loss: 1.10314:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 1, Loss: 1.10314:  50%|█████     | 1/2 [00:00<00:00,  4.24it/s]
Epoch 1, Loss: 1.63412:  50%|█████     | 1/2 [00:00<00:00,  4.24it/s]
Epoch 1, Loss: 1.63412: 100%|██████████| 2/2 [00:00<00:00,  2.88it/s]
Epoch 1, Loss: 1.63412: 100%|██████████| 2/2 [00:00<00:00,  3.03it/s]

  0%|          | 0/2 [00:00<?, ?it/s]
100%|██████████| 2/2 [00:00<00:00, 14.58it/s]
100%|██████████| 2/2 [00:00<00:00, 14.55it/s]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
- Epoch 001, ExpID 29524
Train - Loss (one batch): 1.63412
Val - Loss, MSE, MAE: 0.95265, 0.95265, 0.71539
Test - Best epoch, Loss, MSE, MAE: 1, 1.02841, 1.02841, 0.69969
Time spent: 0.91s

Training:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 2, Loss: 1.33538:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 2, Loss: 1.33538:  50%|█████     | 1/2 [00:00<00:00,  2.44it/s]
Epoch 2, Loss: 1.03590:  50%|█████     | 1/2 [00:00<00:00,  2.44it/s]
Epoch 2, Loss: 1.03590: 100%|██████████| 2/2 [00:00<00:00,  2.85it/s]
Epoch 2, Loss: 1.03590: 100%|██████████| 2/2 [00:00<00:00,  2.78it/s]

  0%|          | 0/2 [00:00<?, ?it/s]
100%|██████████| 2/2 [00:00<00:00, 14.58it/s]
100%|██████████| 2/2 [00:00<00:00, 14.56it/s]
- Epoch 002, ExpID 29524
Train - Loss (one batch): 1.03590
Val - Loss, MSE, MAE: 0.95292, 0.95292, 0.71830
Test - Best epoch, Loss, MSE, MAE: 1, 1.02841, 1.02841, 0.69969
Time spent: 0.86s

Training:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 3, Loss: 1.61931:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 3, Loss: 1.61931:  50%|█████     | 1/2 [00:00<00:00,  2.99it/s]
Epoch 3, Loss: 1.11529:  50%|█████     | 1/2 [00:00<00:00,  2.99it/s]
Epoch 3, Loss: 1.11529: 100%|██████████| 2/2 [00:00<00:00,  2.49it/s]
Epoch 3, Loss: 1.11529: 100%|██████████| 2/2 [00:00<00:00,  2.55it/s]

  0%|          | 0/2 [00:00<?, ?it/s]
100%|██████████| 2/2 [00:00<00:00, 14.58it/s]
100%|██████████| 2/2 [00:00<00:00, 14.56it/s]
- Epoch 003, ExpID 29524
Train - Loss (one batch): 1.11529
Val - Loss, MSE, MAE: 0.95351, 0.95351, 0.72015
Test - Best epoch, Loss, MSE, MAE: 1, 1.02841, 1.02841, 0.69969
Time spent: 0.92s

Training:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 4, Loss: 0.99168:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 4, Loss: 0.99168:  50%|█████     | 1/2 [00:00<00:00,  2.18it/s]
Epoch 4, Loss: 0.96241:  50%|█████     | 1/2 [00:00<00:00,  2.18it/s]
Epoch 4, Loss: 0.96241: 100%|██████████| 2/2 [00:00<00:00,  2.69it/s]
Epoch 4, Loss: 0.96241: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

  0%|          | 0/2 [00:00<?, ?it/s]
100%|██████████| 2/2 [00:00<00:00, 14.56it/s]
100%|██████████| 2/2 [00:00<00:00, 14.53it/s]
- Epoch 004, ExpID 29524
Train - Loss (one batch): 0.96241
Val - Loss, MSE, MAE: 0.95499, 0.95499, 0.72260
Test - Best epoch, Loss, MSE, MAE: 1, 1.02841, 1.02841, 0.69969
Time spent: 0.91s
Exp has been early stopped!
loss: 1.028408169746399
mse: 1.028408169746399
mae: 0.6996890306472778
rmse: 1.0141046047210693
mape: -0.16374395787715912
### Done ###
[INFO] MIMIC__tPatchGNN__seed42__uni exit code: 0

In [ ]:
from pathlib import Path
import subprocess
import itertools
import pandas as pd
from datetime import datetime

REPO_ROOT = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF")
LOG_ROOT = REPO_ROOT / "run_logs_full"
RESULTS_ROOT = REPO_ROOT / "results_full"

LOG_ROOT.mkdir(parents=True, exist_ok=True)
RESULTS_ROOT.mkdir(parents=True, exist_ok=True)

DATASETS = ["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"]
MODELS = [
    "Informer",
    "DLinear",
    "PatchTST",
    "TimesNet",
    "TimeMixer",
    "TimeLLM",
    "TTM",
    "CRU",
    "LatentODE",
    "NeuralFlow",
    "tPatchGNN",
]
ENCODERS = ["GPT2", "BERT", "Llama", "DeepSeek"]
TTF_MODULES = ["TTF_RecAvg", "TTF_T2V_XAttn"]
MMF_MODULES = ["MMF_GR_Add", "MMF_XAttn_Add"]
SEEDS = [42]

RUN_UNIMODAL = True
RUN_MULTIMODAL = True

# Start smaller per session. Increase later.
MAX_RUNS_THIS_SESSION = 20
SKIP_COMPLETED = True
FORCE_RERUN_FAILED = False

BATCH_SIZE = 8
EPOCHS = 20
SPLIT_METHOD = "instance"

def model_overrides(model: str, dataset: str) -> dict:
    overrides = {}

    if model == "tPatchGNN":
        overrides.update({
            "patch_size": 24,
            "nlayer": 1,
            "te_dim": 10,
            "node_dim": 10,
            "hid_dim": 32,
        })
        if dataset == "CESNET":
            overrides.update({
                "history": 12,
                "pred_window": 6,
                "stride": 6,
                "patch_size": 6,
                "patch_stride": 6,
                "npatch": 2,
            })

    return overrides

def run_name(dataset, model, seed, modality, ttf=None, mmf=None, enc=None):
    parts = [dataset, model, f"seed{seed}", modality]
    if modality == "multi":
        parts.extend([ttf, mmf, enc])
    return "__".join(parts)

def build_cmd(dataset, model, seed, modality, ttf=None, mmf=None, enc=None):
    cmd = [
        "/usr/bin/python3", "main.py",
        "--dataset", dataset,
        "--model", model,
        "--split_method", SPLIT_METHOD,
        "-b", str(BATCH_SIZE),
        "--epoch", str(EPOCHS),
        "--seed", str(seed),
    ]

    ov = model_overrides(model, dataset)
    for k, v in ov.items():
        cmd.extend([f"--{k}", str(v)])

    if modality == "multi":
        cmd.extend([
            "--TTF_module", ttf,
            "--MMF_module", mmf,
            "--llm_model_fusion", enc,
            "--use_text_embeddings",
            "--enable_text",
        ])

    return cmd

def log_contains_done(log_path: Path) -> bool:
    if not log_path.exists():
        return False
    txt = log_path.read_text(encoding="utf-8", errors="ignore")
    return ("### Done ###" in txt) or ("mse:" in txt and "mae:" in txt)

def log_contains_failure(log_path: Path) -> bool:
    if not log_path.exists():
        return False
    txt = log_path.read_text(encoding="utf-8", errors="ignore")
    fail_markers = [
        "Traceback",
        "ModuleNotFoundError",
        "RuntimeError",
        "FileNotFoundError",
        "error:",
    ]
    return any(m in txt for m in fail_markers)

jobs = []
for dataset, model, seed in itertools.product(DATASETS, MODELS, SEEDS):
    if RUN_UNIMODAL:
        jobs.append({
            "dataset": dataset, "model": model, "seed": seed,
            "modality": "uni", "ttf": None, "mmf": None, "encoder": None
        })
    if RUN_MULTIMODAL:
        for ttf, mmf, enc in itertools.product(TTF_MODULES, MMF_MODULES, ENCODERS):
            jobs.append({
                "dataset": dataset, "model": model, "seed": seed,
                "modality": "multi", "ttf": ttf, "mmf": mmf, "encoder": enc
            })

manifest = pd.DataFrame(jobs)
manifest_path = RESULTS_ROOT / "partA_manifest_full.csv"
manifest.to_csv(manifest_path, index=False)

print("Total jobs in full Part A grid:", len(jobs))
print("Manifest saved to:", manifest_path)
manifest.head()

Total jobs in full Part A grid: 935
Manifest saved to: /content/drive/MyDrive/time_imm_project/IMM-TSF/results_full/partA_manifest_full.csv

  dataset     model  seed modality         ttf         mmf   encoder
0   GDELT  Informer    42      uni        None        None      None
1   GDELT  Informer    42    multi  TTF_RecAvg  MMF_GR_Add      GPT2
2   GDELT  Informer    42    multi  TTF_RecAvg  MMF_GR_Add      BERT
3   GDELT  Informer    42    multi  TTF_RecAvg  MMF_GR_Add     Llama
4   GDELT  Informer    42    multi  TTF_RecAvg  MMF_GR_Add  DeepSeek

In [ ]:
def run_embed(llm_name: str):
    print(f"\n=== Generating embeddings for {llm_name} ===")
    cmd = ["/usr/bin/python3", "compute_text_embeddings.py", "--llm_model", llm_name]
    return subprocess.run(cmd, cwd=str(REPO_ROOT), text=True).returncode

for llm in ENCODERS:
    code = run_embed(llm)
    print(f"{llm} embedding job exit code: {code}")

=== Generating embeddings for GPT2 ===
GPT2 embedding job exit code: 1

=== Generating embeddings for BERT ===
BERT embedding job exit code: 1

=== Generating embeddings for Llama ===
Llama embedding job exit code: 1

=== Generating embeddings for DeepSeek ===
DeepSeek embedding job exit code: 1

In [ ]:
status_rows = []
status_path = RESULTS_ROOT / "partA_run_status.csv"

to_run = []
for j in jobs:
    rn = run_name(j["dataset"], j["model"], j["seed"], j["modality"], j["ttf"], j["mmf"], j["encoder"])
    log_path = LOG_ROOT / f"{rn}.log"

    if SKIP_COMPLETED and log_contains_done(log_path):
        continue
    if (not FORCE_RERUN_FAILED) and log_contains_failure(log_path):
        continue

    to_run.append(j)

if MAX_RUNS_THIS_SESSION is not None:
    to_run = to_run[:MAX_RUNS_THIS_SESSION]

print(f"Jobs queued this session: {len(to_run)}")

for idx, j in enumerate(to_run, 1):
    rn = run_name(j["dataset"], j["model"], j["seed"], j["modality"], j["ttf"], j["mmf"], j["encoder"])
    log_path = LOG_ROOT / f"{rn}.log"
    cmd = build_cmd(j["dataset"], j["model"], j["seed"], j["modality"], j["ttf"], j["mmf"], j["encoder"])

    print("\n" + "="*100)
    print(f"[{idx}/{len(to_run)}] {rn}")
    print("CMD:", " ".join(cmd))
    print("="*100)

    with open(log_path, "w", encoding="utf-8") as f:
        proc = subprocess.Popen(
            cmd,
            cwd=str(REPO_ROOT),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        for line in proc.stdout:
            print(line, end="")
            f.write(line)
        return_code = proc.wait()

    status_rows.append({
        "timestamp": datetime.now().isoformat(),
        "run_name": rn,
        "dataset": j["dataset"],
        "model": j["model"],
        "seed": j["seed"],
        "modality": j["modality"],
        "ttf_module": j["ttf"],
        "mmf_module": j["mmf"],
        "text_encoder": j["encoder"],
        "return_code": return_code,
        "log_file": str(log_path),
    })

    pd.DataFrame(status_rows).to_csv(status_path, index=False)
    print(f"[INFO] return code = {return_code}")

print(f"\nSaved session status to: {status_path}")

Jobs queued this session: 20

====================================================================================================
[1/20] GDELT__Informer__seed42__uni
CMD: /usr/bin/python3 main.py --dataset GDELT --model Informer --split_method instance -b 8 --epoch 20 --seed 42
====================================================================================================
/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py
2026-04-07 22:59:03
main.py --dataset GDELT --model Informer --split_method instance -b 8 --epoch 20 --seed 42
Namespace(overwrite_args=False, state='def', seed=42, gpu='0', dataset='GDELT', data_root='./data', n=100000000, split_method='instance', enable_text=False, use_text_embeddings=False, time_unit='days', history=24, pred_window=24, stride=24, patch_size=24, npatch=1, patch_stride=None, model='Informer', outlayer='Linear', hid_dim=64, te_dim=10, node_dim=10, hop=1, tf_layer=1, nlayer=1, top_k=5, e_layers=2, d_layers=1, d_ff=2048, d_model=512, n_heads=2, num_kernels=6, embed='timeF', freq='h', moving_avg=25, factor=1, activation='gelu', distil=True, down_sampling_layers=3, down_sampling_window=2, down_sampling_method='avg', decomp_method='moving_avg', channel_independence=1, use_norm=1, n_vars=7, mode='mix_channel', AP_levels=3, use_decoder=True, d_mode='common_channel', d_d_model=64, ts_vocab_size=1000, domain_des='The Electricity Transformer Temperature (ETT) is a crucial indicator in the electric power long-term deployment.', input_token_len=576, output_token_len=96, llm_model_timellm='GPT2', llm_layers_timellm=6, nf_latents=20, nf_rec_dims=40, nf_gru_units=32, nf_hidden_layers=3, nf_hidden_dim=32, nf_flow_model='coupling', nf_flow_layers=2, nf_time_net='TimeLinear', nf_time_hidden_dim=8, nf_solver='dopri5', nf_solver_step=0.05, nf_atol=0.0001, nf_rtol=0.001, nf_odenet='concat', nf_activation='Tanh', nf_final_activation='Identity', nf_obsrv_std=0.01, nf_weight_decay=0.0001, nf_quantization=0.0, nf_max_t=5.0, nf_mixing=0.0001, nf_gob_prep_hidden=10, nf_gob_cov_hidden=50, nf_gob_p_hidden=25, nf_invertible=1, nf_components=8, nf_decoder_type='continuous', nf_rnn='gru', nf_marks=0, nf_density_model='independent', nf_extrap=0, cru_lsd=64, cru_hidden_units=64, cru_enc_num_layers=1, cru_dec_num_layers=1, cru_num_layers=1, cru_dropout_type='None', cru_dropout_rate=0.0, cru_use_gate_hidden_states=True, cru_use_ode_for_gru=False, cru_use_decay_gravity_gate=True, cru_use_gravity_gate=True, cru_use_decay_input_gate=True, cru_use_input_gate=True, cru_use_skip_connection=True, cru_solver='euler', ts=0.3, grad_clip=False, ode_latents=20, ode_units=32, ode_gen_layers=1, ode_rec_dims=32, ode_rec_layers=1, ode_gru_units=32, ode_poisson=False, ode_classif=False, ode_linear_classif=False, ode_z0_encoder='odernn', ode_obsrv_std=0.01, ode_n_traj_samples=1, TTF_module='TTF_T2V_XAttn', MMF_module='MMF_XAttn_Add', llm_model_fusion='GPT2', llm_layers_fusion=6, max_length=1024, d_txt=768, recency_sigma=1.0, n_heads_fusion=1, kappa=0.5, epoch=20, patience=3, early_stop_delta=0.0001, lr=0.001, w_decay=0.01, batch_size=8, dropout=0.1, use_amp=False, logmode='a', save='experiments/', load=None, device=device(type='cuda'), PID=22032, C=5, enc_in=5, c_out=5, input_len=419, pred_len=419)
PID, device: 22032 cuda
Using dataset path: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT
Record AUS_AGR: 59 chunks created, 1 dropped (1.67%)
Record AUS_LAB: 59 chunks created, 0 dropped (0.00%)
Record CAN_AGR: 59 chunks created, 0 dropped (0.00%)
Record CAN_LAB: 59 chunks created, 0 dropped (0.00%)
Record GBR_AGR: 59 chunks created, 0 dropped (0.00%)
Record GBR_LAB: 59 chunks created, 0 dropped (0.00%)
Record USA_AGR: 59 chunks created, 0 dropped (0.00%)
Record USA_LAB: 59 chunks created, 0 dropped (0.00%)
+-------------------------------------+-----------------------------------------+
|                Metric               |                  Value                  |
+-------------------------------------+-----------------------------------------+
|             num_entities            |                    8                    |
|             num_features            |                    5                    |
|        num_unique_timestamps        |                  34317                  |
|           num_observations          |                  193205                 |
|  Feat observability entropy (norm)  |                   1.0                   |
| Temporal observation entropy (norm) |                  0.9964                 |
|               Mean IOI              |               0.3015 days               |
|               timespan              | 2021-01-01 03:15:00~2024-12-31 23:00:00 |
|               num_text              |                  14357                  |
|     Text temporal entropy (norm)    |                  0.9896                 |
+-------------------------------------+-----------------------------------------+
After chunking & splitting (instance): train=235, val=118, test=118
Using Standard Collate Fn
Scanning train split (30 batches)...
Scanning val split (15 batches)...
Scanning test split (15 batches)...

Training:   0%|          | 0/30 [00:00<?, ?it/s]
Epoch 0, Loss: 1.35704:   0%|          | 0/30 [00:01<?, ?it/s]
Epoch 0, Loss: 1.35704:   3%|▎         | 1/30 [00:01<00:36,  1.26s/it]
Epoch 0, Loss: 11.62165:   3%|▎         | 1/30 [00:01<00:36,  1.26s/it]
Epoch 0, Loss: 11.62165:   7%|▋         | 2/30 [00:01<00:20,  1.34it/s]
Epoch 0, Loss: 6.49412:   7%|▋         | 2/30 [00:02<00:20,  1.34it/s]
Epoch 0, Loss: 6.49412:  10%|█         | 3/30 [00:02<00:15,  1.74it/s]
Epoch 0, Loss: 5.84155:  10%|█         | 3/30 [00:02<00:15,  1.74it/s]
Epoch 0, Loss: 5.84155:  13%|█▎        | 4/30 [00:02<00:12,  2.00it/s]
Epoch 0, Loss: 1.82975:  13%|█▎        | 4/30 [00:02<00:12,  2.00it/s]
Epoch 0, Loss: 1.82975:  17%|█▋        | 5/30 [00:02<00:11,  2.21it/s]
Epoch 0, Loss: 1.63483:  17%|█▋        | 5/30 [00:03<00:11,  2.21it/s]
Epoch 0, Loss: 1.63483:  20%|██        | 6/30 [00:03<00:10,  2.31it/s]
Epoch 0, Loss: 2.31508:  20%|██        | 6/30 [00:03<00:10,  2.31it/s]
Epoch 0, Loss: 2.31508:  23%|██▎       | 7/30 [00:03<00:09,  2.46it/s]
Epoch 0, Loss: 2.02198:  23%|██▎       | 7/30 [00:03<00:09,  2.46it/s]
Epoch 0, Loss: 2.02198:  27%|██▋       | 8/30 [00:03<00:08,  2.59it/s]
Epoch 0, Loss: 1.24237:  27%|██▋       | 8/30 [00:04<00:08,  2.59it/s]
Epoch 0, Loss: 1.24237:  30%|███       | 9/30 [00:04<00:07,  2.69it/s]
Epoch 0, Loss: 1.30908:  30%|███       | 9/30 [00:04<00:07,  2.69it/s]
Epoch 0, Loss: 1.30908:  33%|███▎      | 10/30 [00:04<00:07,  2.71it/s]
Epoch 0, Loss: 1.87367:  33%|███▎      | 10/30 [00:04<00:07,  2.71it/s]
Epoch 0, Loss: 1.87367:  37%|███▋      | 11/30 [00:04<00:07,  2.69it/s]
Epoch 0, Loss: 1.30857:  37%|███▋      | 11/30 [00:05<00:07,  2.69it/s]
Epoch 0, Loss: 1.30857:  40%|████      | 12/30 [00:05<00:06,  2.76it/s]
Epoch 0, Loss: 1.16463:  40%|████      | 12/30 [00:05<00:06,  2.76it/s]
Epoch 0, Loss: 1.16463:  43%|████▎     | 13/30 [00:05<00:06,  2.80it/s]
Epoch 0, Loss: 1.74278:  43%|████▎     | 13/30 [00:05<00:06,  2.80it/s]
Epoch 0, Loss: 1.74278:  47%|████▋     | 14/30 [00:05<00:05,  2.83it/s]
Epoch 0, Loss: 1.27140:  47%|████▋     | 14/30 [00:06<00:05,  2.83it/s]
Epoch 0, Loss: 1.27140:  50%|█████     | 15/30 [00:06<00:05,  2.84it/s]
Epoch 0, Loss: 1.49857:  50%|█████     | 15/30 [00:06<00:05,  2.84it/s]
Epoch 0, Loss: 1.49857:  53%|█████▎    | 16/30 [00:06<00:05,  2.71it/s]
Epoch 0, Loss: 0.96968:  53%|█████▎    | 16/30 [00:07<00:05,  2.71it/s]
Epoch 0, Loss: 0.96968:  57%|█████▋    | 17/30 [00:07<00:04,  2.77it/s]
Epoch 0, Loss: 0.96516:  57%|█████▋    | 17/30 [00:07<00:04,  2.77it/s]
Epoch 0, Loss: 0.96516:  60%|██████    | 18/30 [00:07<00:04,  2.82it/s]
Epoch 0, Loss: 1.23351:  60%|██████    | 18/30 [00:07<00:04,  2.82it/s]
Epoch 0, Loss: 1.23351:  63%|██████▎   | 19/30 [00:07<00:03,  2.84it/s]
Epoch 0, Loss: 1.01705:  63%|██████▎   | 19/30 [00:08<00:03,  2.84it/s]
Epoch 0, Loss: 1.01705:  67%|██████▋   | 20/30 [00:08<00:03,  2.68it/s]
Epoch 0, Loss: 1.08161:  67%|██████▋   | 20/30 [00:08<00:03,  2.68it/s]
Epoch 0, Loss: 1.08161:  70%|███████   | 21/30 [00:08<00:03,  2.66it/s]
Epoch 0, Loss: 0.81815:  70%|███████   | 21/30 [00:09<00:03,  2.66it/s]
Epoch 0, Loss: 0.81815:  73%|███████▎  | 22/30 [00:09<00:03,  2.53it/s]
Epoch 0, Loss: 1.23582:  73%|███████▎  | 22/30 [00:09<00:03,  2.53it/s]
Epoch 0, Loss: 1.23582:  77%|███████▋  | 23/30 [00:09<00:02,  2.54it/s]
Epoch 0, Loss: 1.09616:  77%|███████▋  | 23/30 [00:09<00:02,  2.54it/s]
Epoch 0, Loss: 1.09616:  80%|████████  | 24/30 [00:09<00:02,  2.58it/s]
Epoch 0, Loss: 1.29538:  80%|████████  | 24/30 [00:10<00:02,  2.58it/s]
Epoch 0, Loss: 1.29538:  83%|████████▎ | 25/30 [00:10<00:02,  2.47it/s]
Epoch 0, Loss: 1.08829:  83%|████████▎ | 25/30 [00:10<00:02,  2.47it/s]
Epoch 0, Loss: 1.08829:  87%|████████▋ | 26/30 [00:10<00:01,  2.33it/s]
Epoch 0, Loss: 0.83569:  87%|████████▋ | 26/30 [00:11<00:01,  2.33it/s]
Epoch 0, Loss: 0.83569:  90%|█████████ | 27/30 [00:11<00:01,  2.27it/s]
Epoch 0, Loss: 1.23258:  90%|█████████ | 27/30 [00:11<00:01,  2.27it/s]
Epoch 0, Loss: 1.23258:  93%|█████████▎| 28/30 [00:11<00:00,  2.31it/s]
Epoch 0, Loss: 0.98382:  93%|█████████▎| 28/30 [00:12<00:00,  2.31it/s]
Epoch 0, Loss: 0.98382:  97%|█████████▋| 29/30 [00:12<00:00,  2.33it/s]
Epoch 0, Loss: 2.26121:  97%|█████████▋| 29/30 [00:12<00:00,  2.33it/s]
Epoch 0, Loss: 2.26121: 100%|██████████| 30/30 [00:12<00:00,  2.38it/s]
Epoch 0, Loss: 2.26121: 100%|██████████| 30/30 [00:12<00:00,  2.42it/s]

  0%|          | 0/15 [00:00<?, ?it/s]
 20%|██        | 3/15 [00:00<00:00, 21.12it/s]
 40%|████      | 6/15 [00:00<00:00, 21.98it/s]
 60%|██████    | 9/15 [00:00<00:00, 23.82it/s]
 80%|████████  | 12/15 [00:00<00:00, 25.35it/s]
100%|██████████| 15/15 [00:00<00:00, 26.43it/s]
100%|██████████| 15/15 [00:00<00:00, 25.00it/s]

  0%|          | 0/15 [00:00<?, ?it/s]
 20%|██        | 3/15 [00:00<00:00, 28.94it/s]
 40%|████      | 6/15 [00:00<00:00, 28.69it/s]
 60%|██████    | 9/15 [00:00<00:00, 28.39it/s]
 80%|████████  | 12/15 [00:00<00:00, 28.47it/s]
100%|██████████| 15/15 [00:00<00:00, 28.88it/s]
- Epoch 000, ExpID 6357
Train - Loss (one batch): 2.26121
Val - Loss, MSE, MAE: 1.08507, 1.08507, 0.76330
Test - Best epoch, Loss, MSE, MAE: 0, 1.13561, 1.13561, 0.66481
Time spent: 13.52s

Training:   0%|          | 0/30 [00:00<?, ?it/s]
Epoch 1, Loss: 0.71423:   0%|          | 0/30 [00:00<?, ?it/s]
Epoch 1, Loss: 0.71423:   3%|▎         | 1/30 [00:00<00:09,  3.02it/s]
Epoch 1, Loss: 1.39845:   3%|▎         | 1/30 [00:00<00:09,  3.02it/s]
Epoch 1, Loss: 1.39845:   7%|▋         | 2/30 [00:00<00:09,  3.00it/s]
Epoch 1, Loss: 1.00500:   7%|▋         | 2/30 [00:00<00:09,  3.00it/s]
Epoch 1, Loss: 1.00500:  10%|█         | 3/30 [00:00<00:08,  3.03it/s]
Epoch 1, Loss: 2.12016:  10%|█         | 3/30 [00:01<00:08,  3.03it/s]
Epoch 1, Loss: 2.12016:  13%|█▎        | 4/30 [00:01<00:09,  2.83it/s]
Epoch 1, Loss: 1.08389:  13%|█▎        | 4/30 [00:01<00:09,  2.83it/s]
Epoch 1, Loss: 1.08389:  17%|█▋        | 5/30 [00:01<00:08,  2.92it/s]
Epoch 1, Loss: 1.01528:  17%|█▋        | 5/30 [00:02<00:08,  2.92it/s]
Epoch 1, Loss: 1.01528:  20%|██        | 6/30 [00:02<00:08,  2.91it/s]
Epoch 1, Loss: 1.06835:  20%|██        | 6/30 [00:02<00:08,  2.91it/s]
Epoch 1, Loss: 1.06835:  23%|██▎       | 7/30 [00:02<00:08,  2.86it/s]
Epoch 1, Loss: 0.93747:  23%|██▎       | 7/30 [00:02<00:08,  2.86it/s]
Epoch 1, Loss: 0.93747:  27%|██▋       | 8/30 [00:02<00:07,  2.88it/s]
Epoch 1, Loss: 0.83155:  27%|██▋       | 8/30 [00:03<00:07,  2.88it/s]
Epoch 1, Loss: 0.83155:  30%|███       | 9/30 [00:03<00:07,  2.88it/s]
Epoch 1, Loss: 1.19702:  30%|███       | 9/30 [00:03<00:07,  2.88it/s]
Epoch 1, Loss: 1.19702:  33%|███▎      | 10/30 [00:03<00:07,  2.81it/s]
Epoch 1, Loss: 0.92342:  33%|███▎      | 10/30 [00:03<00:07,  2.81it/s]
Epoch 1, Loss: 0.92342:  37%|███▋      | 11/30 [00:03<00:07,  2.68it/s]
Epoch 1, Loss: 1.35845:  37%|███▋      | 11/30 [00:04<00:07,  2.68it/s]
Epoch 1, Loss: 1.35845:  40%|████      | 12/30 [00:04<00:06,  2.73it/s]
Epoch 1, Loss: 0.94874:  40%|████      | 12/30 [00:04<00:06,  2.73it/s]
Epoch 1, Loss: 0.94874:  43%|████▎     | 13/30 [00:04<00:06,  2.76it/s]
Epoch 1, Loss: 0.77852:  43%|████▎     | 13/30 [00:04<00:06,  2.76it/s]
Epoch 1, Loss: 0.77852:  47%|████▋     | 14/30 [00:04<00:05,  2.76it/s]
Epoch 1, Loss: 0.87326:  47%|████▋     | 14/30 [00:05<00:05,  2.76it/s]
Epoch 1, Loss: 0.87326:  50%|█████     | 15/30 [00:05<00:05,  2.74it/s]
Epoch 1, Loss: 1.22213:  50%|█████     | 15/30 [00:05<00:05,  2.74it/s]
Epoch 1, Loss: 1.22213:  53%|█████▎    | 16/30 [00:05<00:05,  2.64it/s]
Epoch 1, Loss: 1.04307:  53%|█████▎    | 16/30 [00:06<00:05,  2.64it/s]
Epoch 1, Loss: 1.04307:  57%|█████▋    | 17/30 [00:06<00:04,  2.72it/s]
Epoch 1, Loss: 0.96082:  57%|█████▋    | 17/30 [00:06<00:04,  2.72it/s]
Epoch 1, Loss: 0.96082:  60%|██████    | 18/30 [00:06<00:04,  2.78it/s]
Epoch 1, Loss: 1.73770:  60%|██████    | 18/30 [00:06<00:04,  2.78it/s]
Epoch 1, Loss: 1.73770:  63%|██████▎   | 19/30 [00:06<00:03,  2.82it/s]
Epoch 1, Loss: 1.26125:  63%|██████▎   | 19/30 [00:07<00:03,  2.82it/s]
Epoch 1, Loss: 1.26125:  67%|██████▋   | 20/30 [00:07<00:03,  2.85it/s]
Epoch 1, Loss: 0.83770:  67%|██████▋   | 20/30 [00:07<00:03,  2.85it/s]
Epoch 1, Loss: 0.83770:  70%|███████   | 21/30 [00:07<00:03,  2.87it/s]
Epoch 1, Loss: 1.08974:  70%|███████   | 21/30 [00:07<00:03,  2.87it/s]
Epoch 1, Loss: 1.08974:  73%|███████▎  | 22/30 [00:07<00:02,  2.85it/s]
Epoch 1, Loss: 1.16164:  73%|███████▎  | 22/30 [00:08<00:02,  2.85it/s]
Epoch 1, Loss: 1.16164:  77%|███████▋  | 23/30 [00:08<00:02,  2.77it/s]
Epoch 1, Loss: 0.86919:  77%|███████▋  | 23/30 [00:08<00:02,  2.77it/s]
Epoch 1, Loss: 0.86919:  80%|████████  | 24/30 [00:08<00:02,  2.75it/s]
Epoch 1, Loss: 1.20672:  80%|████████  | 24/30 [00:08<00:02,  2.75it/s]
Epoch 1, Loss: 1.20672:  83%|████████▎ | 25/30 [00:08<00:01,  2.77it/s]
Epoch 1, Loss: 0.91170:  83%|████████▎ | 25/30 [00:09<00:01,  2.77it/s]
Epoch 1, Loss: 0.91170:  87%|████████▋ | 26/30 [00:09<00:01,  2.72it/s]
Epoch 1, Loss: 0.94389:  87%|████████▋ | 26/30 [00:09<00:01,  2.72it/s]
Epoch 1, Loss: 0.94389:  90%|█████████ | 27/30 [00:09<00:01,  2.65it/s]
Epoch 1, Loss: 0.94034:  90%|█████████ | 27/30 [00:10<00:01,  2.65it/s]
Epoch 1, Loss: 0.94034:  93%|█████████▎| 28/30 [00:10<00:00,  2.62it/s]
Epoch 1, Loss: 0.83568:  93%|█████████▎| 28/30 [00:10<00:00,  2.62it/s]
Epoch 1, Loss: 0.83568:  97%|█████████▋| 29/30 [00:10<00:00,  2.52it/s]
Epoch 1, Loss: 1.03033:  97%|█████████▋| 29/30 [00:10<00:00,  2.52it/s]
Epoch 1, Loss: 1.03033: 100%|██████████| 30/30 [00:10<00:00,  2.65it/s]
Epoch 1, Loss: 1.03033: 100%|██████████| 30/30 [00:10<00:00,  2.76it/s]

  0%|          | 0/15 [00:00<?, ?it/s]
 20%|██        | 3/15 [00:00<00:00, 23.99it/s]
 40%|████      | 6/15 [00:00<00:00, 26.03it/s]
 60%|██████    | 9/15 [00:00<00:00, 27.19it/s]
 80%|████████  | 12/15 [00:00<00:00, 27.36it/s]
100%|██████████| 15/15 [00:00<00:00, 27.47it/s]

  0%|          | 0/15 [00:00<?, ?it/s]
 20%|██        | 3/15 [00:00<00:00, 28.32it/s]
 40%|████      | 6/15 [00:00<00:00, 28.48it/s]
 60%|██████    | 9/15 [00:00<00:00, 28.59it/s]
 80%|████████  | 12/15 [00:00<00:00, 28.57it/s]
100%|██████████| 15/15 [00:00<00:00, 28.83it/s]
- Epoch 001, ExpID 6357
Train - Loss (one batch): 1.03033
Val - Loss, MSE, MAE: 1.04502, 1.04502, 0.71191
Test - Best epoch, Loss, MSE, MAE: 1, 1.07714, 1.07714, 0.62493
Time spent: 11.92s

Training:   0%|          | 0/30 [00:00<?, ?it/s]
Epoch 2, Loss: 1.28736:   0%|          | 0/30 [00:00<?, ?it/s]
Epoch 2, Loss: 1.28736:   3%|▎         | 1/30 [00:00<00:09,  2.92it/s]
Epoch 2, Loss: 0.81014:   3%|▎         | 1/30 [00:00<00:09,  2.92it/s]
Epoch 2, Loss: 0.81014:   7%|▋         | 2/30 [00:00<00:09,  2.90it/s]
Epoch 2, Loss: 0.96422:   7%|▋         | 2/30 [00:01<00:09,  2.90it/s]
Epoch 2, Loss: 0.96422:  10%|█         | 3/30 [00:01<00:09,  2.97it/s]
Epoch 2, Loss: 1.30679:  10%|█         | 3/30 [00:01<00:09,  2.97it/s]
Epoch 2, Loss: 1.30679:  13%|█▎        | 4/30 [00:01<00:08,  3.04it/s]
Epoch 2, Loss: 1.12500:  13%|█▎        | 4/30 [00:01<00:08,  3.04it/s]
Epoch 2, Loss: 1.12500:  17%|█▋        | 5/30 [00:01<00:08,  3.05it/s]
Epoch 2, Loss: 0.82292:  17%|█▋        | 5/30 [00:01<00:08,  3.05it/s]
Epoch 2, Loss: 0.82292:  20%|██        | 6/30 [00:01<00:07,  3.02it/s]
Epoch 2, Loss: 0.82788:  20%|██        | 6/30 [00:02<00:07,  3.02it/s]
Epoch 2, Loss: 0.82788:  23%|██▎       | 7/30 [00:02<00:07,  3.01it/s]
Epoch 2, Loss: 1.29488:  23%|██▎       | 7/30 [00:02<00:07,  3.01it/s]
Epoch 2, Loss: 1.29488:  27%|██▋       | 8/30 [00:02<00:07,  3.00it/s]
Epoch 2, Loss: 1.83762:  27%|██▋       | 8/30 [00:03<00:07,  3.00it/s]
Epoch 2, Loss: 1.83762:  30%|███       | 9/30 [00:03<00:07,  2.98it/s]
Epoch 2, Loss: 0.78138:  30%|███       | 9/30 [00:03<00:07,  2.98it/s]
Epoch 2, Loss: 0.78138:  33%|███▎      | 10/30 [00:03<00:06,  2.98it/s]
Epoch 2, Loss: 0.96783:  33%|███▎      | 10/30 [00:03<00:06,  2.98it/s]
Epoch 2, Loss: 0.96783:  37%|███▋      | 11/30 [00:03<00:06,  2.95it/s]
Epoch 2, Loss: 1.11220:  37%|███▋      | 11/30 [00:04<00:06,  2.95it/s]
Epoch 2, Loss: 1.11220:  40%|████      | 12/30 [00:04<00:06,  2.94it/s]
Epoch 2, Loss: 0.80938:  40%|████      | 12/30 [00:04<00:06,  2.94it/s]
Epoch 2, Loss: 0.80938:  43%|████▎     | 13/30 [00:04<00:05,  2.94it/s]
Epoch 2, Loss: 1.18332:  43%|████▎     | 13/30 [00:04<00:05,  2.94it/s]
Epoch 2, Loss: 1.18332:  47%|████▋     | 14/30 [00:04<00:05,  2.95it/s]
Epoch 2, Loss: 1.45155:  47%|████▋     | 14/30 [00:05<00:05,  2.95it/s]
Epoch 2, Loss: 1.45155:  50%|█████     | 15/30 [00:05<00:05,  2.84it/s]
Epoch 2, Loss: 0.83176:  50%|█████     | 15/30 [00:05<00:05,  2.84it/s]
Epoch 2, Loss: 0.83176:  53%|█████▎    | 16/30 [00:05<00:04,  2.86it/s]
Epoch 2, Loss: 0.83524:  53%|█████▎    | 16/30 [00:05<00:04,  2.86it/s]
Epoch 2, Loss: 0.83524:  57%|█████▋    | 17/30 [00:05<00:04,  2.87it/s]
Epoch 2, Loss: 0.89874:  57%|█████▋    | 17/30 [00:06<00:04,  2.87it/s]
Epoch 2, Loss: 0.89874:  60%|██████    | 18/30 [00:06<00:04,  2.84it/s]
Epoch 2, Loss: 1.06896:  60%|██████    | 18/30 [00:06<00:04,  2.84it/s]
Epoch 2, Loss: 1.06896:  63%|██████▎   | 19/30 [00:06<00:04,  2.61it/s]
Epoch 2, Loss: 1.22814:  63%|██████▎   | 19/30 [00:07<00:04,  2.61it/s]
Epoch 2, Loss: 1.22814:  67%|██████▋   | 20/30 [00:07<00:03,  2.56it/s]
Epoch 2, Loss: 0.96164:  67%|██████▋   | 20/30 [00:07<00:03,  2.56it/s]
Epoch 2, Loss: 0.96164:  70%|███████   | 21/30 [00:07<00:03,  2.66it/s]
Epoch 2, Loss: 0.93466:  70%|███████   | 21/30 [00:07<00:03,  2.66it/s]
Epoch 2, Loss: 0.93466:  73%|███████▎  | 22/30 [00:07<00:02,  2.73it/s]
Epoch 2, Loss: 0.77346:  73%|███████▎  | 22/30 [00:08<00:02,  2.73it/s]
Epoch 2, Loss: 0.77346:  77%|███████▋  | 23/30 [00:08<00:02,  2.73it/s]
Epoch 2, Loss: 0.92927:  77%|███████▋  | 23/30 [00:08<00:02,  2.73it/s]
Epoch 2, Loss: 0.92927:  80%|████████  | 24/30 [00:08<00:02,  2.73it/s]
Epoch 2, Loss: 0.94750:  80%|████████  | 24/30 [00:08<00:02,  2.73it/s]
Epoch 2, Loss: 0.94750:  83%|████████▎ | 25/30 [00:08<00:01,  2.60it/s]
Epoch 2, Loss: 0.90220:  83%|████████▎ | 25/30 [00:09<00:01,  2.60it/s]
Epoch 2, Loss: 0.90220:  87%|████████▋ | 26/30 [00:09<00:01,  2.60it/s]
Epoch 2, Loss: 1.71764:  87%|████████▋ | 26/30 [00:09<00:01,  2.60it/s]
Epoch 2, Loss: 1.71764:  90%|█████████ | 27/30 [00:09<00:01,  2.64it/s]
Epoch 2, Loss: 1.15966:  90%|█████████ | 27/30 [00:09<00:01,  2.64it/s]
Epoch 2, Loss: 1.15966:  93%|█████████▎| 28/30 [00:09<00:00,  2.62it/s]
Epoch 2, Loss: 1.26584:  93%|█████████▎| 28/30 [00:10<00:00,  2.62it/s]
Epoch 2, Loss: 1.26584:  97%|█████████▋| 29/30 [00:10<00:00,  2.61it/s]
Epoch 2, Loss: 0.96076:  97%|█████████▋| 29/30 [00:10<00:00,  2.61it/s]
Epoch 2, Loss: 0.96076: 100%|██████████| 30/30 [00:10<00:00,  2.67it/s]
Epoch 2, Loss: 0.96076: 100%|██████████| 30/30 [00:10<00:00,  2.79it/s]

  0%|          | 0/15 [00:00<?, ?it/s]
 20%|██        | 3/15 [00:00<00:00, 22.93it/s]

In [ ]:
DATASETS = ["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"]
MODELS = ["tPatchGNN"]
ENCODERS = ["GPT2"]
TTF_MODULES = ["TTF_RecAvg"]
MMF_MODULES = ["MMF_GR_Add"]
MAX_RUNS_THIS_SESSION = 10

In [ ]:
DATASETS = ["FNSPID"]   # change to GDELT, FNSPID, ClusterTrace, CESNET
MODELS = [
    "Informer", "DLinear", "PatchTST", "TimesNet", "TimeMixer",
    "TimeLLM", "TTM", "CRU", "LatentODE", "NeuralFlow", "tPatchGNN"
]
ENCODERS = ["GPT2", "BERT", "Llama", "DeepSeek"]
TTF_MODULES = ["TTF_RecAvg", "TTF_T2V_XAttn"]
MMF_MODULES = ["MMF_GR_Add", "MMF_XAttn_Add"]
MAX_RUNS_THIS_SESSION = 30

In [ ]:
DATASETS = ["MIMIC"]   # change to GDELT, FNSPID, ClusterTrace, CESNET
MODELS = [
    "Informer", "DLinear", "PatchTST", "TimesNet", "TimeMixer",
    "TimeLLM", "TTM", "CRU", "LatentODE", "NeuralFlow", "tPatchGNN"
]
ENCODERS = ["GPT2", "BERT", "Llama", "DeepSeek"]
TTF_MODULES = ["TTF_RecAvg", "TTF_T2V_XAttn"]
MMF_MODULES = ["MMF_GR_Add", "MMF_XAttn_Add"]
MAX_RUNS_THIS_SESSION = 30

In [ ]:
status_path = RESULTS_ROOT / "partA_run_status.csv"
if status_path.exists():
    status_df = pd.read_csv(status_path)
    print(status_df["return_code"].value_counts(dropna=False))
    display(status_df.tail(20))
else:
    print("No status file yet.")

In [ ]:
done = []
failed = []

for log_file in sorted(LOG_ROOT.glob("*.log")):
    txt = log_file.read_text(encoding="utf-8", errors="ignore")
    if "### Done ###" in txt or ("mse:" in txt and "mae:" in txt):
        done.append(log_file.name)
    elif "Traceback" in txt or "error:" in txt:
        failed.append(log_file.name)

print("Completed logs:", len(done))
print("Failed logs:", len(failed))
print("\nSample completed:", done[:10])
print("\nSample failed:", failed[:10])

In [ ]:
DATASETS = ["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"]
MODELS = ["tPatchGNN"]
ENCODERS = ["GPT2"]
TTF_MODULES = ["TTF_RecAvg"]
MMF_MODULES = ["MMF_GR_Add"]
MAX_RUNS_THIS_SESSION = 10

In [ ]:
from pathlib import Path
import subprocess
import itertools
import pandas as pd
from datetime import datetime

REPO_ROOT = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF")
LOG_ROOT = REPO_ROOT / "run_logs_full"
RESULTS_ROOT = REPO_ROOT / "results_full"

LOG_ROOT.mkdir(parents=True, exist_ok=True)
RESULTS_ROOT.mkdir(parents=True, exist_ok=True)

DATASETS = ["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"]
MODELS = [
    "Informer",
    "DLinear",
    "PatchTST",
    "TimesNet",
    "TimeMixer",
    "TimeLLM",
    "TTM",
    "CRU",
    "LatentODE",
    "NeuralFlow",
    "tPatchGNN",
]
ENCODERS = ["GPT2", "BERT", "Llama", "DeepSeek"]
TTF_MODULES = ["TTF_RecAvg", "TTF_T2V_XAttn"]
MMF_MODULES = ["MMF_GR_Add", "MMF_XAttn_Add"]
SEEDS = [42]

RUN_UNIMODAL = True
RUN_MULTIMODAL = True

# Start smaller per session. Increase later.
MAX_RUNS_THIS_SESSION = 20
SKIP_COMPLETED = True
FORCE_RERUN_FAILED = False

BATCH_SIZE = 8
EPOCHS = 20
SPLIT_METHOD = "instance"

def model_overrides(model: str, dataset: str) -> dict:
    overrides = {}

    if model == "tPatchGNN":
        overrides.update({
            "patch_size": 24,
            "nlayer": 1,
            "te_dim": 10,
            "node_dim": 10,
            "hid_dim": 32,
        })
        if dataset == "CESNET":
            overrides.update({
                "history": 12,
                "pred_window": 6,
                "stride": 6,
                "patch_size": 6,
                "patch_stride": 6,
                "npatch": 2,
            })

    return overrides

def run_name(dataset, model, seed, modality, ttf=None, mmf=None, enc=None):
    parts = [dataset, model, f"seed{seed}", modality]
    if modality == "multi":
        parts.extend([ttf, mmf, enc])
    return "__".join(parts)

def build_cmd(dataset, model, seed, modality, ttf=None, mmf=None, enc=None):
    cmd = [
        "/usr/bin/python3", "main.py",
        "--dataset", dataset,
        "--model", model,
        "--split_method", SPLIT_METHOD,
        "-b", str(BATCH_SIZE),
        "--epoch", str(EPOCHS),
        "--seed", str(seed),
    ]

    ov = model_overrides(model, dataset)
    for k, v in ov.items():
        cmd.extend([f"--{k}", str(v)])

    if modality == "multi":
        cmd.extend([
            "--TTF_module", ttf,
            "--MMF_module", mmf,
            "--llm_model_fusion", enc,
            "--use_text_embeddings",
            "--enable_text",
        ])

    return cmd

def log_contains_done(log_path: Path) -> bool:
    if not log_path.exists():
        return False
    txt = log_path.read_text(encoding="utf-8", errors="ignore")
    return ("### Done ###" in txt) or ("mse:" in txt and "mae:" in txt)

def log_contains_failure(log_path: Path) -> bool:
    if not log_path.exists():
        return False
    txt = log_path.read_text(encoding="utf-8", errors="ignore")
    fail_markers = [
        "Traceback",
        "ModuleNotFoundError",
        "RuntimeError",
        "FileNotFoundError",
        "error:",
    ]
    return any(m in txt for m in fail_markers)

jobs = []
for dataset, model, seed in itertools.product(DATASETS, MODELS, SEEDS):
    if RUN_UNIMODAL:
        jobs.append({
            "dataset": dataset, "model": model, "seed": seed,
            "modality": "uni", "ttf": None, "mmf": None, "encoder": None
        })
    if RUN_MULTIMODAL:
        for ttf, mmf, enc in itertools.product(TTF_MODULES, MMF_MODULES, ENCODERS):
            jobs.append({
                "dataset": dataset, "model": model, "seed": seed,
                "modality": "multi", "ttf": ttf, "mmf": mmf, "encoder": enc
            })

manifest = pd.DataFrame(jobs)
manifest_path = RESULTS_ROOT / "partA_manifest_full.csv"
manifest.to_csv(manifest_path, index=False)

print("Total jobs in full Part A grid:", len(jobs))
print("Manifest saved to:", manifest_path)
manifest.head()

Total jobs in full Part A grid: 935
Manifest saved to: /content/drive/MyDrive/time_imm_project/IMM-TSF/results_full/partA_manifest_full.csv

  dataset     model  seed modality         ttf         mmf   encoder
0   GDELT  Informer    42      uni        None        None      None
1   GDELT  Informer    42    multi  TTF_RecAvg  MMF_GR_Add      GPT2
2   GDELT  Informer    42    multi  TTF_RecAvg  MMF_GR_Add      BERT
3   GDELT  Informer    42    multi  TTF_RecAvg  MMF_GR_Add     Llama
4   GDELT  Informer    42    multi  TTF_RecAvg  MMF_GR_Add  DeepSeek

In [ ]:
status_rows = []
status_path = RESULTS_ROOT / "partA_run_status.csv"

to_run = []
for j in jobs:
    rn = run_name(j["dataset"], j["model"], j["seed"], j["modality"], j["ttf"], j["mmf"], j["encoder"])
    log_path = LOG_ROOT / f"{rn}.log"

    if SKIP_COMPLETED and log_contains_done(log_path):
        continue
    if (not FORCE_RERUN_FAILED) and log_contains_failure(log_path):
        continue

    to_run.append(j)

if MAX_RUNS_THIS_SESSION is not None:
    to_run = to_run[:MAX_RUNS_THIS_SESSION]

print(f"Jobs queued this session: {len(to_run)}")

for idx, j in enumerate(to_run, 1):
    rn = run_name(j["dataset"], j["model"], j["seed"], j["modality"], j["ttf"], j["mmf"], j["encoder"])
    log_path = LOG_ROOT / f"{rn}.log"
    cmd = build_cmd(j["dataset"], j["model"], j["seed"], j["modality"], j["ttf"], j["mmf"], j["encoder"])

    print("\n" + "="*100)
    print(f"[{idx}/{len(to_run)}] {rn}")
    print("CMD:", " ".join(cmd))
    print("="*100)

    with open(log_path, "w", encoding="utf-8") as f:
        proc = subprocess.Popen(
            cmd,
            cwd=str(REPO_ROOT),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        for line in proc.stdout:
            print(line, end="")
            f.write(line)
        return_code = proc.wait()

    status_rows.append({
        "timestamp": datetime.now().isoformat(),
        "run_name": rn,
        "dataset": j["dataset"],
        "model": j["model"],
        "seed": j["seed"],
        "modality": j["modality"],
        "ttf_module": j["ttf"],
        "mmf_module": j["mmf"],
        "text_encoder": j["encoder"],
        "return_code": return_code,
        "log_file": str(log_path),
    })

    pd.DataFrame(status_rows).to_csv(status_path, index=False)
    print(f"[INFO] return code = {return_code}")

print(f"\nSaved session status to: {status_path}")

Jobs queued this session: 20

====================================================================================================
[1/20] GDELT__DLinear__seed42__multi__TTF_RecAvg__MMF_GR_Add__Llama
CMD: /usr/bin/python3 main.py --dataset GDELT --model DLinear --split_method instance -b 8 --epoch 20 --seed 42 --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion Llama --use_text_embeddings --enable_text
====================================================================================================
PID, device: 23886 cuda
Using dataset path: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT
Traceback (most recent call last):
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets
    ds = ChunkedTimeSeriesDataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 149, in __init__
    raise FileNotFoundError(f"Missing text embeddings file: {path}")
FileNotFoundError: Missing text embeddings file: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT/processed/AUS_AGR/text_embeddings_model=Llama_layers=6_maxlen=1024.pt
[INFO] return code = 1

====================================================================================================
[2/20] GDELT__DLinear__seed42__multi__TTF_RecAvg__MMF_GR_Add__DeepSeek
CMD: /usr/bin/python3 main.py --dataset GDELT --model DLinear --split_method instance -b 8 --epoch 20 --seed 42 --TTF_module TTF_RecAvg --MMF_module MMF_GR_Add --llm_model_fusion DeepSeek --use_text_embeddings --enable_text
====================================================================================================
PID, device: 23948 cuda
Using dataset path: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT
Traceback (most recent call last):
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets
    ds = ChunkedTimeSeriesDataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 149, in __init__
    raise FileNotFoundError(f"Missing text embeddings file: {path}")
FileNotFoundError: Missing text embeddings file: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT/processed/AUS_AGR/text_embeddings_model=DeepSeek_layers=6_maxlen=1024.pt
[INFO] return code = 1

====================================================================================================
[3/20] GDELT__DLinear__seed42__multi__TTF_RecAvg__MMF_XAttn_Add__GPT2
CMD: /usr/bin/python3 main.py --dataset GDELT --model DLinear --split_method instance -b 8 --epoch 20 --seed 42 --TTF_module TTF_RecAvg --MMF_module MMF_XAttn_Add --llm_model_fusion GPT2 --use_text_embeddings --enable_text
====================================================================================================
PID, device: 24007 cuda
Using dataset path: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT
Traceback (most recent call last):
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets
    ds = ChunkedTimeSeriesDataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 149, in __init__
    raise FileNotFoundError(f"Missing text embeddings file: {path}")
FileNotFoundError: Missing text embeddings file: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT/processed/AUS_AGR/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
[INFO] return code = 1

====================================================================================================
[4/20] GDELT__DLinear__seed42__multi__TTF_RecAvg__MMF_XAttn_Add__BERT
CMD: /usr/bin/python3 main.py --dataset GDELT --model DLinear --split_method instance -b 8 --epoch 20 --seed 42 --TTF_module TTF_RecAvg --MMF_module MMF_XAttn_Add --llm_model_fusion BERT --use_text_embeddings --enable_text
====================================================================================================
PID, device: 24069 cuda
Using dataset path: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT
Traceback (most recent call last):
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets
    ds = ChunkedTimeSeriesDataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 149, in __init__
    raise FileNotFoundError(f"Missing text embeddings file: {path}")
FileNotFoundError: Missing text embeddings file: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT/processed/AUS_AGR/text_embeddings_model=BERT_layers=6_maxlen=512.pt
[INFO] return code = 1

====================================================================================================
[5/20] GDELT__DLinear__seed42__multi__TTF_RecAvg__MMF_XAttn_Add__Llama
CMD: /usr/bin/python3 main.py --dataset GDELT --model DLinear --split_method instance -b 8 --epoch 20 --seed 42 --TTF_module TTF_RecAvg --MMF_module MMF_XAttn_Add --llm_model_fusion Llama --use_text_embeddings --enable_text
====================================================================================================
PID, device: 24131 cuda
Using dataset path: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT
Traceback (most recent call last):
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets
    ds = ChunkedTimeSeriesDataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 149, in __init__
    raise FileNotFoundError(f"Missing text embeddings file: {path}")
FileNotFoundError: Missing text embeddings file: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT/processed/AUS_AGR/text_embeddings_model=Llama_layers=6_maxlen=1024.pt
[INFO] return code = 1

====================================================================================================
[6/20] GDELT__DLinear__seed42__multi__TTF_RecAvg__MMF_XAttn_Add__DeepSeek
CMD: /usr/bin/python3 main.py --dataset GDELT --model DLinear --split_method instance -b 8 --epoch 20 --seed 42 --TTF_module TTF_RecAvg --MMF_module MMF_XAttn_Add --llm_model_fusion DeepSeek --use_text_embeddings --enable_text
====================================================================================================
PID, device: 24193 cuda
Using dataset path: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT
Traceback (most recent call last):
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets
    ds = ChunkedTimeSeriesDataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 149, in __init__
    raise FileNotFoundError(f"Missing text embeddings file: {path}")
FileNotFoundError: Missing text embeddings file: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT/processed/AUS_AGR/text_embeddings_model=DeepSeek_layers=6_maxlen=1024.pt
[INFO] return code = 1

====================================================================================================
[7/20] GDELT__DLinear__seed42__multi__TTF_T2V_XAttn__MMF_GR_Add__GPT2
CMD: /usr/bin/python3 main.py --dataset GDELT --model DLinear --split_method instance -b 8 --epoch 20 --seed 42 --TTF_module TTF_T2V_XAttn --MMF_module MMF_GR_Add --llm_model_fusion GPT2 --use_text_embeddings --enable_text
====================================================================================================
PID, device: 24252 cuda
Using dataset path: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT
Traceback (most recent call last):
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets
    ds = ChunkedTimeSeriesDataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 149, in __init__
    raise FileNotFoundError(f"Missing text embeddings file: {path}")
FileNotFoundError: Missing text embeddings file: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT/processed/AUS_AGR/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
[INFO] return code = 1

====================================================================================================
[8/20] GDELT__DLinear__seed42__multi__TTF_T2V_XAttn__MMF_GR_Add__BERT
CMD: /usr/bin/python3 main.py --dataset GDELT --model DLinear --split_method instance -b 8 --epoch 20 --seed 42 --TTF_module TTF_T2V_XAttn --MMF_module MMF_GR_Add --llm_model_fusion BERT --use_text_embeddings --enable_text
====================================================================================================
PID, device: 24316 cuda
Using dataset path: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT
Traceback (most recent call last):
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets
    ds = ChunkedTimeSeriesDataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 149, in __init__
    raise FileNotFoundError(f"Missing text embeddings file: {path}")
FileNotFoundError: Missing text embeddings file: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT/processed/AUS_AGR/text_embeddings_model=BERT_layers=6_maxlen=512.pt
[INFO] return code = 1

====================================================================================================
[9/20] GDELT__DLinear__seed42__multi__TTF_T2V_XAttn__MMF_GR_Add__Llama
CMD: /usr/bin/python3 main.py --dataset GDELT --model DLinear --split_method instance -b 8 --epoch 20 --seed 42 --TTF_module TTF_T2V_XAttn --MMF_module MMF_GR_Add --llm_model_fusion Llama --use_text_embeddings --enable_text
====================================================================================================
PID, device: 24381 cuda
Using dataset path: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT
Traceback (most recent call last):
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets
    ds = ChunkedTimeSeriesDataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 149, in __init__
    raise FileNotFoundError(f"Missing text embeddings file: {path}")
FileNotFoundError: Missing text embeddings file: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT/processed/AUS_AGR/text_embeddings_model=Llama_layers=6_maxlen=1024.pt
[INFO] return code = 1

====================================================================================================
[10/20] GDELT__DLinear__seed42__multi__TTF_T2V_XAttn__MMF_GR_Add__DeepSeek
CMD: /usr/bin/python3 main.py --dataset GDELT --model DLinear --split_method instance -b 8 --epoch 20 --seed 42 --TTF_module TTF_T2V_XAttn --MMF_module MMF_GR_Add --llm_model_fusion DeepSeek --use_text_embeddings --enable_text
====================================================================================================
PID, device: 24443 cuda
Using dataset path: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT
Traceback (most recent call last):
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets
    ds = ChunkedTimeSeriesDataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 149, in __init__
    raise FileNotFoundError(f"Missing text embeddings file: {path}")
FileNotFoundError: Missing text embeddings file: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT/processed/AUS_AGR/text_embeddings_model=DeepSeek_layers=6_maxlen=1024.pt
[INFO] return code = 1

====================================================================================================
[11/20] GDELT__DLinear__seed42__multi__TTF_T2V_XAttn__MMF_XAttn_Add__GPT2
CMD: /usr/bin/python3 main.py --dataset GDELT --model DLinear --split_method instance -b 8 --epoch 20 --seed 42 --TTF_module TTF_T2V_XAttn --MMF_module MMF_XAttn_Add --llm_model_fusion GPT2 --use_text_embeddings --enable_text
====================================================================================================
PID, device: 24506 cuda
Using dataset path: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT
Traceback (most recent call last):
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets
    ds = ChunkedTimeSeriesDataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 149, in __init__
    raise FileNotFoundError(f"Missing text embeddings file: {path}")
FileNotFoundError: Missing text embeddings file: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT/processed/AUS_AGR/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt
[INFO] return code = 1

====================================================================================================
[12/20] GDELT__DLinear__seed42__multi__TTF_T2V_XAttn__MMF_XAttn_Add__BERT
CMD: /usr/bin/python3 main.py --dataset GDELT --model DLinear --split_method instance -b 8 --epoch 20 --seed 42 --TTF_module TTF_T2V_XAttn --MMF_module MMF_XAttn_Add --llm_model_fusion BERT --use_text_embeddings --enable_text
====================================================================================================
PID, device: 24565 cuda
Using dataset path: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT
Traceback (most recent call last):
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets
    ds = ChunkedTimeSeriesDataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 149, in __init__
    raise FileNotFoundError(f"Missing text embeddings file: {path}")
FileNotFoundError: Missing text embeddings file: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT/processed/AUS_AGR/text_embeddings_model=BERT_layers=6_maxlen=512.pt
[INFO] return code = 1

====================================================================================================
[13/20] GDELT__DLinear__seed42__multi__TTF_T2V_XAttn__MMF_XAttn_Add__Llama
CMD: /usr/bin/python3 main.py --dataset GDELT --model DLinear --split_method instance -b 8 --epoch 20 --seed 42 --TTF_module TTF_T2V_XAttn --MMF_module MMF_XAttn_Add --llm_model_fusion Llama --use_text_embeddings --enable_text
====================================================================================================
PID, device: 24630 cuda
Using dataset path: /content/drive/MyDrive/time_imm_project/IMM-TSF/data/GDELT
Traceback (most recent call last):
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1319, in <module>
    best_metrics = trainable(tunable_params, fixed_params, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py", line 1021, in trainable
    data_obj = parse_datasets(args)
               ^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/time_imm_project/IMM-TSF/lib/parse_datasets.py", line 661, in parse_datasets

In [ ]:
from pathlib import Path
import subprocess
import itertools
import pandas as pd
from datetime import datetime

REPO_ROOT = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF")
LOG_ROOT = REPO_ROOT / "run_logs_full"
RESULTS_ROOT = REPO_ROOT / "results_full"

LOG_ROOT.mkdir(parents=True, exist_ok=True)
RESULTS_ROOT.mkdir(parents=True, exist_ok=True)

DATASETS = ["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"]
MODELS = [
    "Informer",
    "DLinear",
    "PatchTST",
    "TimesNet",
    "TimeMixer",
    "TimeLLM",
    "TTM",
    "CRU",
    "LatentODE",
    "NeuralFlow",
    "tPatchGNN",
]
SEEDS = [42]

BATCH_SIZE = 8
EPOCHS = 20
SPLIT_METHOD = "instance"
MAX_RUNS_THIS_SESSION = 20
SKIP_COMPLETED = True

def model_overrides(model: str, dataset: str) -> dict:
    overrides = {}

    if model == "tPatchGNN":
        overrides.update({
            "patch_size": 24,
            "nlayer": 1,
            "te_dim": 10,
            "node_dim": 10,
            "hid_dim": 32,
        })
        if dataset == "CESNET":
            overrides.update({
                "history": 12,
                "pred_window": 6,
                "stride": 6,
                "patch_size": 6,
                "patch_stride": 6,
                "npatch": 2,
            })

    return overrides

def run_name(dataset, model, seed):
    return f"{dataset}__{model}__seed{seed}__uni"

def build_cmd(dataset, model, seed):
    cmd = [
        "/usr/bin/python3", "main.py",
        "--dataset", dataset,
        "--model", model,
        "--split_method", SPLIT_METHOD,
        "-b", str(BATCH_SIZE),
        "--epoch", str(EPOCHS),
        "--seed", str(seed),
    ]
    ov = model_overrides(model, dataset)
    for k, v in ov.items():
        cmd.extend([f"--{k}", str(v)])
    return cmd

def log_contains_done(log_path: Path) -> bool:
    if not log_path.exists():
        return False
    txt = log_path.read_text(encoding="utf-8", errors="ignore")
    return ("### Done ###" in txt) or ("mse:" in txt and "mae:" in txt)

jobs = []
for dataset, model, seed in itertools.product(DATASETS, MODELS, SEEDS):
    jobs.append({"dataset": dataset, "model": model, "seed": seed})

to_run = []
for j in jobs:
    rn = run_name(j["dataset"], j["model"], j["seed"])
    log_path = LOG_ROOT / f"{rn}.log"
    if SKIP_COMPLETED and log_contains_done(log_path):
        continue
    to_run.append(j)

if MAX_RUNS_THIS_SESSION is not None:
    to_run = to_run[:MAX_RUNS_THIS_SESSION]

print("Queued unimodal jobs:", len(to_run))

status_rows = []
status_path = RESULTS_ROOT / "partA_unimodal_status.csv"

for idx, j in enumerate(to_run, 1):
    rn = run_name(j["dataset"], j["model"], j["seed"])
    log_path = LOG_ROOT / f"{rn}.log"
    cmd = build_cmd(j["dataset"], j["model"], j["seed"])

    print("\n" + "="*100)
    print(f"[{idx}/{len(to_run)}] {rn}")
    print("CMD:", " ".join(cmd))
    print("="*100)

    with open(log_path, "w", encoding="utf-8") as f:
        proc = subprocess.Popen(
            cmd,
            cwd=str(REPO_ROOT),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        for line in proc.stdout:
            print(line, end="")
            f.write(line)
        return_code = proc.wait()

    status_rows.append({
        "timestamp": datetime.now().isoformat(),
        "run_name": rn,
        "dataset": j["dataset"],
        "model": j["model"],
        "seed": j["seed"],
        "modality": "uni",
        "return_code": return_code,
        "log_file": str(log_path),
    })
    pd.DataFrame(status_rows).to_csv(status_path, index=False)

print("Saved unimodal status to:", status_path)

Streaming output truncated to the last 5000 lines.
Epoch 5, Loss: 0.15781:  82%|████████▏ | 128/156 [07:29<01:35,  3.41s/it]
Epoch 5, Loss: 0.15781:  83%|████████▎ | 129/156 [07:29<01:34,  3.49s/it]
Epoch 5, Loss: 0.16748:  83%|████████▎ | 129/156 [07:32<01:34,  3.49s/it]
Epoch 5, Loss: 0.16748:  83%|████████▎ | 130/156 [07:32<01:30,  3.50s/it]
Epoch 5, Loss: 0.07155:  83%|████████▎ | 130/156 [07:36<01:30,  3.50s/it]
Epoch 5, Loss: 0.07155:  84%|████████▍ | 131/156 [07:36<01:27,  3.49s/it]
Epoch 5, Loss: 0.11525:  84%|████████▍ | 131/156 [07:39<01:27,  3.49s/it]
Epoch 5, Loss: 0.11525:  85%|████████▍ | 132/156 [07:39<01:23,  3.48s/it]
Epoch 5, Loss: 0.09015:  85%|████████▍ | 132/156 [07:42<01:23,  3.48s/it]
Epoch 5, Loss: 0.09015:  85%|████████▌ | 133/156 [07:42<01:17,  3.35s/it]
Epoch 5, Loss: 0.22426:  85%|████████▌ | 133/156 [07:46<01:17,  3.35s/it]
Epoch 5, Loss: 0.22426:  86%|████████▌ | 134/156 [07:46<01:15,  3.43s/it]
Epoch 5, Loss: 0.16487:  86%|████████▌ | 134/156 [07:49<01:15,  3.43s/it]
Epoch 5, Loss: 0.16487:  87%|████████▋ | 135/156 [07:49<01:11,  3.40s/it]
Epoch 5, Loss: 0.19698:  87%|████████▋ | 135/156 [07:52<01:11,  3.40s/it]
Epoch 5, Loss: 0.19698:  87%|████████▋ | 136/156 [07:52<01:08,  3.43s/it]
Epoch 5, Loss: 0.06866:  87%|████████▋ | 136/156 [07:56<01:08,  3.43s/it]
Epoch 5, Loss: 0.06866:  88%|████████▊ | 137/156 [07:56<01:03,  3.34s/it]
Epoch 5, Loss: 0.10556:  88%|████████▊ | 137/156 [07:59<01:03,  3.34s/it]
Epoch 5, Loss: 0.10556:  88%|████████▊ | 138/156 [07:59<01:01,  3.43s/it]
Epoch 5, Loss: 0.15944:  88%|████████▊ | 138/156 [08:03<01:01,  3.43s/it]
Epoch 5, Loss: 0.15944:  89%|████████▉ | 139/156 [08:03<00:58,  3.41s/it]
Epoch 5, Loss: 0.04929:  89%|████████▉ | 139/156 [08:06<00:58,  3.41s/it]
Epoch 5, Loss: 0.04929:  90%|████████▉ | 140/156 [08:06<00:54,  3.40s/it]
Epoch 5, Loss: 0.06956:  90%|████████▉ | 140/156 [08:10<00:54,  3.40s/it]
Epoch 5, Loss: 0.06956:  90%|█████████ | 141/156 [08:10<00:51,  3.47s/it]
Epoch 5, Loss: 0.15948:  90%|█████████ | 141/156 [08:13<00:51,  3.47s/it]
Epoch 5, Loss: 0.15948:  91%|█████████ | 142/156 [08:13<00:49,  3.55s/it]
Epoch 5, Loss: 0.40440:  91%|█████████ | 142/156 [08:17<00:49,  3.55s/it]
Epoch 5, Loss: 0.40440:  92%|█████████▏| 143/156 [08:17<00:45,  3.48s/it]
Epoch 5, Loss: 0.10942:  92%|█████████▏| 143/156 [08:20<00:45,  3.48s/it]
Epoch 5, Loss: 0.10942:  92%|█████████▏| 144/156 [08:20<00:41,  3.49s/it]
Epoch 5, Loss: 0.17629:  92%|█████████▏| 144/156 [08:24<00:41,  3.49s/it]
Epoch 5, Loss: 0.17629:  93%|█████████▎| 145/156 [08:24<00:39,  3.59s/it]
Epoch 5, Loss: 0.14000:  93%|█████████▎| 145/156 [08:27<00:39,  3.59s/it]
Epoch 5, Loss: 0.14000:  94%|█████████▎| 146/156 [08:27<00:35,  3.51s/it]
Epoch 5, Loss: 0.20303:  94%|█████████▎| 146/156 [08:31<00:35,  3.51s/it]
Epoch 5, Loss: 0.20303:  94%|█████████▍| 147/156 [08:31<00:30,  3.43s/it]
Epoch 5, Loss: 0.11106:  94%|█████████▍| 147/156 [08:34<00:30,  3.43s/it]
Epoch 5, Loss: 0.11106:  95%|█████████▍| 148/156 [08:34<00:27,  3.46s/it]
Epoch 5, Loss: 1.30071:  95%|█████████▍| 148/156 [08:38<00:27,  3.46s/it]
Epoch 5, Loss: 1.30071:  96%|█████████▌| 149/156 [08:38<00:24,  3.57s/it]
Epoch 5, Loss: 0.12296:  96%|█████████▌| 149/156 [08:41<00:24,  3.57s/it]
Epoch 5, Loss: 0.12296:  96%|█████████▌| 150/156 [08:41<00:20,  3.47s/it]
Epoch 5, Loss: 0.14708:  96%|█████████▌| 150/156 [08:45<00:20,  3.47s/it]
Epoch 5, Loss: 0.14708:  97%|█████████▋| 151/156 [08:45<00:17,  3.45s/it]
Epoch 5, Loss: 0.22391:  97%|█████████▋| 151/156 [08:48<00:17,  3.45s/it]
Epoch 5, Loss: 0.22391:  97%|█████████▋| 152/156 [08:48<00:13,  3.48s/it]
Epoch 5, Loss: 0.24269:  97%|█████████▋| 152/156 [08:52<00:13,  3.48s/it]
Epoch 5, Loss: 0.24269:  98%|█████████▊| 153/156 [08:52<00:10,  3.59s/it]
Epoch 5, Loss: 0.05577:  98%|█████████▊| 153/156 [08:55<00:10,  3.59s/it]
Epoch 5, Loss: 0.05577:  99%|█████████▊| 154/156 [08:55<00:06,  3.45s/it]
Epoch 5, Loss: 0.27075:  99%|█████████▊| 154/156 [08:59<00:06,  3.45s/it]
Epoch 5, Loss: 0.27075:  99%|█████████▉| 155/156 [08:59<00:03,  3.49s/it]
Epoch 5, Loss: 0.11396:  99%|█████████▉| 155/156 [09:02<00:03,  3.49s/it]
Epoch 5, Loss: 0.11396: 100%|██████████| 156/156 [09:02<00:00,  3.54s/it]
Epoch 5, Loss: 0.11396: 100%|██████████| 156/156 [09:02<00:00,  3.48s/it]

  0%|          | 0/49 [00:00<?, ?it/s]
  2%|▏         | 1/49 [00:00<00:06,  7.87it/s]
  4%|▍         | 2/49 [00:00<00:06,  7.57it/s]
  6%|▌         | 3/49 [00:00<00:06,  7.55it/s]
  8%|▊         | 4/49 [00:00<00:06,  7.50it/s]
 10%|█         | 5/49 [00:00<00:05,  7.53it/s]
 12%|█▏        | 6/49 [00:00<00:05,  7.61it/s]
 14%|█▍        | 7/49 [00:00<00:05,  7.58it/s]
 16%|█▋        | 8/49 [00:01<00:05,  7.55it/s]
 18%|█▊        | 9/49 [00:01<00:05,  7.54it/s]
 20%|██        | 10/49 [00:01<00:05,  7.43it/s]
 22%|██▏       | 11/49 [00:01<00:05,  7.46it/s]
 24%|██▍       | 12/49 [00:01<00:04,  7.51it/s]
 27%|██▋       | 13/49 [00:01<00:04,  7.51it/s]
 29%|██▊       | 14/49 [00:01<00:04,  7.50it/s]
 31%|███       | 15/49 [00:01<00:04,  7.50it/s]
 33%|███▎      | 16/49 [00:02<00:04,  7.47it/s]
 35%|███▍      | 17/49 [00:02<00:04,  7.47it/s]
 37%|███▋      | 18/49 [00:02<00:04,  7.47it/s]
 39%|███▉      | 19/49 [00:02<00:03,  7.50it/s]
 41%|████      | 20/49 [00:02<00:03,  7.61it/s]
 43%|████▎     | 21/49 [00:02<00:03,  7.56it/s]
 45%|████▍     | 22/49 [00:02<00:03,  7.53it/s]
 47%|████▋     | 23/49 [00:03<00:03,  7.55it/s]
 49%|████▉     | 24/49 [00:03<00:03,  7.55it/s]
 51%|█████     | 25/49 [00:03<00:03,  7.48it/s]
 53%|█████▎    | 26/49 [00:03<00:03,  7.37it/s]
 55%|█████▌    | 27/49 [00:03<00:02,  7.42it/s]
 57%|█████▋    | 28/49 [00:03<00:02,  7.35it/s]
 59%|█████▉    | 29/49 [00:03<00:02,  7.39it/s]
 61%|██████    | 30/49 [00:03<00:02,  7.51it/s]
 63%|██████▎   | 31/49 [00:04<00:02,  7.53it/s]
 65%|██████▌   | 32/49 [00:04<00:02,  7.50it/s]
 67%|██████▋   | 33/49 [00:04<00:02,  7.51it/s]
 69%|██████▉   | 34/49 [00:04<00:01,  7.57it/s]
 71%|███████▏  | 35/49 [00:04<00:01,  7.57it/s]
 73%|███████▎  | 36/49 [00:04<00:01,  7.53it/s]
 76%|███████▌  | 37/49 [00:04<00:01,  7.51it/s]
 78%|███████▊  | 38/49 [00:05<00:01,  7.51it/s]
 80%|███████▉  | 39/49 [00:05<00:01,  7.52it/s]
 82%|████████▏ | 40/49 [00:05<00:01,  7.42it/s]
 84%|████████▎ | 41/49 [00:05<00:01,  7.48it/s]
 86%|████████▌ | 42/49 [00:05<00:00,  7.47it/s]
 88%|████████▊ | 43/49 [00:05<00:00,  7.39it/s]
 90%|████████▉ | 44/49 [00:05<00:00,  7.46it/s]
 92%|█████████▏| 45/49 [00:06<00:00,  7.40it/s]
 94%|█████████▍| 46/49 [00:06<00:00,  7.38it/s]
 96%|█████████▌| 47/49 [00:06<00:00,  7.33it/s]
 98%|█████████▊| 48/49 [00:06<00:00,  7.32it/s]
100%|██████████| 49/49 [00:06<00:00,  7.40it/s]
100%|██████████| 49/49 [00:06<00:00,  7.48it/s]
- Epoch 005, ExpID 59124
Train - Loss (one batch): 0.11396
Val - Loss, MSE, MAE: 0.18245, 0.18245, 0.23101
Test - Best epoch, Loss, MSE, MAE: 4, 0.15626, 0.15626, 0.16917
Time spent: 549.38s

Training:   0%|          | 0/156 [00:00<?, ?it/s]
Epoch 6, Loss: 0.05679:   0%|          | 0/156 [00:03<?, ?it/s]
Epoch 6, Loss: 0.05679:   1%|          | 1/156 [00:03<08:40,  3.36s/it]
Epoch 6, Loss: 0.09821:   1%|          | 1/156 [00:07<08:40,  3.36s/it]
Epoch 6, Loss: 0.09821:   1%|▏         | 2/156 [00:07<09:11,  3.58s/it]
Epoch 6, Loss: 0.21669:   1%|▏         | 2/156 [00:10<09:11,  3.58s/it]
Epoch 6, Loss: 0.21669:   2%|▏         | 3/156 [00:10<09:14,  3.63s/it]
Epoch 6, Loss: 0.09625:   2%|▏         | 3/156 [00:14<09:14,  3.63s/it]
Epoch 6, Loss: 0.09625:   3%|▎         | 4/156 [00:14<08:59,  3.55s/it]
Epoch 6, Loss: 0.12689:   3%|▎         | 4/156 [00:17<08:59,  3.55s/it]
Epoch 6, Loss: 0.12689:   3%|▎         | 5/156 [00:17<09:05,  3.62s/it]
Epoch 6, Loss: 0.13248:   3%|▎         | 5/156 [00:21<09:05,  3.62s/it]
Epoch 6, Loss: 0.13248:   4%|▍         | 6/156 [00:21<08:53,  3.56s/it]
Epoch 6, Loss: 0.29571:   4%|▍         | 6/156 [00:24<08:53,  3.56s/it]
Epoch 6, Loss: 0.29571:   4%|▍         | 7/156 [00:24<08:34,  3.46s/it]
Epoch 6, Loss: 0.28609:   4%|▍         | 7/156 [00:27<08:34,  3.46s/it]
Epoch 6, Loss: 0.28609:   5%|▌         | 8/156 [00:27<08:18,  3.37s/it]
Epoch 6, Loss: 0.19110:   5%|▌         | 8/156 [00:31<08:18,  3.37s/it]
Epoch 6, Loss: 0.19110:   6%|▌         | 9/156 [00:31<08:37,  3.52s/it]
Epoch 6, Loss: 0.17545:   6%|▌         | 9/156 [00:35<08:37,  3.52s/it]
Epoch 6, Loss: 0.17545:   6%|▋         | 10/156 [00:35<08:35,  3.53s/it]
Epoch 6, Loss: 0.16251:   6%|▋         | 10/156 [00:38<08:35,  3.53s/it]
Epoch 6, Loss: 0.16251:   7%|▋         | 11/156 [00:38<08:15,  3.42s/it]
Epoch 6, Loss: 0.33669:   7%|▋         | 11/156 [00:42<08:15,  3.42s/it]
Epoch 6, Loss: 0.33669:   8%|▊         | 12/156 [00:42<08:23,  3.50s/it]
Epoch 6, Loss: 0.10007:   8%|▊         | 12/156 [00:45<08:23,  3.50s/it]
Epoch 6, Loss: 0.10007:   8%|▊         | 13/156 [00:45<08:17,  3.48s/it]
Epoch 6, Loss: 0.12206:   8%|▊         | 13/156 [00:48<08:17,  3.48s/it]
Epoch 6, Loss: 0.12206:   9%|▉         | 14/156 [00:48<08:09,  3.44s/it]
Epoch 6, Loss: 0.27184:   9%|▉         | 14/156 [00:52<08:09,  3.44s/it]
Epoch 6, Loss: 0.27184:  10%|▉         | 15/156 [00:52<07:56,  3.38s/it]
Epoch 6, Loss: 0.26046:  10%|▉         | 15/156 [00:55<07:56,  3.38s/it]
Epoch 6, Loss: 0.26046:  10%|█         | 16/156 [00:55<08:15,  3.54s/it]
Epoch 6, Loss: 0.14203:  10%|█         | 16/156 [00:59<08:15,  3.54s/it]
Epoch 6, Loss: 0.14203:  11%|█         | 17/156 [00:59<08:11,  3.53s/it]
Epoch 6, Loss: 0.10945:  11%|█         | 17/156 [01:02<08:11,  3.53s/it]
Epoch 6, Loss: 0.10945:  12%|█▏        | 18/156 [01:02<07:59,  3.48s/it]
Epoch 6, Loss: 0.18532:  12%|█▏        | 18/156 [01:06<07:59,  3.48s/it]
Epoch 6, Loss: 0.18532:  12%|█▏        | 19/156 [01:06<07:47,  3.41s/it]
Epoch 6, Loss: 0.31092:  12%|█▏        | 19/156 [01:09<07:47,  3.41s/it]
Epoch 6, Loss: 0.31092:  13%|█▎        | 20/156 [01:09<07:48,  3.45s/it]
Epoch 6, Loss: 0.16111:  13%|█▎        | 20/156 [01:12<07:48,  3.45s/it]
Epoch 6, Loss: 0.16111:  13%|█▎        | 21/156 [01:12<07:32,  3.35s/it]
Epoch 6, Loss: 0.19619:  13%|█▎        | 21/156 [01:15<07:32,  3.35s/it]
Epoch 6, Loss: 0.19619:  14%|█▍        | 22/156 [01:15<07:23,  3.31s/it]
Epoch 6, Loss: 0.13816:  14%|█▍        | 22/156 [01:19<07:23,  3.31s/it]
Epoch 6, Loss: 0.13816:  15%|█▍        | 23/156 [01:19<07:40,  3.46s/it]
Epoch 6, Loss: 0.69203:  15%|█▍        | 23/156 [01:23<07:40,  3.46s/it]
Epoch 6, Loss: 0.69203:  15%|█▌        | 24/156 [01:23<07:35,  3.45s/it]
Epoch 6, Loss: 0.09505:  15%|█▌        | 24/156 [01:26<07:35,  3.45s/it]
Epoch 6, Loss: 0.09505:  16%|█▌        | 25/156 [01:26<07:27,  3.41s/it]
Epoch 6, Loss: 0.09254:  16%|█▌        | 25/156 [01:30<07:27,  3.41s/it]
Epoch 6, Loss: 0.09254:  17%|█▋        | 26/156 [01:30<07:27,  3.44s/it]
Epoch 6, Loss: 0.21086:  17%|█▋        | 26/156 [01:33<07:27,  3.44s/it]
Epoch 6, Loss: 0.21086:  17%|█▋        | 27/156 [01:33<07:31,  3.50s/it]
Epoch 6, Loss: 0.11268:  17%|█▋        | 27/156 [01:37<07:31,  3.50s/it]
Epoch 6, Loss: 0.11268:  18%|█▊        | 28/156 [01:37<07:32,  3.53s/it]
Epoch 6, Loss: 0.18498:  18%|█▊        | 28/156 [01:40<07:32,  3.53s/it]
Epoch 6, Loss: 0.18498:  19%|█▊        | 29/156 [01:40<07:21,  3.47s/it]
Epoch 6, Loss: 0.08525:  19%|█▊        | 29/156 [01:44<07:21,  3.47s/it]
Epoch 6, Loss: 0.08525:  19%|█▉        | 30/156 [01:44<07:17,  3.47s/it]
Epoch 6, Loss: 0.07186:  19%|█▉        | 30/156 [01:47<07:17,  3.47s/it]
Epoch 6, Loss: 0.07186:  20%|█▉        | 31/156 [01:47<07:11,  3.45s/it]
Epoch 6, Loss: 0.15638:  20%|█▉        | 31/156 [01:50<07:11,  3.45s/it]
Epoch 6, Loss: 0.15638:  21%|██        | 32/156 [01:50<07:01,  3.40s/it]
Epoch 6, Loss: 0.26134:  21%|██        | 32/156 [01:54<07:01,  3.40s/it]
Epoch 6, Loss: 0.26134:  21%|██        | 33/156 [01:54<06:58,  3.40s/it]
Epoch 6, Loss: 0.20927:  21%|██        | 33/156 [01:57<06:58,  3.40s/it]
Epoch 6, Loss: 0.20927:  22%|██▏       | 34/156 [01:57<07:04,  3.48s/it]
Epoch 6, Loss: 0.21035:  22%|██▏       | 34/156 [02:01<07:04,  3.48s/it]
Epoch 6, Loss: 0.21035:  22%|██▏       | 35/156 [02:01<06:53,  3.42s/it]
Epoch 6, Loss: 0.22708:  22%|██▏       | 35/156 [02:04<06:53,  3.42s/it]
Epoch 6, Loss: 0.22708:  23%|██▎       | 36/156 [02:04<06:51,  3.43s/it]
Epoch 6, Loss: 0.07997:  23%|██▎       | 36/156 [02:08<06:51,  3.43s/it]
Epoch 6, Loss: 0.07997:  24%|██▎       | 37/156 [02:08<06:53,  3.48s/it]
Epoch 6, Loss: 0.16955:  24%|██▎       | 37/156 [02:11<06:53,  3.48s/it]
Epoch 6, Loss: 0.16955:  24%|██▍       | 38/156 [02:11<06:54,  3.51s/it]
Epoch 6, Loss: 0.12442:  24%|██▍       | 38/156 [02:15<06:54,  3.51s/it]
Epoch 6, Loss: 0.12442:  25%|██▌       | 39/156 [02:15<06:48,  3.49s/it]
Epoch 6, Loss: 0.14458:  25%|██▌       | 39/156 [02:18<06:48,  3.49s/it]
Epoch 6, Loss: 0.14458:  26%|██▌       | 40/156 [02:18<06:39,  3.45s/it]
Epoch 6, Loss: 0.19890:  26%|██▌       | 40/156 [02:22<06:39,  3.45s/it]
Epoch 6, Loss: 0.19890:  26%|██▋       | 41/156 [02:22<06:39,  3.47s/it]
Epoch 6, Loss: 0.29758:  26%|██▋       | 41/156 [02:25<06:39,  3.47s/it]
Epoch 6, Loss: 0.29758:  27%|██▋       | 42/156 [02:25<06:34,  3.46s/it]
Epoch 6, Loss: 0.26058:  27%|██▋       | 42/156 [02:28<06:34,  3.46s/it]
Epoch 6, Loss: 0.26058:  28%|██▊       | 43/156 [02:28<06:29,  3.45s/it]
Epoch 6, Loss: 0.15524:  28%|██▊       | 43/156 [02:32<06:29,  3.45s/it]
Epoch 6, Loss: 0.15524:  28%|██▊       | 44/156 [02:32<06:18,  3.38s/it]
Epoch 6, Loss: 0.10932:  28%|██▊       | 44/156 [02:35<06:18,  3.38s/it]
Epoch 6, Loss: 0.10932:  29%|██▉       | 45/156 [02:35<06:24,  3.46s/it]
Epoch 6, Loss: 0.14439:  29%|██▉       | 45/156 [02:39<06:24,  3.46s/it]
Epoch 6, Loss: 0.14439:  29%|██▉       | 46/156 [02:39<06:39,  3.64s/it]
Epoch 6, Loss: 0.29423:  29%|██▉       | 46/156 [02:43<06:39,  3.64s/it]
Epoch 6, Loss: 0.29423:  30%|███       | 47/156 [02:43<06:25,  3.54s/it]
Epoch 6, Loss: 0.37932:  30%|███       | 47/156 [02:46<06:25,  3.54s/it]
Epoch 6, Loss: 0.37932:  31%|███       | 48/156 [02:46<06:22,  3.54s/it]
Epoch 6, Loss: 0.16504:  31%|███       | 48/156 [02:50<06:22,  3.54s/it]
Epoch 6, Loss: 0.16504:  31%|███▏      | 49/156 [02:50<06:26,  3.61s/it]
Epoch 6, Loss: 0.08097:  31%|███▏      | 49/156 [02:53<06:26,  3.61s/it]
Epoch 6, Loss: 0.08097:  32%|███▏      | 50/156 [02:53<06:14,  3.53s/it]
Epoch 6, Loss: 0.13027:  32%|███▏      | 50/156 [02:57<06:14,  3.53s/it]
Epoch 6, Loss: 0.13027:  33%|███▎      | 51/156 [02:57<06:08,  3.51s/it]
Epoch 6, Loss: 0.29417:  33%|███▎      | 51/156 [03:01<06:08,  3.51s/it]
Epoch 6, Loss: 0.29417:  33%|███▎      | 52/156 [03:01<06:19,  3.65s/it]
Epoch 6, Loss: 0.09439:  33%|███▎      | 52/156 [03:04<06:19,  3.65s/it]
Epoch 6, Loss: 0.09439:  34%|███▍      | 53/156 [03:04<06:02,  3.52s/it]
Epoch 6, Loss: 0.12772:  34%|███▍      | 53/156 [03:08<06:02,  3.52s/it]
Epoch 6, Loss: 0.12772:  35%|███▍      | 54/156 [03:08<06:00,  3.54s/it]
Epoch 6, Loss: 0.20505:  35%|███▍      | 54/156 [03:11<06:00,  3.54s/it]
Epoch 6, Loss: 0.20505:  35%|███▌      | 55/156 [03:11<05:53,  3.50s/it]
Epoch 6, Loss: 0.10030:  35%|███▌      | 55/156 [03:15<05:53,  3.50s/it]
Epoch 6, Loss: 0.10030:  36%|███▌      | 56/156 [03:15<05:53,  3.54s/it]
Epoch 6, Loss: 0.10669:  36%|███▌      | 56/156 [03:18<05:53,  3.54s/it]
Epoch 6, Loss: 0.10669:  37%|███▋      | 57/156 [03:18<05:43,  3.47s/it]
Epoch 6, Loss: 0.24832:  37%|███▋      | 57/156 [03:21<05:43,  3.47s/it]
Epoch 6, Loss: 0.24832:  37%|███▋      | 58/156 [03:21<05:30,  3.38s/it]
Epoch 6, Loss: 0.20310:  37%|███▋      | 58/156 [03:25<05:30,  3.38s/it]
Epoch 6, Loss: 0.20310:  38%|███▊      | 59/156 [03:25<05:41,  3.52s/it]
Epoch 6, Loss: 0.06153:  38%|███▊      | 59/156 [03:29<05:41,  3.52s/it]
Epoch 6, Loss: 0.06153:  38%|███▊      | 60/156 [03:29<05:44,  3.59s/it]
Epoch 6, Loss: 0.28487:  38%|███▊      | 60/156 [03:32<05:44,  3.59s/it]
Epoch 6, Loss: 0.28487:  39%|███▉      | 61/156 [03:32<05:34,  3.52s/it]
Epoch 6, Loss: 0.09009:  39%|███▉      | 61/156 [03:36<05:34,  3.52s/it]
Epoch 6, Loss: 0.09009:  40%|███▉      | 62/156 [03:36<05:32,  3.54s/it]
Epoch 6, Loss: 0.27036:  40%|███▉      | 62/156 [03:40<05:32,  3.54s/it]
Epoch 6, Loss: 0.27036:  40%|████      | 63/156 [03:40<05:51,  3.78s/it]
Epoch 6, Loss: 0.14623:  40%|████      | 63/156 [03:44<05:51,  3.78s/it]
Epoch 6, Loss: 0.14623:  41%|████      | 64/156 [03:44<05:48,  3.78s/it]
Epoch 6, Loss: 0.14735:  41%|████      | 64/156 [03:47<05:48,  3.78s/it]
Epoch 6, Loss: 0.14735:  42%|████▏     | 65/156 [03:47<05:40,  3.75s/it]
Epoch 6, Loss: 0.24255:  42%|████▏     | 65/156 [03:51<05:40,  3.75s/it]
Epoch 6, Loss: 0.24255:  42%|████▏     | 66/156 [03:51<05:36,  3.74s/it]
Epoch 6, Loss: 0.08741:  42%|████▏     | 66/156 [03:54<05:36,  3.74s/it]
Epoch 6, Loss: 0.08741:  43%|████▎     | 67/156 [03:54<05:19,  3.59s/it]
Epoch 6, Loss: 0.30895:  43%|████▎     | 67/156 [03:58<05:19,  3.59s/it]
Epoch 6, Loss: 0.30895:  44%|████▎     | 68/156 [03:58<05:05,  3.47s/it]
Epoch 6, Loss: 0.24705:  44%|████▎     | 68/156 [04:01<05:05,  3.47s/it]
Epoch 6, Loss: 0.24705:  44%|████▍     | 69/156 [04:01<04:58,  3.43s/it]
Epoch 6, Loss: 0.09872:  44%|████▍     | 69/156 [04:04<04:58,  3.43s/it]
Epoch 6, Loss: 0.09872:  45%|████▍     | 70/156 [04:04<04:57,  3.46s/it]
Epoch 6, Loss: 0.23012:  45%|████▍     | 70/156 [04:08<04:57,  3.46s/it]
Epoch 6, Loss: 0.23012:  46%|████▌     | 71/156 [04:08<04:54,  3.46s/it]
Epoch 6, Loss: 0.14055:  46%|████▌     | 71/156 [04:11<04:54,  3.46s/it]
Epoch 6, Loss: 0.14055:  46%|████▌     | 72/156 [04:11<04:43,  3.37s/it]
Epoch 6, Loss: 0.11015:  46%|████▌     | 72/156 [04:15<04:43,  3.37s/it]
Epoch 6, Loss: 0.11015:  47%|████▋     | 73/156 [04:15<04:45,  3.44s/it]
Epoch 6, Loss: 0.11452:  47%|████▋     | 73/156 [04:18<04:45,  3.44s/it]
Epoch 6, Loss: 0.11452:  47%|████▋     | 74/156 [04:18<04:38,  3.39s/it]
Epoch 6, Loss: 0.19252:  47%|████▋     | 74/156 [04:21<04:38,  3.39s/it]
Epoch 6, Loss: 0.19252:  48%|████▊     | 75/156 [04:21<04:34,  3.39s/it]
Epoch 6, Loss: 0.09734:  48%|████▊     | 75/156 [04:25<04:34,  3.39s/it]
Epoch 6, Loss: 0.09734:  49%|████▊     | 76/156 [04:25<04:29,  3.37s/it]
Epoch 6, Loss: 0.06931:  49%|████▊     | 76/156 [04:28<04:29,  3.37s/it]
Epoch 6, Loss: 0.06931:  49%|████▉     | 77/156 [04:28<04:33,  3.46s/it]
Epoch 6, Loss: 0.10371:  49%|████▉     | 77/156 [04:31<04:33,  3.46s/it]
Epoch 6, Loss: 0.10371:  50%|█████     | 78/156 [04:31<04:22,  3.36s/it]
Epoch 6, Loss: 0.21193:  50%|█████     | 78/156 [04:35<04:22,  3.36s/it]
Epoch 6, Loss: 0.21193:  51%|█████     | 79/156 [04:35<04:21,  3.39s/it]
Epoch 6, Loss: 0.08402:  51%|█████     | 79/156 [04:38<04:21,  3.39s/it]
Epoch 6, Loss: 0.08402:  51%|█████▏    | 80/156 [04:38<04:19,  3.41s/it]
Epoch 6, Loss: 0.18783:  51%|█████▏    | 80/156 [04:42<04:19,  3.41s/it]
Epoch 6, Loss: 0.18783:  52%|█████▏    | 81/156 [04:42<04:23,  3.51s/it]
Epoch 6, Loss: 0.21353:  52%|█████▏    | 81/156 [04:46<04:23,  3.51s/it]
Epoch 6, Loss: 0.21353:  53%|█████▎    | 82/156 [04:46<04:34,  3.71s/it]
Epoch 6, Loss: 0.11038:  53%|█████▎    | 82/156 [04:50<04:34,  3.71s/it]
Epoch 6, Loss: 0.11038:  53%|█████▎    | 83/156 [04:50<04:24,  3.63s/it]
Epoch 6, Loss: 0.17573:  53%|█████▎    | 83/156 [04:54<04:24,  3.63s/it]
Epoch 6, Loss: 0.17573:  54%|█████▍    | 84/156 [04:54<04:28,  3.72s/it]
Epoch 6, Loss: 0.11725:  54%|█████▍    | 84/156 [04:57<04:28,  3.72s/it]
Epoch 6, Loss: 0.11725:  54%|█████▍    | 85/156 [04:57<04:12,  3.56s/it]
Epoch 6, Loss: 0.08199:  54%|█████▍    | 85/156 [05:00<04:12,  3.56s/it]
Epoch 6, Loss: 0.08199:  55%|█████▌    | 86/156 [05:00<04:02,  3.46s/it]
Epoch 6, Loss: 0.23172:  55%|█████▌    | 86/156 [05:03<04:02,  3.46s/it]
Epoch 6, Loss: 0.23172:  56%|█████▌    | 87/156 [05:03<03:57,  3.44s/it]
Epoch 6, Loss: 0.10949:  56%|█████▌    | 87/156 [05:07<03:57,  3.44s/it]
Epoch 6, Loss: 0.10949:  56%|█████▋    | 88/156 [05:07<03:56,  3.48s/it]
Epoch 6, Loss: 0.08763:  56%|█████▋    | 88/156 [05:10<03:56,  3.48s/it]
Epoch 6, Loss: 0.08763:  57%|█████▋    | 89/156 [05:10<03:47,  3.40s/it]
Epoch 6, Loss: 0.08900:  57%|█████▋    | 89/156 [05:14<03:47,  3.40s/it]

In [ ]:
from pathlib import Path
import pandas as pd
import os

REPO_ROOT = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF")
DATASETS = ["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"]
ENCODERS = {
    "GPT2": "text_embeddings_model=GPT2_layers=6_maxlen=1024.pt",
    "BERT": "text_embeddings_model=BERT_layers=6_maxlen=512.pt",
    "Llama": "text_embeddings_model=Llama_layers=6_maxlen=1024.pt",
    "DeepSeek": "text_embeddings_model=DeepSeek_layers=6_maxlen=1024.pt",
}

rows = []

for dataset in DATASETS:
    proc_root = REPO_ROOT / "data" / dataset / "processed"
    if not proc_root.exists():
        rows.append({
            "dataset": dataset,
            "record_dir": None,
            "encoder": None,
            "exists": False,
            "note": "processed folder missing"
        })
        continue

    subdirs = [d for d in proc_root.iterdir() if d.is_dir()]
    for subdir in subdirs:
        for enc, fname in ENCODERS.items():
            rows.append({
                "dataset": dataset,
                "record_dir": subdir.name,
                "encoder": enc,
                "exists": (subdir / fname).exists(),
                "note": ""
            })

embed_df = pd.DataFrame(rows)
display(embed_df.head(20))
print(embed_df.groupby(["dataset", "encoder"])["exists"].mean().reset_index())

In [ ]:
import subprocess

REPO_ROOT = "/content/drive/MyDrive/time_imm_project/IMM-TSF"

def run_embed(llm_name: str):
    print(f"\n=== Generating embeddings for {llm_name} ===")
    cmd = ["/usr/bin/python3", "compute_text_embeddings.py", "--llm_model", llm_name]
    return subprocess.run(cmd, cwd=REPO_ROOT, text=True).returncode

# Start with GPT2
code = run_embed("GPT2")
print("Exit code:", code)

In [ ]:
code = run_embed("BERT")
print("Exit code:", code)

In [ ]:
code = run_embed("Llama")
print("Exit code:", code)

In [ ]:
code = run_embed("DeepSeek")
print("Exit code:", code)

In [ ]:
%cd /content/drive/MyDrive/time_imm_project/IMM-TSF
!pwd
!ls

In [ ]:
from pathlib import Path
import shutil

embed_path = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF/compute_text_embeddings.py")
backup_path = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF/compute_text_embeddings_backup_before_partA_patch.py")

if embed_path.exists() and not backup_path.exists():
    shutil.copy(embed_path, backup_path)
    print(f"Backup created: {backup_path}")
else:
    print("Backup already exists or source file missing.")

In [ ]:
from pathlib import Path
import re

embed_path = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF/compute_text_embeddings.py")
text = embed_path.read_text(encoding="utf-8")

# Force absolute processed path if the script uses a relative one
text = text.replace(
    'base_dir = f"data/{data_name}/processed"',
    'base_dir = rf"/content/drive/MyDrive/time_imm_project/IMM-TSF/data/{data_name}/processed"'
)

# Sometimes the file may use single quotes instead
text = text.replace(
    "base_dir = f'data/{data_name}/processed'",
    "base_dir = rf'/content/drive/MyDrive/time_imm_project/IMM-TSF/data/{data_name}/processed'"
)

embed_path.write_text(text, encoding="utf-8")
print("Patched compute_text_embeddings.py to use the correct absolute data path.")

In [ ]:
from pathlib import Path
import re

EMBED_SCRIPT = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF/compute_text_embeddings.py")

def patch_embed_script(datasets, llm_name, llm_layers=6):
    text = EMBED_SCRIPT.read_text(encoding="utf-8")

    # Restrict datasets
    text = re.sub(
        r"data_name_list\s*=\s*\[[^\]]*\]",
        f"data_name_list = {datasets!r}",
        text,
        flags=re.DOTALL
    )

    # Force llm layers for fusion-style file naming
    text = re.sub(
        r"llm_layers_fusion\s*=\s*None",
        f"llm_layers_fusion = {llm_layers}",
        text
    )

    # If the script stores llm model in a variable, patch that too when possible
    text = re.sub(
        r'llm_model\s*=\s*"[^"]+"',
        f'llm_model = "{llm_name}"',
        text
    )
    text = re.sub(
        r"llm_model\s*=\s*'[^']+'",
        f"llm_model = '{llm_name}'",
        text
    )

    EMBED_SCRIPT.write_text(text, encoding="utf-8")
    print(f"Patched embedding script for datasets={datasets} and llm={llm_name}, layers={llm_layers}")

In [ ]:
patch_embed_script(
    datasets=["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"],
    llm_name="GPT2",
    llm_layers=6
)

!cd /content/drive/MyDrive/time_imm_project/IMM-TSF && /usr/bin/python3 compute_text_embeddings.py --llm_model GPT2

In [ ]:
from pathlib import Path

root = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF/data")
for ds in ["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"]:
    files = list(root.glob(f"{ds}/processed/**/text_embeddings_model=GPT2_layers=6_maxlen=1024.pt"))
    print(ds, "GPT2 embedding files:", len(files))
    for f in files[:3]:
        print("  ", f)

In [ ]:
patch_embed_script(
    datasets=["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"],
    llm_name="BERT",
    llm_layers=6
)

!cd /content/drive/MyDrive/time_imm_project/IMM-TSF && /usr/bin/python3 compute_text_embeddings.py --llm_model BERT

In [ ]:
from pathlib import Path

root = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF/data")
for ds in ["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"]:
    files = list(root.glob(f"{ds}/processed/**/text_embeddings_model=BERT_layers=6_maxlen=512.pt"))
    print(ds, "BERT embedding files:", len(files))

In [ ]:
patch_embed_script(
    datasets=["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"],
    llm_name="Llama",
    llm_layers=6
)

!cd /content/drive/MyDrive/time_imm_project/IMM-TSF && /usr/bin/python3 compute_text_embeddings.py --llm_model Llama

In [ ]:
from pathlib import Path

root = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF/data")
for ds in ["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"]:
    files = list(root.glob(f"{ds}/processed/**/text_embeddings_model=Llama_layers=6_maxlen=1024.pt"))
    print(ds, "Llama embedding files:", len(files))

In [ ]:
patch_embed_script(
    datasets=["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"],
    llm_name="DeepSeek",
    llm_layers=6
)

!cd /content/drive/MyDrive/time_imm_project/IMM-TSF && /usr/bin/python3 compute_text_embeddings.py --llm_model DeepSeek

In [ ]:
from pathlib import Path

root = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF/data")
for ds in ["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"]:
    files = list(root.glob(f"{ds}/processed/**/text_embeddings_model=DeepSeek_layers=6_maxlen=1024.pt"))
    print(ds, "DeepSeek embedding files:", len(files))

In [ ]:
from pathlib import Path
import pandas as pd

root = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF/data")

expected = {
    "GPT2": "text_embeddings_model=GPT2_layers=6_maxlen=1024.pt",
    "BERT": "text_embeddings_model=BERT_layers=6_maxlen=512.pt",
    "Llama": "text_embeddings_model=Llama_layers=6_maxlen=1024.pt",
    "DeepSeek": "text_embeddings_model=DeepSeek_layers=6_maxlen=1024.pt",
}

rows = []
for ds in ["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"]:
    proc = root / ds / "processed"
    subdirs = [d for d in proc.iterdir() if d.is_dir()] if proc.exists() else []
    for sub in subdirs:
        for enc, fname in expected.items():
            rows.append({
                "dataset": ds,
                "record_dir": sub.name,
                "encoder": enc,
                "exists": (sub / fname).exists()
            })

df = pd.DataFrame(rows)
display(df.head(20))
print(df.groupby(["dataset", "encoder"])["exists"].mean().reset_index())

In [ ]:
from pathlib import Path
import subprocess
import itertools
import pandas as pd
from datetime import datetime

REPO_ROOT = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF")
LOG_ROOT = REPO_ROOT / "run_logs_full"
RESULTS_ROOT = REPO_ROOT / "results_full"

DATASETS = ["GDELT", "FNSPID", "ClusterTrace", "CESNET", "MIMIC"]
MODELS = [
    "Informer",
    "DLinear",
    "PatchTST",
    "TimesNet",
    "TimeMixer",
    "TimeLLM",
    "TTM",
    "CRU",
    "LatentODE",
    "NeuralFlow",
    "tPatchGNN",
]
ENCODERS = {
    "GPT2": "text_embeddings_model=GPT2_layers=6_maxlen=1024.pt",
    "BERT": "text_embeddings_model=BERT_layers=6_maxlen=512.pt",
    "Llama": "text_embeddings_model=Llama_layers=6_maxlen=1024.pt",
    "DeepSeek": "text_embeddings_model=DeepSeek_layers=6_maxlen=1024.pt",
}
TTF_MODULES = ["TTF_RecAvg", "TTF_T2V_XAttn"]
MMF_MODULES = ["MMF_GR_Add", "MMF_XAttn_Add"]
SEEDS = [42]

BATCH_SIZE = 8
EPOCHS = 20
SPLIT_METHOD = "instance"
MAX_RUNS_THIS_SESSION = 20
SKIP_COMPLETED = True

def model_overrides(model: str, dataset: str) -> dict:
    overrides = {}
    if model == "tPatchGNN":
        overrides.update({
            "patch_size": 24,
            "nlayer": 1,
            "te_dim": 10,
            "node_dim": 10,
            "hid_dim": 32,
        })
        if dataset == "CESNET":
            overrides.update({
                "history": 12,
                "pred_window": 6,
                "stride": 6,
                "patch_size": 6,
                "patch_stride": 6,
                "npatch": 2,
            })
    return overrides

def run_name(dataset, model, seed, ttf, mmf, enc):
    return f"{dataset}__{model}__seed{seed}__multi__{ttf}__{mmf}__{enc}"

def build_cmd(dataset, model, seed, ttf, mmf, enc):
    cmd = [
        "/usr/bin/python3", "main.py",
        "--dataset", dataset,
        "--model", model,
        "--split_method", SPLIT_METHOD,
        "-b", str(BATCH_SIZE),
        "--epoch", str(EPOCHS),
        "--seed", str(seed),
        "--TTF_module", ttf,
        "--MMF_module", mmf,
        "--llm_model_fusion", enc,
        "--use_text_embeddings",
        "--enable_text",
    ]
    ov = model_overrides(model, dataset)
    for k, v in ov.items():
        cmd.extend([f"--{k}", str(v)])
    return cmd

def log_contains_done(log_path: Path) -> bool:
    if not log_path.exists():
        return False
    txt = log_path.read_text(encoding="utf-8", errors="ignore")
    return ("### Done ###" in txt) or ("mse:" in txt and "mae:" in txt)

def embeddings_exist_for_dataset(dataset: str, enc: str) -> bool:
    proc_root = REPO_ROOT / "data" / dataset / "processed"
    if not proc_root.exists():
        return False
    subdirs = [d for d in proc_root.iterdir() if d.is_dir()]
    if not subdirs:
        return False
    fname = ENCODERS[enc]
    return all((subdir / fname).exists() for subdir in subdirs)

jobs = []
for dataset, model, seed, ttf, mmf, enc in itertools.product(DATASETS, MODELS, SEEDS, TTF_MODULES, MMF_MODULES, ENCODERS.keys()):
    if embeddings_exist_for_dataset(dataset, enc):
        jobs.append({
            "dataset": dataset,
            "model": model,
            "seed": seed,
            "ttf": ttf,
            "mmf": mmf,
            "encoder": enc
        })

to_run = []
for j in jobs:
    rn = run_name(j["dataset"], j["model"], j["seed"], j["ttf"], j["mmf"], j["encoder"])
    log_path = LOG_ROOT / f"{rn}.log"
    if SKIP_COMPLETED and log_contains_done(log_path):
        continue
    to_run.append(j)

if MAX_RUNS_THIS_SESSION is not None:
    to_run = to_run[:MAX_RUNS_THIS_SESSION]

print("Queued multimodal jobs with existing embeddings:", len(to_run))

status_rows = []
status_path = RESULTS_ROOT / "partA_multimodal_status.csv"

for idx, j in enumerate(to_run, 1):
    rn = run_name(j["dataset"], j["model"], j["seed"], j["ttf"], j["mmf"], j["encoder"])
    log_path = LOG_ROOT / f"{rn}.log"
    cmd = build_cmd(j["dataset"], j["model"], j["seed"], j["ttf"], j["mmf"], j["encoder"])

    print("\n" + "="*100)
    print(f"[{idx}/{len(to_run)}] {rn}")
    print("CMD:", " ".join(cmd))
    print("="*100)

    with open(log_path, "w", encoding="utf-8") as f:
        proc = subprocess.Popen(
            cmd,
            cwd=str(REPO_ROOT),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        for line in proc.stdout:
            print(line, end="")
            f.write(line)
        return_code = proc.wait()

    status_rows.append({
        "timestamp": datetime.now().isoformat(),
        "run_name": rn,
        "dataset": j["dataset"],
        "model": j["model"],
        "seed": j["seed"],
        "modality": "multi",
        "ttf_module": j["ttf"],
        "mmf_module": j["mmf"],
        "text_encoder": j["encoder"],
        "return_code": return_code,
        "log_file": str(log_path),
    })
    pd.DataFrame(status_rows).to_csv(status_path, index=False)

print("Saved multimodal status to:", status_path)

In [ ]:
from pathlib import Path
import subprocess
import itertools
import pandas as pd
from datetime import datetime
import numpy as np

REPO_ROOT = Path("/content/drive/MyDrive/time_imm_project/IMM-TSF")
LOG_ROOT = REPO_ROOT / "run_logs_full"
RESULTS_ROOT = REPO_ROOT / "results_full"
LOG_ROOT.mkdir(parents=True, exist_ok=True)
RESULTS_ROOT.mkdir(parents=True, exist_ok=True)

DATASET = "MIMIC"
MODELS = [
    "Informer",
    "DLinear",
    "PatchTST",
    "TimesNet",
    "TimeMixer",
    "TimeLLM",
    "TTM",
    "CRU",
    "LatentODE",
    "NeuralFlow",
    "tPatchGNN",
]
ENCODERS = {
    "GPT2": "text_embeddings_model=GPT2_layers=6_maxlen=1024.pt",
    "BERT": "text_embeddings_model=BERT_layers=6_maxlen=512.pt",
    "Llama": "text_embeddings_model=Llama_layers=6_maxlen=1024.pt",
    "DeepSeek": "text_embeddings_model=DeepSeek_layers=6_maxlen=1024.pt",
}
TTF_MODULES = ["TTF_RecAvg", "TTF_T2V_XAttn"]
MMF_MODULES = ["MMF_GR_Add", "MMF_XAttn_Add"]
SEEDS = [42]

BATCH_SIZE = 8
EPOCHS = 20
SPLIT_METHOD = "instance"
MAX_RUNS_THIS_SESSION = 40
SKIP_COMPLETED = True
FORCE_RERUN_FAILED = False

def model_overrides(model: str, dataset: str) -> dict:
    overrides = {}
    if model == "tPatchGNN":
        overrides.update({
            "patch_size": 24,
            "nlayer": 1,
            "te_dim": 10,
            "node_dim": 10,
            "hid_dim": 32,
        })
    return overrides

def run_name(dataset, model, seed, modality, ttf=None, mmf=None, enc=None):
    parts = [dataset, model, f"seed{seed}", modality]
    if modality == "multi":
        parts.extend([ttf, mmf, enc])
    return "__".join(parts)

def build_cmd(dataset, model, seed, modality, ttf=None, mmf=None, enc=None):
    cmd = [
        "/usr/bin/python3", "main.py",
        "--dataset", dataset,
        "--model", model,
        "--split_method", SPLIT_METHOD,
        "-b", str(BATCH_SIZE),
        "--epoch", str(EPOCHS),
        "--seed", str(seed),
    ]

    ov = model_overrides(model, dataset)
    for k, v in ov.items():
        cmd.extend([f"--{k}", str(v)])

    if modality == "multi":
        cmd.extend([
            "--TTF_module", ttf,
            "--MMF_module", mmf,
            "--llm_model_fusion", enc,
            "--use_text_embeddings",
            "--enable_text",
        ])

    return cmd

def log_contains_done(log_path: Path) -> bool:
    if not log_path.exists():
        return False
    txt = log_path.read_text(encoding="utf-8", errors="ignore")
    return ("### Done ###" in txt) or ("mse:" in txt and "mae:" in txt)

def log_contains_failure(log_path: Path) -> bool:
    if not log_path.exists():
        return False
    txt = log_path.read_text(encoding="utf-8", errors="ignore")
    fail_markers = ["Traceback", "RuntimeError", "ModuleNotFoundError", "FileNotFoundError", "error:"]
    return any(m in txt for m in fail_markers)

def embeddings_exist_for_dataset(dataset: str, enc: str) -> bool:
    proc_root = REPO_ROOT / "data" / dataset / "processed"
    if not proc_root.exists():
        return False
    subdirs = [d for d in proc_root.iterdir() if d.is_dir()]
    if not subdirs:
        return False
    fname = ENCODERS[enc]
    return all((subdir / fname).exists() for subdir in subdirs)

jobs = []

# unimodal
for model, seed in itertools.product(MODELS, SEEDS):
    jobs.append({
        "dataset": DATASET,
        "model": model,
        "seed": seed,
        "modality": "uni",
        "ttf": None,
        "mmf": None,
        "encoder": None
    })

# multimodal only if embeddings exist
for model, seed, ttf, mmf, enc in itertools.product(MODELS, SEEDS, TTF_MODULES, MMF_MODULES, ENCODERS.keys()):
    if embeddings_exist_for_dataset(DATASET, enc):
        jobs.append({
            "dataset": DATASET,
            "model": model,
            "seed": seed,
            "modality": "multi",
            "ttf": ttf,
            "mmf": mmf,
            "encoder": enc
        })

status_rows = []
status_path = RESULTS_ROOT / "partC_mimic_forecasting_status.csv"

to_run = []
for j in jobs:
    rn = run_name(j["dataset"], j["model"], j["seed"], j["modality"], j["ttf"], j["mmf"], j["encoder"])
    log_path = LOG_ROOT / f"{rn}.log"
    if SKIP_COMPLETED and log_contains_done(log_path):
        continue
    if (not FORCE_RERUN_FAILED) and log_contains_failure(log_path):
        continue
    to_run.append(j)

if MAX_RUNS_THIS_SESSION is not None:
    to_run = to_run[:MAX_RUNS_THIS_SESSION]

print("Queued MIMIC forecasting jobs:", len(to_run))

for idx, j in enumerate(to_run, 1):
    rn = run_name(j["dataset"], j["model"], j["seed"], j["modality"], j["ttf"], j["mmf"], j["encoder"])
    log_path = LOG_ROOT / f"{rn}.log"
    cmd = build_cmd(j["dataset"], j["model"], j["seed"], j["modality"], j["ttf"], j["mmf"], j["encoder"])

    print("\n" + "="*100)
    print(f"[{idx}/{len(to_run)}] {rn}")
    print("CMD:", " ".join(cmd))
    print("="*100)

    with open(log_path, "w", encoding="utf-8") as f:
        proc = subprocess.Popen(
            cmd,
            cwd=str(REPO_ROOT),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        for line in proc.stdout:
            print(line, end="")
            f.write(line)
        return_code = proc.wait()

    status_rows.append({
        "timestamp": datetime.now().isoformat(),
        "run_name": rn,
        "dataset": j["dataset"],
        "model": j["model"],
        "seed": j["seed"],
        "modality": j["modality"],
        "ttf_module": j["ttf"],
        "mmf_module": j["mmf"],
        "text_encoder": j["encoder"],
        "return_code": return_code,
        "log_file": str(log_path),
    })
    pd.DataFrame(status_rows).to_csv(status_path, index=False)

print("Saved:", status_path)

Queued MIMIC forecasting jobs: 11

====================================================================================================
[1/11] MIMIC__Informer__seed42__uni
CMD: /usr/bin/python3 main.py --dataset MIMIC --model Informer --split_method instance -b 8 --epoch 20 --seed 42
====================================================================================================
/usr/bin/python3: can't open file '/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py': [Errno 2] No such file or directory

====================================================================================================
[2/11] MIMIC__DLinear__seed42__uni
CMD: /usr/bin/python3 main.py --dataset MIMIC --model DLinear --split_method instance -b 8 --epoch 20 --seed 42
====================================================================================================
/usr/bin/python3: can't open file '/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py': [Errno 2] No such file or directory

====================================================================================================
[3/11] MIMIC__PatchTST__seed42__uni
CMD: /usr/bin/python3 main.py --dataset MIMIC --model PatchTST --split_method instance -b 8 --epoch 20 --seed 42
====================================================================================================
/usr/bin/python3: can't open file '/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py': [Errno 2] No such file or directory

====================================================================================================
[4/11] MIMIC__TimesNet__seed42__uni
CMD: /usr/bin/python3 main.py --dataset MIMIC --model TimesNet --split_method instance -b 8 --epoch 20 --seed 42
====================================================================================================
/usr/bin/python3: can't open file '/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py': [Errno 2] No such file or directory

====================================================================================================
[5/11] MIMIC__TimeMixer__seed42__uni
CMD: /usr/bin/python3 main.py --dataset MIMIC --model TimeMixer --split_method instance -b 8 --epoch 20 --seed 42
====================================================================================================
/usr/bin/python3: can't open file '/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py': [Errno 2] No such file or directory

====================================================================================================
[6/11] MIMIC__TimeLLM__seed42__uni
CMD: /usr/bin/python3 main.py --dataset MIMIC --model TimeLLM --split_method instance -b 8 --epoch 20 --seed 42
====================================================================================================
/usr/bin/python3: can't open file '/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py': [Errno 2] No such file or directory

====================================================================================================
[7/11] MIMIC__TTM__seed42__uni
CMD: /usr/bin/python3 main.py --dataset MIMIC --model TTM --split_method instance -b 8 --epoch 20 --seed 42
====================================================================================================
/usr/bin/python3: can't open file '/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py': [Errno 2] No such file or directory

====================================================================================================
[8/11] MIMIC__CRU__seed42__uni
CMD: /usr/bin/python3 main.py --dataset MIMIC --model CRU --split_method instance -b 8 --epoch 20 --seed 42
====================================================================================================
/usr/bin/python3: can't open file '/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py': [Errno 2] No such file or directory

====================================================================================================
[9/11] MIMIC__LatentODE__seed42__uni
CMD: /usr/bin/python3 main.py --dataset MIMIC --model LatentODE --split_method instance -b 8 --epoch 20 --seed 42
====================================================================================================
/usr/bin/python3: can't open file '/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py': [Errno 2] No such file or directory

====================================================================================================
[10/11] MIMIC__NeuralFlow__seed42__uni
CMD: /usr/bin/python3 main.py --dataset MIMIC --model NeuralFlow --split_method instance -b 8 --epoch 20 --seed 42
====================================================================================================
/usr/bin/python3: can't open file '/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py': [Errno 2] No such file or directory

====================================================================================================
[11/11] MIMIC__tPatchGNN__seed42__uni
CMD: /usr/bin/python3 main.py --dataset MIMIC --model tPatchGNN --split_method instance -b 8 --epoch 20 --seed 42 --patch_size 24 --nlayer 1 --te_dim 10 --node_dim 10 --hid_dim 32
====================================================================================================
/usr/bin/python3: can't open file '/content/drive/MyDrive/time_imm_project/IMM-TSF/main.py': [Errno 2] No such file or directory
Saved: /content/drive/MyDrive/time_imm_project/IMM-TSF/results_full/partC_mimic_forecasting_status.csv